// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class _2024GeologyCodes
{
    public string Geology { get; set; }

    public string Geology_Short { get; set; }

    public string Texture { get; set; }

    public string Texture_Short { get; set; }

    public string PrimaryLith { get; set; }

    public string PrimaryLith_Short { get; set; }

    public string SecondaryLith { get; set; }

    public string SecondaryLith_Short { get; set; }

    public string Hardness { get; set; }

    public string Hardness_Short { get; set; }
}