// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AA_ASSAY_tblStandardSampP2
{
    public string DataSet { get; set; }

    public string SampleID { get; set; }

    public string GenericMethod { get; set; }

    public string Element { get; set; }

    public string OrigMethod { get; set; }

    public string UnitCode { get; set; }

    public string LabElement { get; set; }

    public string Repeat { get; set; }

    public short Preferred { get; set; }

    public string AssayResult { get; set; }

    public float? AssayResultNum { get; set; }

    public string LabCode { get; set; }

    public string Batch_No { get; set; }

    public float? LimitLower { get; set; }

    public float? LimitUpper { get; set; }

    public string sysAssayStatus { get; set; }

    public DateTime? Load_Date { get; set; }

    public int PRIORITY { get; set; }

    public double? VALUE { get; set; }

    public string DSC { get; set; }
}