// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AA_DRILL_DESIGN_DETAILS_EXTENDED
{
    public string HOLEID { get; set; }

    public string SHORTID { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public string DESIGN_VERSION { get; set; }

    public double? HOLE_DEPTH { get; set; }

    public double? FEXRF_FROM { get; set; }

    public double? FEXRF_TO { get; set; }

    public double? SE4AD_FROM { get; set; }

    public double? SE4AD_TO { get; set; }

    public double? STANDARD_DEPTH { get; set; }

    public double? DUPLICATE_DEPTH { get; set; }

    public double? WET_METRES { get; set; }

    public string SUMP { get; set; }

    public double? GROUND_DISTURBED { get; set; }

    public double? EST_FE { get; set; }

    public double? EST_TOO { get; set; }

    public double? EST_BOO { get; set; }

    public double? EST_ORE_METRES { get; set; }

    public double? OVERBURDEN { get; set; }

    public int TWIN_WARNING { get; set; }

    public string PLANNED_GRID { get; set; }

    public int? COMPLETED_SPACING { get; set; }

    public int PRIORITY { get; set; }

    public string LEASE { get; set; }

    public string GDP { get; set; }

    public string REGION { get; set; }

    public string REGIONPIT { get; set; }

    public string SUBREGIONPIT { get; set; }

    public string MINING_SOURCE { get; set; }

    public string MINING_VERSION { get; set; }

    public DateOnly? MINING_START_DATE { get; set; }

    public DateOnly? MODEL_COMPLETE_DATE { get; set; }

    public DateOnly? ASSAY_COMPLETE_DATE { get; set; }

    public DateOnly? DRILLING_COMPLETE_DATE { get; set; }

    public DateOnly? PEGGED_DATE { get; set; }

    public DateOnly? CLEARED_DATE { get; set; }

    public DateOnly? DRILLED_DATE { get; set; }

    public DateOnly? LOGGED_DATE { get; set; }

    public int? DRILLED_LEADTIME { get; set; }

    public int? CURRENT_LEADTIME { get; set; }

    public string OVERALL_STATUS { get; set; }

    public string COLLAR_STATUS { get; set; }

    public double? EAST_25 { get; set; }

    public double? NORTH_25 { get; set; }

    public double? ACTUAL_FE { get; set; }

    public double? ACTUAL_TOO { get; set; }

    public double? ACTUAL_BOO { get; set; }

    public double? ACTUAL_ORE_METRES { get; set; }

    public string Geophys_Status { get; set; }
}