// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class aaDHSampQC_WETBULK_P1
{
    public string DataSet { get; set; }

    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string GenericMethod { get; set; }

    public string NAME { get; set; }

    public string Element { get; set; }

    public string OrigMethod { get; set; }

    public string UnitCode { get; set; }

    public string LabElement { get; set; }

    public string Repeat { get; set; }

    public short Preferred { get; set; }

    public string AssayResult { get; set; }

    public float? AssayResultNum { get; set; }

    public string LabCode { get; set; }

    public string LABJOBNO { get; set; }

    public float? LimitLower { get; set; }

    public float? LimitUpper { get; set; }

    public string sysAssayStatus { get; set; }

    public string LOADDATE { get; set; }

    public int PRIORITY { get; set; }

    public double? VALUE { get; set; }

    public string DSC { get; set; }
}