// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class aaDHSamp_P3
{
    public string SAMPLEID { get; set; }

    public string NAME { get; set; }

    public int PRIORITY { get; set; }

    public double? VALUE { get; set; }

    public string DSC { get; set; }

    public string LABJOBNO { get; set; }

    public DateTime LOADDATE { get; set; }

    public int? ANALYSISORDER { get; set; }
}