// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores details of the activity report itself. The activity report may be a DOR, a PLOD or some other type of periodical report of activities provided by a contractor.
/// </summary>
public partial class AC_ACTIVITYREPORT
{
    /// <summary>
    /// The unique identifier, within the contractor company, to identify the activity report.
    /// </summary>
    public string ACTIVITYREPORTCODE { get; set; }

    /// <summary>
    /// The unique identifier of the contractor company that is associated with this contract. It is the primary key of the COMPANY table.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// The unique identifier of the job that the activity report is associated with.
    /// </summary>
    public string JOBCODE { get; set; }

    /// <summary>
    /// The date of the activity report.
    /// </summary>
    public DateTime ACTIVITYREPORTDATE { get; set; }

    /// <summary>
    /// The unique identifier of the main piece of equipment against which activities are reported.
    /// </summary>
    public string EQUIPMENTCODE { get; set; }

    /// <summary>
    /// The shift during which the activities in the activity report were completed.
    /// </summary>
    public string SHIFT { get; set; }

    /// <summary>
    /// The contract category into which the report&apos;s contract must fall. It ties all the items in this report to the category of contract.
    /// </summary>
    public string CONTRACTCATEGORYCODE { get; set; }

    public virtual ICollection<AC_ACTIVITYREPORTBIGCOMMENT> AC_ACTIVITYREPORTBIGCOMMENT { get; set; } = new List<AC_ACTIVITYREPORTBIGCOMMENT>();

    public virtual ICollection<AC_ACTIVITYREPORTCOMMENT> AC_ACTIVITYREPORTCOMMENT { get; set; } = new List<AC_ACTIVITYREPORTCOMMENT>();

    public virtual ICollection<AC_ACTIVITYREPORTDETAILS> AC_ACTIVITYREPORTDETAILS { get; set; } = new List<AC_ACTIVITYREPORTDETAILS>();

    public virtual ICollection<AC_ACTIVITYREPORTITEM> AC_ACTIVITYREPORTITEM { get; set; } = new List<AC_ACTIVITYREPORTITEM>();

    public virtual COMPANY COMPANYCODENavigation { get; set; }

    public virtual AC_CONTRACTCATEGORY CONTRACTCATEGORYCODENavigation { get; set; }

    public virtual EQUIPMENT EQUIPMENTCODENavigation { get; set; }

    public virtual AC_JOB JOBCODENavigation { get; set; }

    public virtual SHIFT SHIFTNavigation { get; set; }
}