// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Comment table associated with AC_ACTIVITYREPORTITEM.
/// </summary>
public partial class AC_ACTIVITYREPORTITEMCOMMENT
{
    /// <summary>
    /// With COMPANYCODE and ITEMNUMBER, forms the unique identifier of the activity report item to which the comment belongs.
    /// </summary>
    public string ACTIVITYREPORTCODE { get; set; }

    /// <summary>
    /// With ACTIVITYREPORTCODE and ITEMNUMBER, forms the unique identifier of the activity report item to which the comment belongs.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// With COMPANYCODE and ACTIVITYREPORTCODE, forms the unique identifier of the activity report item to which the comment belongs.
    /// </summary>
    public int ITEMNUMBER { get; set; }

    /// <summary>
    /// The name of the virtual field and the foreign key to the lookup table.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The value of the virtual field.
    /// </summary>
    public string VALUE { get; set; }

    public virtual AC_ACTIVITYREPORTITEM AC_ACTIVITYREPORTITEM { get; set; }

    public virtual AC_ACTIVITYREPORTITEMCOMMENTCODE NAMENavigation { get; set; }
}