// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Code table associated with AC_ACTIVITYREPORTITEMDETAILS.
/// </summary>
public partial class AC_ACTIVITYREPORTITEMCODE
{
    /// <summary>
    /// The name of the virtual field.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// A description of this virtual field.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// The type of the data to be held in this virtual field. A foreign key to the DATATYPE lookup table.
    /// </summary>
    public string DATATYPE { get; set; }

    /// <summary>
    /// The units that can be applied to the virtual field. A foreign key to the UNITS lookup table.
    /// </summary>
    public string UNITS { get; set; }

    public virtual ICollection<AC_ACTIVITYREPORTITEMDETAILS> AC_ACTIVITYREPORTITEMDETAILS { get; set; } = new List<AC_ACTIVITYREPORTITEMDETAILS>();

    public virtual DATATYPE DATATYPENavigation { get; set; }
}