// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores details of individual items listed on an activity report. This may be quantities of consumables, depths drilled, etc.
/// </summary>
public partial class AC_ACTIVITYREPORTITEM
{
    /// <summary>
    /// With COMPANYCODE, forms the unique identifier for the activity report to which the item belongs.
    /// </summary>
    public string ACTIVITYREPORTCODE { get; set; }

    /// <summary>
    /// With ACTIVITYREPORTCODE, forms the unique identifier for the activity report to which the item belongs.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// The unique identifier of the specific item within the activity report that is identified by COMPANYCODE and ACTIVITYREPORTCODE.
    /// </summary>
    public int ITEMNUMBER { get; set; }

    /// <summary>
    /// The type of contract item for which the activity report item is providing reported values.
    /// </summary>
    public string CONTRACTITEMTYPECODE { get; set; }

    /// <summary>
    /// A cost code for the item reported.
    /// </summary>
    public string COSTCODE { get; set; }

    /// <summary>
    /// The date and time that an activity started or a cost was incurred. Mutually exclusive with ACTIVITYHOURS.
    /// </summary>
    public DateTime? STARTDATETIME { get; set; }

    /// <summary>
    /// The date and time that an activity ended. Mutually exclusive with ACTIVITYHOURS.
    /// </summary>
    public DateTime? ENDDATETIME { get; set; }

    /// <summary>
    /// The duration of an activity. Mutually exclusive with STARTDATETIME and ENDDATETIME.
    /// </summary>
    public decimal? ACTIVITYHOURS { get; set; }

    /// <summary>
    /// The value associated with the report item when the contract item type is defined for point data rather than range data.
    /// </summary>
    public double? SINGLEVALUE { get; set; }

    /// <summary>
    /// The start of a range value associated with the report item when the contract item type is defined for range data.
    /// </summary>
    public double? STARTVALUE { get; set; }

    /// <summary>
    /// The end of a range value associated with the report item when the contract item type is defined for range data.
    /// </summary>
    public double? ENDVALUE { get; set; }

    /// <summary>
    /// Any comments associated with the activity report item.
    /// </summary>
    public string COMMENT { get; set; }

    public virtual AC_ACTIVITYREPORT AC_ACTIVITYREPORT { get; set; }

    public virtual ICollection<AC_ACTIVITYREPORTITEMBIGCOMMENT> AC_ACTIVITYREPORTITEMBIGCOMMENT { get; set; } = new List<AC_ACTIVITYREPORTITEMBIGCOMMENT>();

    public virtual ICollection<AC_ACTIVITYREPORTITEMCOMMENT> AC_ACTIVITYREPORTITEMCOMMENT { get; set; } = new List<AC_ACTIVITYREPORTITEMCOMMENT>();

    public virtual ICollection<AC_ACTIVITYREPORTITEMDETAILS> AC_ACTIVITYREPORTITEMDETAILS { get; set; } = new List<AC_ACTIVITYREPORTITEMDETAILS>();

    public virtual ICollection<AC_ACTIVITYREPORTITEMPARAMETER> AC_ACTIVITYREPORTITEMPARAMETER { get; set; } = new List<AC_ACTIVITYREPORTITEMPARAMETER>();

    public virtual ICollection<AC_DESPATCHSENDACTIVITYREPORTITEM> AC_DESPATCHSENDACTIVITYREPORTITEM { get; set; } = new List<AC_DESPATCHSENDACTIVITYREPORTITEM>();

    public virtual ICollection<AC_HOLELOCATIONACTIVITYREPORTITEM> AC_HOLELOCATIONACTIVITYREPORTITEM { get; set; } = new List<AC_HOLELOCATIONACTIVITYREPORTITEM>();

    public virtual COST COSTCODENavigation { get; set; }
}