// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Code table associated with AC_ACTIVITYREPORTITEMBIGCOMMENT.
/// </summary>
public partial class AC_ACTIVITYREPORTITEMBIGCOMMENTCODE
{
    /// <summary>
    /// The name of the virtual field and the primary key of the lookup table.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// A description of this virtual field.
    /// </summary>
    public string DESCRIPTION { get; set; }

    public virtual ICollection<AC_ACTIVITYREPORTITEMBIGCOMMENT> AC_ACTIVITYREPORTITEMBIGCOMMENT { get; set; } = new List<AC_ACTIVITYREPORTITEMBIGCOMMENT>();
}