// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// BigComment table associated with AC_Contract. 
/// </summary>
public partial class AC_CONTRACTBIGCOMMENT
{
    /// <summary>
    /// The unique identifier for this instance of the contract.
    /// </summary>
    public string CONTRACTCODE { get; set; }

    /// <summary>
    /// The name of the virtual big comment field.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The value stored in the virtual big comment field.
    /// </summary>
    public string VALUE { get; set; }

    public virtual AC_CONTRACT CONTRACTCODENavigation { get; set; }

    public virtual AC_CONTRACTBIGCOMMENTCODE NAMENavigation { get; set; }
}