// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores details of the predefined types for items that can be included within a contract.
/// </summary>
public partial class AC_CONTRACTITEMTYPE
{
    /// <summary>
    /// The unique identifier for the contract item type.
    /// </summary>
    public string CONTRACTITEMTYPECODE { get; set; }

    /// <summary>
    /// Bit flag to identify contract item types that can be charged pro rata.
    /// </summary>
    public byte CANPRORATA { get; set; }

    /// <summary>
    /// A self join back to a parent contract item type code allowing hierarchies to be constructed.
    /// </summary>
    public string PARENTCONTRACTITEMTYPECODE { get; set; }

    /// <summary>
    /// Whether or not the report values applied should be a range.  The alternative is a just a single point.
    /// </summary>
    public byte ISRANGEDATA { get; set; }

    /// <summary>
    /// For single values, the value for the specified contract item type at the specified contract item type hierarchy level.
    /// </summary>
    public double? SINGLEVALUE { get; set; }

    /// <summary>
    /// For text values, the value for the specified contract item type at the specified contract item type hierarchy level.
    /// </summary>
    public string TEXTVALUE { get; set; }

    /// <summary>
    /// For value ranges, the start value for the specified contract item type at the specified contract item type hierarchy level.
    /// </summary>
    public double? STARTVALUE { get; set; }

    /// <summary>
    /// For value ranges, the end value for the specified contract item type at the specified contract item type hierarchy level.
    /// </summary>
    public double? ENDVALUE { get; set; }

    /// <summary>
    /// A description of the contract item type.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// The unit of measurement for the contract item type hierarchy.
    /// </summary>
    public string UNITS { get; set; }

    /// <summary>
    /// The unique identifier for the contract item type group.
    /// </summary>
    public string GROUPNAME { get; set; }

    public virtual AC_CONTRACTITEMTYPEGROUP GROUPNAMENavigation { get; set; }

    public virtual UNITS UNITSNavigation { get; set; }
}