// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores details of the items included within a contract.
/// </summary>
public partial class AC_CONTRACTITEM
{
    /// <summary>
    /// The identifier for the predefined contract item type associated with the item, part of a unique key.
    /// </summary>
    public string CONTRACTITEMTYPECODE { get; set; }

    /// <summary>
    /// The identifier of the contract in which the item resides, part of a unique key.
    /// </summary>
    public string CONTRACTCODE { get; set; }

    /// <summary>
    /// A value associated with the contract item.
    /// </summary>
    public double CONTRACTVALUE { get; set; }

    /// <summary>
    /// The unique identifier for a contract item.
    /// </summary>
    public long CONTRACTITEMID { get; set; }

    /// <summary>
    /// The expiry date of a contract rate for a contract item, part of a unique key.
    /// </summary>
    public DateTime? CONTRACTRATEENDDATE { get; set; }

    public virtual AC_CONTRACT CONTRACTCODENavigation { get; set; }
}