// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores details of the contract, possibly an SoR, between the company and its contractors.
/// </summary>
public partial class AC_CONTRACT
{
    /// <summary>
    /// The unique code identifying this instance of the contract.
    /// </summary>
    public string CONTRACTCODE { get; set; }

    /// <summary>
    /// The date from which this instance of the contract is effective.
    /// </summary>
    public DateTime CONTRACTSTARTDATE { get; set; }

    /// <summary>
    /// The date up to which this instance of the contract is effective.
    /// </summary>
    public DateTime? CONTRACTENDDATE { get; set; }

    /// <summary>
    /// The date up to which this instance of the contract is active.
    /// </summary>
    public DateTime? INACTIVEFROMDATE { get; set; }

    /// <summary>
    /// The category to which this contract applies.
    /// </summary>
    public string CONTRACTCATEGORYCODE { get; set; }

    public virtual ICollection<AC_CONTRACTBIGCOMMENT> AC_CONTRACTBIGCOMMENT { get; set; } = new List<AC_CONTRACTBIGCOMMENT>();

    public virtual ICollection<AC_CONTRACTCOMMENT> AC_CONTRACTCOMMENT { get; set; } = new List<AC_CONTRACTCOMMENT>();

    public virtual ICollection<AC_CONTRACTDETAILS> AC_CONTRACTDETAILS { get; set; } = new List<AC_CONTRACTDETAILS>();

    public virtual ICollection<AC_CONTRACTITEM> AC_CONTRACTITEM { get; set; } = new List<AC_CONTRACTITEM>();

    public virtual AC_CONTRACTCATEGORY CONTRACTCATEGORYCODENavigation { get; set; }

    public virtual CONTRACT CONTRACTCODENavigation { get; set; }

    public virtual ICollection<AC_JOB> JOBCODE { get; set; } = new List<AC_JOB>();
}