// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Provides a link between an activity report item and a specific despatch number. An item can be linked to either a single or to many despatch numbers where items are prorated across many despatch numbers.
/// </summary>
public partial class AC_DESPATCHSENDACTIVITYREPORTITEM
{
    /// <summary>
    /// The administrative code to track a batch of samples despatched to a laboratory.
    /// </summary>
    public string DESPATCHNO { get; set; }

    /// <summary>
    /// With COMPANYCODE and ITEMNUMBER, the unique identifier for the activity report item being linked to the despatch.
    /// </summary>
    public string ACTIVITYREPORTCODE { get; set; }

    /// <summary>
    /// With ACTIVITYREPORTCODE and ITEMNUMBER, the unique identifier for the activity report item being linked to the despatch.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// With ACTIVITYREPORTCODE and COMPANYCODE, the unique identifier for the activity report item being linked to the despatch.
    /// </summary>
    public int ITEMNUMBER { get; set; }

    /// <summary>
    /// The proportion of an item per despatch. Total cannot exceed 100%.
    /// </summary>
    public decimal? PRORATAPERCENT { get; set; }

    public virtual AC_ACTIVITYREPORTITEM AC_ACTIVITYREPORTITEM { get; set; }

    public virtual DESPATCHSEND DESPATCHNONavigation { get; set; }
}