// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Provides a link between an activity report item and a specific hole. An item can be linked to either a single hole or to many holes where items are prorated across many holes.
/// </summary>
public partial class AC_HOLELOCATIONACTIVITYREPORTITEM
{
    /// <summary>
    /// With PROJECTCODE, the unique identifier for the hole to which the activity report item is linked.
    /// </summary>
    public string HOLEID { get; set; }

    /// <summary>
    /// With HOLEID, the unique identifier for the hole to which the activity report item is linked.
    /// </summary>
    public string PROJECTCODE { get; set; }

    /// <summary>
    /// With COMPANYCODE and ITEMNUMBER, the unique identifier for the activity report item being linked to the hole.
    /// </summary>
    public string ACTIVITYREPORTCODE { get; set; }

    /// <summary>
    /// With ACTIVITYREPORTCODE and ITEMNUMBER, the unique identifier for the activity report item being linked to the hole.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// With ACTIVITYREPORTCODE and COMPANYCODE, the unique identifier for the activity report item being linked to the hole.
    /// </summary>
    public int ITEMNUMBER { get; set; }

    /// <summary>
    /// The proportion of an item per hole. Total cannot exceed 100%.
    /// </summary>
    public decimal? PRORATAPERCENT { get; set; }

    public virtual AC_ACTIVITYREPORTITEM AC_ACTIVITYREPORTITEM { get; set; }

    public virtual HOLELOCATION HOLELOCATION { get; set; }
}