// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores properties of a single invoice.
/// </summary>
public partial class AC_INVOICE
{
    /// <summary>
    /// The invoice number supplied by the contract company.
    /// </summary>
    public string INVOICENUMBER { get; set; }

    /// <summary>
    /// The company code of the contract company.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// A cost code used in the invoice.
    /// </summary>
    public string COSTCODE { get; set; }

    /// <summary>
    /// The date when the invoice was issued.
    /// </summary>
    public DateTime? INVOICEISSUEDATE { get; set; }

    /// <summary>
    /// The date when the invoice was received.
    /// </summary>
    public DateTime? INVOICERECEIVEDATE { get; set; }

    /// <summary>
    /// The start date of the invocing period.
    /// </summary>
    public DateTime INVOICEPERIODSTARTDATE { get; set; }

    /// <summary>
    /// The end date of the invoicing period.
    /// </summary>
    public DateTime INVOICEPERIODENDDATE { get; set; }

    /// <summary>
    /// The total amount requested for the invoiced work completed.
    /// </summary>
    public decimal INVOICEAMOUNT { get; set; }

    /// <summary>
    /// The total amount paid for the invoiced work completed.
    /// </summary>
    public decimal? INVOICEPAIDAMOUNT { get; set; }

    /// <summary>
    /// The date when the invoice was paid.
    /// </summary>
    public DateTime? INVOICEPAIDDATE { get; set; }

    public virtual ICollection<AC_INVOICEACTIVITY> AC_INVOICEACTIVITY { get; set; } = new List<AC_INVOICEACTIVITY>();

    public virtual ICollection<AC_INVOICEBIGCOMMENT> AC_INVOICEBIGCOMMENT { get; set; } = new List<AC_INVOICEBIGCOMMENT>();

    public virtual ICollection<AC_INVOICEDETAILS> AC_INVOICEDETAILS { get; set; } = new List<AC_INVOICEDETAILS>();

    public virtual COMPANY COMPANYCODENavigation { get; set; }

    public virtual COST COSTCODENavigation { get; set; }
}