// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Big comment table associated with AC_INVOICE.
/// </summary>
public partial class AC_INVOICEBIGCOMMENT
{
    /// <summary>
    /// The invoice number supplied by the contract company.
    /// </summary>
    public string INVOICENUMBER { get; set; }

    /// <summary>
    /// The company code of the contract company.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// The name of the big comment virtual field.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The value of the big comment virtual field.
    /// </summary>
    public string VALUE { get; set; }

    public virtual AC_INVOICE AC_INVOICE { get; set; }

    public virtual AC_INVOICEBIGCOMMENTCODE NAMENavigation { get; set; }
}