// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Comment table associated with AC_JOB. 
/// </summary>
public partial class AC_JOBCOMMENT
{
    /// <summary>
    /// A unique code for the job.
    /// </summary>
    public string JOBCODE { get; set; }

    /// <summary>
    /// The name of the virtual comment field.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The value stored in the virtual comment field.
    /// </summary>
    public string VALUE { get; set; }

    public virtual AC_JOB JOBCODENavigation { get; set; }

    public virtual AC_JOBCOMMENTCODE NAMENavigation { get; set; }
}