// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AdmCompoundVirtualTable
{
    public string CompoundName { get; set; }

    public int? OrderNumber { get; set; }

    public string VirtualTableName { get; set; }
}