// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the Parameters for a Derived Field.
/// </summary>
public partial class AdmDerivedFieldParameter
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int AdmDerivedFieldParameterId { get; set; }

    /// <summary>
    /// The Derived Field this parameter relates to.
    /// </summary>
    public int AdmDerivedFieldId { get; set; }

    /// <summary>
    /// The component of the derived field this parameter provides.
    /// </summary>
    public string Name { get; set; }

    public virtual AdmDerivedField AdmDerivedField { get; set; }

    public virtual ICollection<CompoundField> CompoundField { get; set; } = new List<CompoundField>();
}