// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Defines the ADM processing change level at which the given error message is processed.
/// </summary>
public partial class AdmErrorMessage
{
    /// <summary>
    /// The error message type for this warning.
    /// </summary>
    public int ErrorMessageId { get; set; }

    /// <summary>
    /// The processing type to which this warning type relates.
    /// </summary>
    public int ProcessingTypeId { get; set; }

    /// <summary>
    /// The ADM change level at which this error message is processed.
    /// </summary>
    public int? AdmChangeLevel { get; set; }

    /// <summary>
    /// Whether or not to base the change level cut off logic on the original processing change level, or the final resolved one.
    /// </summary>
    public bool BaseOnOriginalChangeLevel { get; set; }

    public virtual AdmChangeLevel AdmChangeLevelNavigation { get; set; }

    public virtual ICollection<AdmErrorMessageProcedure> AdmErrorMessageProcedure { get; set; } = new List<AdmErrorMessageProcedure>();

    public virtual ErrorMessage ErrorMessage { get; set; }

    public virtual ProcessingType ProcessingType { get; set; }
}