// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Maintains an cache of excluded virtual fields, in order to speed up MetaSystem processing.
/// </summary>
public partial class AdmFailedVirtualField
{
    /// <summary>
    /// The name of virtual field.
    /// </summary>
    public string VirtualFieldName { get; set; }

    /// <summary>
    /// The name of code table for the virtual field.
    /// </summary>
    public string SourceName { get; set; }

    /// <summary>
    /// The most significant error which caused the exclusion of the derived field.
    /// </summary>
    public int ErrorMessageId { get; set; }

    /// <summary>
    /// The arguments to pass to the error message format.
    /// </summary>
    public string Arguments { get; set; }
}