// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AdmHoleGridLocalRankedCoordinate
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double? X { get; set; }

    public double? Y { get; set; }

    public double? Z { get; set; }

    public string GRIDNAME { get; set; }

    public string COORDINATESET { get; set; }
}