// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// An integration with an external data source.
/// </summary>
public partial class AdmIntegration
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int AdmIntegrationId { get; set; }

    /// <summary>
    /// The data associated with the integration.
    /// </summary>
    public string IntegrationData { get; set; }

    /// <summary>
    /// The type of integration.
    /// </summary>
    public string IntegrationType { get; set; }

    /// <summary>
    /// The date the data was received.
    /// </summary>
    public DateTime DateReceived { get; set; }

    public virtual ICollection<AdmIntegrationSection> AdmIntegrationSection { get; set; } = new List<AdmIntegrationSection>();
}