// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// An integration section contained in an integration.
/// </summary>
public partial class AdmIntegrationSection
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int AdmIntegrationSectionId { get; set; }

    /// <summary>
    /// The ID of the integration the section belongs to.
    /// </summary>
    public int AdmIntegrationId { get; set; }

    /// <summary>
    /// The type of integration section.
    /// </summary>
    public string IntegrationSectionType { get; set; }

    /// <summary>
    /// A flag indicating whether the integration section has been processed.
    /// </summary>
    public bool IsProcessed { get; set; }

    public virtual AdmIntegration AdmIntegration { get; set; }
}