// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Scheduled job runs are recorded here until processing is complete.
/// </summary>
public partial class AdmJobRun
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int AdmJobRunId { get; set; }

    /// <summary>
    /// The ID of the job being run.
    /// </summary>
    public int AdmJobId { get; set; }

    /// <summary>
    /// The Datetime the job run started.
    /// </summary>
    public DateTime StartedDatetime { get; set; }

    /// <summary>
    /// The run details in an xml format.
    /// </summary>
    public string JobRunDetails { get; set; }

    public virtual AdmJob AdmJob { get; set; }
}