// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Tasks that will be run in order by their parent Job.
/// </summary>
public partial class AdmJobTask
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int AdmJobTaskId { get; set; }

    /// <summary>
    /// The name of the AdmJobTask.
    /// </summary>
    public string Label { get; set; }

    /// <summary>
    /// A description of the AdmJobTask.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// The ID of a record in the AcqManagement.AdmJob table determining which AdmJob owns this task.
    /// </summary>
    public int AdmJobId { get; set; }

    /// <summary>
    /// Flag indicating whether this task should be run.
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// A number determining the order the parent AdmJob should run its associated tasks.
    /// </summary>
    public int OrderNumber { get; set; }

    /// <summary>
    /// The field storing the acQuire4 task package MIME value.
    /// </summary>
    public byte[] PackageBinaryValue { get; set; }

    /// <summary>
    /// The field storing the acQuire4 task package MIME type.
    /// </summary>
    public string PackageBinaryType { get; set; }

    /// <summary>
    /// Flag indicating if the parent Job should stop if this AdmJobTasks fails.
    /// </summary>
    public bool StopOnError { get; set; }

    /// <summary>
    /// Whether an email should be sent as part of the job task.
    /// </summary>
    public bool SendMail { get; set; }

    public virtual AdmJob AdmJob { get; set; }

    public virtual ICollection<AdmMailTemplate> AdmMailTemplate { get; set; } = new List<AdmMailTemplate>();
}