// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the MIME fields to be created.
/// </summary>
public partial class AdmManualUriField
{
    /// <summary>
    /// The name to be given to the uri field.
    /// </summary>
    public string UriFieldName { get; set; }

    /// <summary>
    /// The schema of the table that this mime field is from.
    /// </summary>
    public string TableSchema { get; set; }

    /// <summary>
    /// The name of the table that this mime field is from.
    /// </summary>
    public string TableName { get; set; }

    /// <summary>
    /// The name of the field containing the information for the path of the uri.
    /// </summary>
    public string PathFieldName { get; set; }
}