// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Compounds to be included even when compound is unused and IncludeUnusedAdmCompounds is turned off.
/// </summary>
public partial class AdmManualCompoundInclusion
{
    /// <summary>
    /// The name of the compound which will be included .
    /// </summary>
    public string Name { get; set; }
}