// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details a queue of mail items that need to be sent.
/// </summary>
public partial class AdmMailQueue
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int AdmMailQueueId { get; set; }

    /// <summary>
    /// The serialized information about the mail.
    /// </summary>
    public string MailData { get; set; }

    public virtual ICollection<AdmMailAttachment> AdmMailAttachment { get; set; } = new List<AdmMailAttachment>();
}