// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Defines the ADM processing change level at which the given processing event type trigger is processed.
/// </summary>
public partial class AdmProcessingTypeEventType
{
    /// <summary>
    /// The relevant processing type.
    /// </summary>
    public int ProcessingTypeId { get; set; }

    /// <summary>
    /// The relevant processing event type which might trigger this process.
    /// </summary>
    public int ProcessingEventTypeId { get; set; }

    /// <summary>
    /// The ADM change level at which this processing event type should be processed.
    /// </summary>
    public int AdmChangeLevel { get; set; }

    public virtual AdmChangeLevel AdmChangeLevelNavigation { get; set; }

    public virtual ProcessingTypeEventType ProcessingTypeEventType { get; set; }
}