// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the compounds which will be listed in AcQuire Object Models.
/// </summary>
public partial class AdmQomCompoundAttribute
{
    /// <summary>
    /// The name of the attribute.
    /// </summary>
    public string AdmQomAttributeName { get; set; }

    /// <summary>
    /// The qom compound against which it is associated.
    /// </summary>
    public int AdmQomCompoundId { get; set; }

    /// <summary>
    /// The type of attribute.
    /// </summary>
    public string AttributeType { get; set; }

    /// <summary>
    /// The xml definition.
    /// </summary>
    public string Definition { get; set; }

    public int Preference { get; set; }

    /// <summary>
    /// The Adm module on which this attribute depends.
    /// </summary>
    public string AdmModuleName { get; set; }

    public virtual AdmQomCompound AdmQomCompound { get; set; }
}