// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AdmQomGeologyIntervalCompoundVirtualField
{
    public string CompoundName { get; set; }

    public int AdmQomCompoundId { get; set; }

    public string PrimaryCode { get; set; }

    public string CodeTable { get; set; }

    public string VirtualFieldName { get; set; }
}