// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// List of the source and target compound relationships that are expected in the object model.
/// </summary>
public partial class AdmQomRelationship
{
    /// <summary>
    /// The source compound of the relationship.
    /// </summary>
    public int SourceQomCompoundId { get; set; }

    /// <summary>
    /// The target compound of the relationship.
    /// </summary>
    public int TargetQomCompoundId { get; set; }

    /// <summary>
    /// Whether the source is a parent of the target, or default to relationships existing value when not provided.
    /// </summary>
    public bool? IsParent { get; set; }

    /// <summary>
    /// Flag indicating that the relationship must be set on the source compound.
    /// </summary>
    public bool? IsRequired { get; set; }

    /// <summary>
    /// The label to be used for the relationship.
    /// </summary>
    public string Label { get; set; }

    public virtual AdmQomCompound SourceQomCompound { get; set; }

    public virtual AdmQomCompound TargetQomCompound { get; set; }
}