// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Definition of a QOM Inherited Compound.
/// </summary>
public partial class AdmQomInheritedCompound
{
    /// <summary>
    /// The unique identifier primary key.
    /// </summary>
    public Guid AdmQomInheritedCompoundGlobalId { get; set; }

    /// <summary>
    /// The name to give the compound upon creation.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The default label of the compound.
    /// </summary>
    public string Label { get; set; }

    /// <summary>
    /// The identity of the qom compound upon which this inherited compound is based..
    /// </summary>
    public int AdmQomCompoundId { get; set; }

    /// <summary>
    /// The category through which this compound is presented.
    /// </summary>
    public Guid? ObjectCategoryGlobalId { get; set; }

    /// <summary>
    /// The Json string defining the inherited compound.
    /// </summary>
    public string PropertyObjectData { get; set; }

    public virtual AdmQomCompound AdmQomCompound { get; set; }

    public virtual AdmQomObjectCategory ObjectCategoryGlobal { get; set; }
}