// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Header record for an ADM Context Defintion.
/// </summary>
public partial class AdmQomContextDefinition
{
    /// <summary>
    /// The identity of context definition and its eventual property object.
    /// </summary>
    public Guid PropertyObjectGlobalId { get; set; }

    /// <summary>
    /// The label of the Context Definition.
    /// </summary>
    public string Label { get; set; }

    /// <summary>
    /// The description of the Context Definition.
    /// </summary>
    public string Description { get; set; }

    public virtual ICollection<AdmQomCompound> AdmQomCompound { get; set; } = new List<AdmQomCompound>();
}