// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Record of an QOM object category.
/// </summary>
public partial class AdmQomObjectCategory
{
    /// <summary>
    /// The unique identifier primary key.
    /// </summary>
    public Guid ObjectCategoryGlobalId { get; set; }

    /// <summary>
    /// The name of the object category.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The default label of the object category, which is to be overriden by Localization.
    /// </summary>
    public string Label { get; set; }

    /// <summary>
    /// The type of the object category.
    /// </summary>
    public string ObjectCategoryType { get; set; }

    /// <summary>
    /// The parent user object category, if there is one.
    /// </summary>
    public Guid? ParentObjectCategoryGlobalId { get; set; }

    /// <summary>
    /// The name of the module on which the QOM category depends.
    /// </summary>
    public string AdmModuleName { get; set; }

    public virtual ICollection<AdmQomInheritedCompound> AdmQomInheritedCompound { get; set; } = new List<AdmQomInheritedCompound>();

    public virtual ICollection<AdmQomObjectCategory> InverseParentObjectCategoryGlobal { get; set; } = new List<AdmQomObjectCategory>();

    public virtual AdmQomObjectCategory ParentObjectCategoryGlobal { get; set; }

    public virtual ICollection<AdmQomCompound> AdmQomCompound { get; set; } = new List<AdmQomCompound>();
}