// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores information on the category paths related to QOM compounds.
/// </summary>
public partial class AdmQomCompoundCategoryPath
{
    /// <summary>
    /// The identifier for the QOM compound that is related to this category path.
    /// </summary>
    public int AdmQomCompoundId { get; set; }

    /// <summary>
    /// The identifier for the category path being related to by this QOM compound.
    /// </summary>
    public int AdmQomCategoryPathId { get; set; }

    /// <summary>
    /// The order in which the compound will be listed within its category in the UI.
    /// </summary>
    public int OrderNumber { get; set; }

    /// <summary>
    /// The name of the ADM module to which the category path and QOM compound combination is related.
    /// </summary>
    public string AdmModuleName { get; set; }

    /// <summary>
    /// An optional attribute of the given compound which fields in the compound should be grouped by, by default.
    /// </summary>
    public string DefaultGroupingAttribute { get; set; }

    public virtual AdmQomCategoryPath AdmQomCategoryPath { get; set; }

    public virtual AdmQomCompound AdmQomCompound { get; set; }
}