// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AdmQomCompoundName
{
    public string Name { get; set; }

    public int AdmQomCompoundId { get; set; }

    public bool IsGeologyInterval { get; set; }

    public bool IsGeologyIntervalJoin { get; set; }

    public string PrimaryCode { get; set; }
}