// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the range base tables that need to be configured for derived relationships.
/// </summary>
public partial class AdmRelationshipRange
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int RelationshipRangeId { get; set; }

    /// <summary>
    /// The base compound that derived relationships are to be based on.
    /// </summary>
    public string BaseCompound { get; set; }

    /// <summary>
    /// Defines if the compound is a range or depth compound.
    /// </summary>
    public bool IsRange { get; set; }

    /// <summary>
    /// The from field name if this is a range compound.
    /// </summary>
    public string FromField { get; set; }

    /// <summary>
    /// The to field name if this is a range compound.
    /// </summary>
    public string ToField { get; set; }

    /// <summary>
    /// The depth field name if this is a depth compound.
    /// </summary>
    public string DepthField { get; set; }

    public virtual ICollection<AdmRelationshipRangeDefaultFilter> AdmRelationshipRangeDefaultFilter { get; set; } = new List<AdmRelationshipRangeDefaultFilter>();

    public virtual ICollection<AdmRelationshipRangeDefaultOrder> AdmRelationshipRangeDefaultOrder { get; set; } = new List<AdmRelationshipRangeDefaultOrder>();

    public virtual ICollection<AdmRelationshipRangeIntersectPath> AdmRelationshipRangeIntersectPath { get; set; } = new List<AdmRelationshipRangeIntersectPath>();
}