// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the path to a common compound for this range table, to facilitate identifying which range compounds can be linked.
/// </summary>
public partial class AdmRelationshipRangeIntersectPath
{
    /// <summary>
    /// The Relationship Range Id from the AdmRelationshipRange table.
    /// </summary>
    public int RelationshipRangeId { get; set; }

    /// <summary>
    /// The order in which the intersect path flows.
    /// </summary>
    public int OrderNumber { get; set; }

    /// <summary>
    /// The source of this intersect step.
    /// </summary>
    public string SourceCompound { get; set; }

    /// <summary>
    /// The destination of this intersect path.
    /// </summary>
    public string DestinationCompound { get; set; }

    public virtual AdmRelationshipRange RelationshipRange { get; set; }
}