// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the ordering to be applied to the range base tables for derived relationships.
/// </summary>
public partial class AdmRelationshipRangeDefaultOrder
{
    /// <summary>
    /// The Relationship Range Id from the AdmRelationshipRange table.
    /// </summary>
    public int RelationshipRangeId { get; set; }

    /// <summary>
    /// The order in which to use the order fields.
    /// </summary>
    public int OrderNumber { get; set; }

    /// <summary>
    /// The field to order by.
    /// </summary>
    public string OrderField { get; set; }

    /// <summary>
    /// Should the field be ordered descending.
    /// </summary>
    public bool IsDescending { get; set; }

    public virtual AdmRelationshipRange RelationshipRange { get; set; }
}