// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Table to assist in the normalization of ADM value range conditions.
/// </summary>
public partial class AdmValueRange
{
    /// <summary>
    /// The field attribute identifier.
    /// </summary>
    public int FieldAttributeId { get; set; }

    /// <summary>
    /// The minimum acceptable value.
    /// </summary>
    public double Minimum { get; set; }

    /// <summary>
    /// The maximum acceptable value.
    /// </summary>
    public double Maximum { get; set; }

    /// <summary>
    /// A Cache of the condition of a between minimum and maximum comparison.
    /// </summary>
    public string Condition { get; set; }

    public virtual ICollection<AdmValueRangeFieldType> AdmValueRangeFieldType { get; set; } = new List<AdmValueRangeFieldType>();

    public virtual FieldAttribute FieldAttribute { get; set; }
}