// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AdmViewCompoundScriptFilter
{
    public int ViewId { get; set; }

    public int ViewCompoundId { get; set; }

    public string ScriptText { get; set; }

    public int IsRootCondition { get; set; }
}