// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// AreaCode stores the names of the virtual fields for the Areas compound definition. 
/// </summary>
public partial class AREACODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public string UNITS { get; set; }

    public virtual ICollection<AREADETAILS> AREADETAILS { get; set; } = new List<AREADETAILS>();

    public virtual DATATYPE DATATYPENavigation { get; set; }
}