// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class ASSAYTRANSLATION
{
    public string ATNAME { get; set; }

    public string SCNAME { get; set; }

    public double ATVALUE { get; set; }

    public string SCVALUE { get; set; }

    public string EXPRULE1 { get; set; }

    public string EXPRULE2 { get; set; }
}