// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Scheduled job runs are recorded here until processing is complete.
/// </summary>
public partial class AUTO_JOBRUN
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int JOBRUNID { get; set; }

    /// <summary>
    /// The ID of the job being run.
    /// </summary>
    public int JOBID { get; set; }

    /// <summary>
    /// The Datetime the job run started.
    /// </summary>
    public DateTime STARTDATETIME { get; set; }

    /// <summary>
    /// The run details in an xml format.
    /// </summary>
    public string JOBRUNDETAILS { get; set; }

    public virtual AUTO_JOB JOB { get; set; }
}