// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// An integration section contained in an integration.
/// </summary>
public partial class AUTO_INTEGRATIONSECTION
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int INTEGRATIONSECTIONID { get; set; }

    /// <summary>
    /// The ID of the integration the section belongs to.
    /// </summary>
    public int INTEGRATIONID { get; set; }

    /// <summary>
    /// The type of integration section.
    /// </summary>
    public string INTEGRATIONSECTIONTYPE { get; set; }

    /// <summary>
    /// A flag indicating whether the integration section has been processed.
    /// </summary>
    public bool ISPROCESSED { get; set; }

    public virtual AUTO_INTEGRATION INTEGRATION { get; set; }
}