// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Tasks that will be run in order by their parent Job.
/// </summary>
public partial class AUTO_JOBTASK
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int JOBTASKID { get; set; }

    /// <summary>
    /// The name of the AdmJobTask.
    /// </summary>
    public string LABEL { get; set; }

    /// <summary>
    /// A description of the AdmJobTask.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// The ID of a record in the AcqManagement.AdmJob table determining which AdmJob owns this task.
    /// </summary>
    public int JOBID { get; set; }

    /// <summary>
    /// Flag indicating whether this task should be run.
    /// </summary>
    public bool ISENABLED { get; set; }

    /// <summary>
    /// A number determining the order the parent AdmJob should run its associated tasks.
    /// </summary>
    public int ORDERNUMBER { get; set; }

    /// <summary>
    /// The field storing the acQuire4 task package MIME value.
    /// </summary>
    public byte[] PACKAGEBINARYVALUE { get; set; }

    /// <summary>
    /// The field storing the acQuire4 task package MIME type.
    /// </summary>
    public string PACKAGEBINARYTYPE { get; set; }

    /// <summary>
    /// Flag indicating if the parent Job should stop if this AdmJobTasks fails.
    /// </summary>
    public bool STOPONERROR { get; set; }

    /// <summary>
    /// Whether an email should be sent as part of the job task.
    /// </summary>
    public bool SENDMAIL { get; set; }

    public virtual AUTO_JOB JOB { get; set; }

    public virtual ICollection<AUTO_MAILTEMPLATE> MAILTEMPLATE { get; set; } = new List<AUTO_MAILTEMPLATE>();
}