// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Defines a schedule that can be used to define when external tasks should be run.
/// </summary>
public partial class AUTO_SCHEDULE
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int SCHEDULEID { get; set; }

    /// <summary>
    /// The name of the schedule. This is not required.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// Whether the schedule is enabled (1) or disabled (0).
    /// </summary>
    public bool ISENABLED { get; set; }

    /// <summary>
    /// How frequently a task should be run for this schedule. This field is a bit flag.
    /// 					1  = Once only
    /// 					4  = Every day
    /// 					8  = Weekly (days of week can be specified by FrequencyInterval)
    /// 					16 = Monthly (the numbered day of the month will be specified by FrequencyInterval)
    /// 					32 = Monthly relative (FrequencyInterval and FrequencyRelativeInterval determine the days in the month)
    /// 				
    /// </summary>
    public int FREQUENCYTYPE { get; set; }

    /// <summary>
    /// Further defines when a task should be run for this schedule. See the relevant
    /// 					freq_interval documentation at https:
    /// 				
    /// </summary>
    public int FREQUENCYINTERVAL { get; set; }

    /// <summary>
    /// Further defines when a task should be run for this schedule. This is only used when
    /// 					FrequencyType is 32 (monthly relative). It&apos;s been modified slightly from SQL&apos;s implementation to
    /// 					cater for the 5th day of the month. This field is a bit flag.
    /// 					0  = Unused
    /// 					1  = First (e.g. First Wednesday every month)
    /// 					2  = Second
    /// 					4  = Third
    /// 					8  = Fourth
    /// 					16 = Fifth
    /// 					32 = Last
    /// 				
    /// </summary>
    public int FREQUENCYRELATIVEINTERVAL { get; set; }

    /// <summary>
    /// The first date that a task or event occurs.
    /// </summary>
    public int ACTIVESTARTDATE { get; set; }

    /// <summary>
    /// The last date that a task or event can occur.
    /// </summary>
    public int? ACTIVEENDDATE { get; set; }

    /// <summary>
    /// The time of day that a task using this schedule should be run.
    /// 					Time is formatted HHMMSS, using a 24-hour clock.
    /// 				
    /// </summary>
    public int ACTIVESTARTTIME { get; set; }

    /// <summary>
    /// The time of day that a task using this schedule should be terminated, if it is still running.
    /// 					Time is formatted HHMMSS, using a 24-hour clock.
    /// 				
    /// </summary>
    public int? ACTIVEENDTIME { get; set; }

    public int? FREQUENCYSUBDAYTYPE { get; set; }

    public int? FREQUENCYSUBDAYINTERVAL { get; set; }

    public virtual ICollection<AUTO_CACHEGROUP> AUTO_CACHEGROUP { get; set; } = new List<AUTO_CACHEGROUP>();

    public virtual ICollection<AUTO_JOB> AUTO_JOB { get; set; } = new List<AUTO_JOB>();
}