// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AV_GIS_ApprovedHole_NotDrilledYet
{
    public string PROJECTCODE { get; set; }

    public string HOLEID { get; set; }

    public string Hole_Type { get; set; }

    public string Planned_Date { get; set; }

    public string Planned_MineDate { get; set; }

    public string Lease_ID { get; set; }

    public string Hole_Status { get; set; }

    public string Program_ID { get; set; }

    public string Peg_ID { get; set; }

    public string GDA94Z50_Grid_ID { get; set; }

    public double? GDA94Z50_North { get; set; }

    public double? GDA94Z50_East { get; set; }

    public double? GDA94Z50_RL { get; set; }

    public double? Max_Depth { get; set; }

    public string Planned_Depth { get; set; }

    public string Planned_WaterDepth { get; set; }

    public string Leadtime { get; set; }

    public string Contracted_Year { get; set; }
}