// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AV_GIS_Water_Conductivity
{
    public string DataSet { get; set; }

    public string Hole_ID { get; set; }

    public double? Max_Depth { get; set; }

    public string GDA94Z50_Grid_ID { get; set; }

    public double? GDA94Z50_North { get; set; }

    public double? GDA94Z50_East { get; set; }

    public string Date_Measured { get; set; }

    public double Depth_Measured { get; set; }

    public string Conductivity { get; set; }

    public string Temperature { get; set; }
}