// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AV_GIS_Water_Dipping
{
    public string DataSet { get; set; }

    public string Hole_ID { get; set; }

    public double? Max_Depth { get; set; }

    public string GDA94Z50_Grid_ID { get; set; }

    public double? GDA94Z50_North { get; set; }

    public double? GDA94Z50_East { get; set; }

    public string Date_water_meas { get; set; }

    public double Water_table_Valid { get; set; }
}