// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AV_MOD_Survey_Valid
{
    public string HOLEID { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public double DEPTH { get; set; }

    public double? AZIM { get; set; }

    public double? DIP { get; set; }

    public string TYPE { get; set; }
}