// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AV_MOD_Collar_Status
{
    public string HOLEID { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public double? DEPTH { get; set; }

    public string STATUS { get; set; }

    public string TYPE { get; set; }

    public string LEASE { get; set; }

    public string CYEAR { get; set; }

    public int? DYEAR { get; set; }

    public int? DMONTH { get; set; }

    public int? LEAD { get; set; }

    public string REGION { get; set; }

    public string MINESURVEY { get; set; }

    public string GEOPHYSURVEY { get; set; }

    public string XRFASSAY { get; set; }

    public string GEOLOGGED { get; set; }

    public string DESTROY { get; set; }
}