// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class AV_MOD_Data
{
    public string PROJECTCODE { get; set; }

    public double PRIORITY { get; set; }

    public string HOLEID { get; set; }

    public double? Northing_D { get; set; }

    public double? Easting_D { get; set; }

    public double? Elevation_D { get; set; }

    public double GEOLFROM { get; set; }

    public double GEOLTO { get; set; }

    public string Converted_Strat { get; set; }

    public string Converted_Strand { get; set; }

    public string Validated_Strat { get; set; }

    public string Validated_Strand { get; set; }

    public string Strat { get; set; }

    public string Strand { get; set; }

    public string P_Strat { get; set; }

    public string P_Strand { get; set; }

    public string P_PRIORITY { get; set; }

    public double? Fe_Best_D { get; set; }

    public double? SiO2_Best_D { get; set; }

    public double? Al2O3_Best_D { get; set; }

    public double? P_Best_D { get; set; }

    public double? Mn_Best_D { get; set; }

    public double? LOI_Best_D { get; set; }

    public double? S_Best_D { get; set; }

    public double? TiO2_Best_D { get; set; }

    public double? CaO_Best_D { get; set; }

    public double? MgO_Best_D { get; set; }

    public double? K2O_Best_D { get; set; }

    public double? As_Best_D { get; set; }

    public double? Ba_Best_D { get; set; }

    public double? Cl_Best_D { get; set; }

    public double? Co_Best_D { get; set; }

    public double? Cr_Best_D { get; set; }

    public double? Cu_Best_D { get; set; }

    public double? Na2O_Best_D { get; set; }

    public double? Ni_Best_D { get; set; }

    public double? Pb_Best_D { get; set; }

    public double? Sn_Best_D { get; set; }

    public double? Sr_Best_D { get; set; }

    public double? V_Best_D { get; set; }

    public double? Zn_Best_D { get; set; }

    public double? Zr_Best_D { get; set; }

    public double? Density_GP_D { get; set; }

    public double? Gamma_GP_D { get; set; }

    public double? Magsus_GP_D { get; set; }

    public int? COLOUR_D { get; set; }

    public string Met_HARD_pct { get; set; }

    public string Met_MEDIUM_pct { get; set; }

    public string Met_FRIABLE_pct { get; set; }
}