// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class BAK_QLR_GEOINTERVAL2020_02_05_11_23_29
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double? GEOLFROM { get; set; }

    public double? GEOLTO { get; set; }

    public double? PRIORITY { get; set; }

    public string ACTION_QLR { get; set; }

    public DateTime? ACTIONDATE_QLR { get; set; }

    public short? SESSID_QLR { get; set; }

    public long CHANGENUMBER { get; set; }

    public Guid? GLOBALID { get; set; }
}