// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Joining table that links ViewCompounds into groups that are scheduled for caching.
/// </summary>
public partial class CacheGroupViewCompound
{
    /// <summary>
    /// The ID of a record in AcqPresentation.CacheGroup.
    /// </summary>
    public int CacheGroupId { get; set; }

    /// <summary>
    /// The ID of a record in AcqPresentation.ViewCompound.
    /// </summary>
    public int ViewCompoundId { get; set; }

    /// <summary>
    /// The last time that caching for the view compound started.
    /// </summary>
    public DateTime? LastStartTime { get; set; }

    /// <summary>
    /// The last time that caching for the view compound completed successfully.
    /// </summary>
    public DateTime? LastSuccessfulTime { get; set; }

    public virtual CacheGroup CacheGroup { get; set; }

    public virtual ViewCompound ViewCompound { get; set; }
}