// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details information pertaining to a saved canvas.
/// </summary>
public partial class Canvas
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int CanvasId { get; set; }

    /// <summary>
    /// The Label for the canvas.
    /// </summary>
    public string Label { get; set; }

    /// <summary>
    /// The Creator of the canvas.
    /// </summary>
    public int? CreatorId { get; set; }

    /// <summary>
    /// The xml data comprising the canvas.
    /// </summary>
    public string CanvasData { get; set; }

    public virtual User Creator { get; set; }

    public virtual ICollection<View> View { get; set; } = new List<View>();

    public virtual ICollection<UserObjectCategory> UserObjectCategory { get; set; } = new List<UserObjectCategory>();
}