// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores the different categories of composite that exist in the database. Can be used to distinguish composite sets by module, e.g. Coal Quality. 
/// </summary>
public partial class CF_COMPOSITECATEGORY
{
    /// <summary>
    /// A category facilitates the grouping of composites based on their methods.
    /// </summary>
    public string COMPOSITECATEGORY { get; set; }

    /// <summary>
    /// The verbose description of composite category.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// The name of a composite or fraction domain, ie COALQUALITYV2.
    /// </summary>
    public string DOMAINCODE { get; set; }

    public virtual ICollection<CF_COMPOSITEMETHOD> CF_COMPOSITEMETHOD { get; set; } = new List<CF_COMPOSITEMETHOD>();

    public virtual ICollection<CF_COMPOSITETYPE> CF_COMPOSITETYPE { get; set; } = new List<CF_COMPOSITETYPE>();
}