// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores in the database the methods used to create composites. 
/// </summary>
public partial class CF_COMPOSITEMETHOD
{
    /// <summary>
    /// The method used to derive the composite.
    /// </summary>
    public string COMPOSITEMETHOD { get; set; }

    /// <summary>
    /// The verbose description of composite method.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// Defines the group a composite method belongs to.
    /// </summary>
    public string COMPOSITECATEGORY { get; set; }

    public virtual ICollection<CF_COMPOSITE> CF_COMPOSITE { get; set; } = new List<CF_COMPOSITE>();

    public virtual CF_COMPOSITECATEGORY COMPOSITECATEGORYNavigation { get; set; }
}