// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Identifies the types of composite present in the database. 
/// </summary>
public partial class CF_COMPOSITETYPE
{
    /// <summary>
    /// A unique identifier and brief descriptive type of a composite.
    /// </summary>
    public string COMPOSITETYPE { get; set; }

    /// <summary>
    /// Defines the group a composite type belongs to.
    /// </summary>
    public string COMPOSITECATEGORY { get; set; }

    /// <summary>
    /// The verbose descriptions of a composite type.
    /// </summary>
    public string DESCRIPTION { get; set; }

    public virtual ICollection<CF_COMPOSITE> CF_COMPOSITE { get; set; } = new List<CF_COMPOSITE>();

    public virtual CF_COMPOSITECATEGORY COMPOSITECATEGORYNavigation { get; set; }
}