// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Defines the domain a composite or fraction can belong to. Helps to protects domain specific attributes. 
/// </summary>
public partial class CF_DOMAIN
{
    /// <summary>
    /// The name of a composite and fraction domain, ie COALQUALITYV2.
    /// </summary>
    public string DOMAINCODE { get; set; }

    /// <summary>
    /// The descriptions of a composite and fraction domain.
    /// </summary>
    public string DESCRIPTION { get; set; }
}