// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Reference table defining fraction suites stored in table FRACTIONSUITEDEFINITION. 
/// </summary>
public partial class CF_FRACTIONSUITE
{
    /// <summary>
    /// A unique name and primary key of a fraction suite.
    /// </summary>
    public string FRACTIONSUITE { get; set; }

    /// <summary>
    /// The verbose descriptions of a fraction suite.
    /// </summary>
    public string DESCRIPTION { get; set; }

    public virtual ICollection<CF_FRACTIONSUITEDEFINITION> CF_FRACTIONSUITEDEFINITION { get; set; } = new List<CF_FRACTIONSUITEDEFINITION>();
}