// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Comments regarding a given fraction method. 
/// </summary>
public partial class CF_FRACTIONMETHODCOMMENT
{
    /// <summary>
    /// A unique name and primary key of a fraction method.
    /// </summary>
    public string FRACTIONMETHOD { get; set; }

    /// <summary>
    /// The name of a virtual field, also part of primary key.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The mandatory value of a virtual field.
    /// </summary>
    public string VALUE { get; set; }

    public virtual CF_FRACTIONMETHODCOMMENTCODE NAMENavigation { get; set; }
}