// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Describes the rules how to treat mass proportions. 
/// </summary>
public partial class CF_FIELDRULE
{
    /// <summary>
    /// A unique identifier and brief descriptive rule.
    /// </summary>
    public string RULE { get; set; }

    /// <summary>
    /// Defines the field name affected by the rule.
    /// </summary>
    public string FIELD { get; set; }

    /// <summary>
    /// The name of a composite or fraction domain, ie COALQUALITYV2.
    /// </summary>
    public string DOMAINCODE { get; set; }
}