// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// A dummy table to generate sequential identifiers. 
/// </summary>
public partial class CF_FRACTIONUNITIDENTITY
{
    public short FRACTIONUNITID { get; set; }

    public string DUMMY { get; set; }
}