// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores the virtual field names used in the CF_FRACTIONMETHODDETAILS table. 
/// </summary>
public partial class CF_FRACTIONMETHODCODE
{
    /// <summary>
    /// The unique name of a virtual field.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The verbose descriptions of a virtual field.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// Defines the data type of a virtual field.
    /// </summary>
    public string DATATYPE { get; set; }

    /// <summary>
    /// Defines the units used when a numeric data type is used.
    /// </summary>
    public string UNITS { get; set; }

    public virtual ICollection<CF_FRACTIONMETHODDETAILS> CF_FRACTIONMETHODDETAILS { get; set; } = new List<CF_FRACTIONMETHODDETAILS>();

    public virtual DATATYPE DATATYPENavigation { get; set; }
}