// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Reference table for fraction method comment fields. 
/// </summary>
public partial class CF_FRACTIONMETHODCOMMENTCODE
{
    /// <summary>
    /// The unique name of a virtual field.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The verbose descriptions of a virtual field.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// Defines the data type of a virtual field, can only be Text.
    /// </summary>
    public string DATATYPE { get; set; }

    public virtual ICollection<CF_FRACTIONMETHODCOMMENT> CF_FRACTIONMETHODCOMMENT { get; set; } = new List<CF_FRACTIONMETHODCOMMENT>();

    public virtual DATATYPE DATATYPENavigation { get; set; }
}