// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Only applicable when Fractions are created. See the pages on Composites and Fractions. 
/// </summary>
public partial class CHECKGEOCOMMENT
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual GEOCOMMENTCODE NAMENavigation { get; set; }
}