// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// CheckDespatchComment stores comments on individual samples in a dispatch. The field names are defined in SampleDespatchComCode.Name. 
/// </summary>
public partial class CHECKDESPATCHCOMMENT
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string DESPATCHNO { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual SAMPLEDESPATCHCOMCODE NAMENavigation { get; set; }
}