// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// This table associates CheckID with a DespatchNo. 
/// </summary>
public partial class CHECKDESPATCH
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string DESPATCHNO { get; set; }

    public string LABJOBNO { get; set; }
}