// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// CheckAssay stores the analytical results for the check samples. The combination of CheckID, DuplicateNo and Name must be unique in the database. The Values MUST be numeric. 
/// </summary>
public partial class CHECKASSAY
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string NAME { get; set; }

    public double VALUE { get; set; }
}