// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Comment table associated with CHECKSAMPLE.
/// </summary>
public partial class CHECKCOMMENT
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual SAMPLECOMMENTCODE NAMENavigation { get; set; }
}