// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// CheckDespatchDetails stores particulars of individual samples in a dispatch. The field names are defined in SampleDespatchCode.Name. 
/// </summary>
public partial class CHECKDESPATCHDETAILS
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string DESPATCHNO { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual SAMPLEDESPATCHCODE NAMENavigation { get; set; }
}