// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class CompoundFlags
{
    public int FlagId { get; set; }

    public string FlagName { get; set; }
}