// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Company associates a CompanyCode with a CompanyName. 
/// </summary>
public partial class COMPANY
{
    public string COMPANYCODE { get; set; }

    public string COMPANYNAME { get; set; }

    public string STREET { get; set; }

    public string TOWN { get; set; }

    public string STATE { get; set; }

    public string POSTCODE { get; set; }

    public string COUNTRY { get; set; }

    public string PHONE1 { get; set; }

    public string PHONE2 { get; set; }

    public string FAX1 { get; set; }

    public string FAX2 { get; set; }

    public string EMAIL { get; set; }

    public virtual ICollection<AC_ACTIVITYREPORT> AC_ACTIVITYREPORT { get; set; } = new List<AC_ACTIVITYREPORT>();

    public virtual ICollection<AC_INVOICE> AC_INVOICE { get; set; } = new List<AC_INVOICE>();

    public virtual ICollection<ASSAYLABORATORY> ASSAYLABORATORY { get; set; } = new List<ASSAYLABORATORY>();

    public virtual ICollection<COMPANYCOMMENT> COMPANYCOMMENT { get; set; } = new List<COMPANYCOMMENT>();

    public virtual ICollection<COMPANYDETAILS> COMPANYDETAILS { get; set; } = new List<COMPANYDETAILS>();

    public virtual ICollection<CONTRACT> CONTRACT { get; set; } = new List<CONTRACT>();

    public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; } = new List<EQUIPMENT>();
}