// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// CompanyComment holds values for columns extended by COMPANYCOMMENTCODE. 
/// </summary>
public partial class COMPANYCOMMENT
{
    public string COMPANYCODE { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual COMPANY COMPANYCODENavigation { get; set; }

    public virtual COMPANYCOMMENTCODE NAMENavigation { get; set; }
}