// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class CompoundSelfRelationshipDetails
{
    public int CompoundId { get; set; }

    public string CompoundName { get; set; }

    public string RelationshipDirection { get; set; }

    public string JoinCondition { get; set; }

    public short DataSourceId { get; set; }
}