// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// The type of the entity (Hole, Point) related to the coordinate set.
/// </summary>
public partial class CoordinatesEntityType
{
    /// <summary>
    /// The auto incrementing primary key.
    /// </summary>
    public int CoordinatesEntityTypeId { get; set; }

    /// <summary>
    /// The unique identifier given to the type.
    /// </summary>
    public string Identifier { get; set; }

    public virtual ICollection<Coordinates> Coordinates { get; set; } = new List<Coordinates>();
}