// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// The method used to determine a set of coordinates.
/// </summary>
public partial class CoordinateMethod
{
    /// <summary>
    /// The auto incrementing primary key.
    /// </summary>
    public int CoordinateMethodId { get; set; }

    /// <summary>
    /// The unique name given to the method.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The survey state.
    /// </summary>
    public bool IsSurveyed { get; set; }

    /// <summary>
    /// A number indicating the preference of the survey method.  The lower the number the more preferential giving a higher ranking.
    /// </summary>
    public int? Rank { get; set; }

    /// <summary>
    /// A description of this coordinate method.
    /// </summary>
    public string Description { get; set; }

    public virtual ICollection<Coordinates> Coordinates { get; set; } = new List<Coordinates>();
}