// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Records the current status of an assay sample. 
/// </summary>
public partial class CORPASSAYSTATUS
{
    public string DSC { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<CORPCHECKASSAY> CORPCHECKASSAY { get; set; } = new List<CORPCHECKASSAY>();

    public virtual ICollection<CORPSAMPLEASSAY> CORPSAMPLEASSAY { get; set; } = new List<CORPSAMPLEASSAY>();
}