// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class CORPSAMPLEASSAY_ODR
{
    public string SAMPLEID { get; set; }

    public string NAMEODR { get; set; }

    public int? ANALYSISORDER { get; set; }
}