// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class CORPCHECKASSAY_PEND_LJN
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string NAMELJN { get; set; }

    public string LABJOBNO { get; set; }
}