// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// A code applied to a number of different objects allowing them to be grouped based on cost.
/// </summary>
public partial class COST
{
    public string COSTCODE { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<AC_ACTIVITYREPORTITEM> AC_ACTIVITYREPORTITEM { get; set; } = new List<AC_ACTIVITYREPORTITEM>();

    public virtual ICollection<AC_INVOICE> AC_INVOICE { get; set; } = new List<AC_INVOICE>();

    public virtual ICollection<DESPATCHSEND> DESPATCHSEND { get; set; } = new List<DESPATCHSEND>();

    public virtual ICollection<DRILLINGDETAIL> DRILLINGDETAIL { get; set; } = new List<DRILLINGDETAIL>();
}