// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Code table associated with COSTCOMMENT.
/// </summary>
public partial class COSTCOMMENTCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public virtual ICollection<COSTCOMMENT> COSTCOMMENT { get; set; } = new List<COSTCOMMENT>();

    public virtual DATATYPE DATATYPENavigation { get; set; }
}