// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the xml schema of a custom field attribute type.
/// </summary>
public partial class CustomFieldAttributeType
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int CustomFieldAttributeTypeId { get; set; }

    /// <summary>
    /// The Name of the custom field attribute type.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The Schema of the Custom Field Attribute Type.
    /// </summary>
    public string AttributeXSD { get; set; }

    public virtual ICollection<FieldAttribute> FieldAttribute { get; set; } = new List<FieldAttribute>();
}