// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class DatabaseFiles
{
    public int file_id { get; set; }

    public Guid? file_guid { get; set; }

    public byte type { get; set; }

    public string type_desc { get; set; }

    public int data_space_id { get; set; }

    public string name { get; set; }

    public string physical_name { get; set; }

    public byte? state { get; set; }

    public string state_desc { get; set; }

    public int size { get; set; }

    public int max_size { get; set; }

    public int growth { get; set; }

    public bool is_media_read_only { get; set; }

    public bool is_read_only { get; set; }

    public bool is_sparse { get; set; }

    public bool is_percent_growth { get; set; }

    public bool is_name_reserved { get; set; }

    public decimal? create_lsn { get; set; }

    public decimal? drop_lsn { get; set; }

    public decimal? read_only_lsn { get; set; }

    public decimal? read_write_lsn { get; set; }

    public decimal? differential_base_lsn { get; set; }

    public Guid? differential_base_guid { get; set; }

    public DateTime? differential_base_time { get; set; }

    public decimal? redo_start_lsn { get; set; }

    public Guid? redo_start_fork_guid { get; set; }

    public decimal? redo_target_lsn { get; set; }

    public Guid? redo_target_fork_guid { get; set; }

    public decimal? backup_lsn { get; set; }

    public DateTime? CreationDate { get; set; }
}