// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// The datum employed for coordinates.
/// </summary>
public partial class Datum
{
    /// <summary>
    /// The auto incrementing primary key.
    /// </summary>
    public int DatumId { get; set; }

    /// <summary>
    /// The unique name given to the datum.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// A description of the datum.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// The XML definition of the datum.
    /// </summary>
    public string Definition { get; set; }

    public virtual ICollection<CoordinateSystem> CoordinateSystem { get; set; } = new List<CoordinateSystem>();

    public virtual ICollection<Transform> TransformFromDatum { get; set; } = new List<Transform>();

    public virtual ICollection<Transform> TransformToDatum { get; set; } = new List<Transform>();
}