// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class DD_CollarStatus
{
    public string HoleId { get; set; }

    public string Status { get; set; }
}