// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class DD_Collars
{
    public string HoleId { get; set; }

    public double? East { get; set; }

    public double? North { get; set; }

    public double? RL { get; set; }

    public string StartDate { get; set; }

    public string EndDate { get; set; }

    public string Lease { get; set; }

    public string GDP { get; set; }

    public string DrillType { get; set; }

    public string SurveyMethod { get; set; }

    public string CollarSurveyDate { get; set; }

    public string HoleStatus { get; set; }
}