// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class DD_GeologyValidated
{
    public string HOLEID { get; set; }

    public double GEOLFROM { get; set; }

    public double GEOLTO { get; set; }

    public string DATEINTERPRETED { get; set; }

    public string GEOZONE { get; set; }

    public string INTERPRETEDBY { get; set; }

    public string STRAND { get; set; }
}