// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class DD_Geology
{
    public string HOLEID { get; set; }

    public double GEOLFROM { get; set; }

    public double GEOLTO { get; set; }

    public string _2024GEOLOGCOLOUR { get; set; }

    public string _2024GEOLOGCOLOURSEC { get; set; }

    public string _2024GEOLOGSHAPE { get; set; }

    public string _2024GEOLOGY { get; set; }

    public string _2024GEOLOGYMOISTURE { get; set; }

    public string _2024HARDNESS { get; set; }

    public string _2024PRILITH { get; set; }

    public string _2024RISKFIBRES { get; set; }

    public string _2024RISKMANGANESE { get; set; }

    public string _2024RISKMETAL { get; set; }

    public string _2024RISKOIL { get; set; }

    public string _2024RISKPLASTIC { get; set; }

    public string _2024RISKSULPHIDES { get; set; }

    public string _2024RISKVOIDINTERVAL { get; set; }

    public string _2024RISKVOIDS { get; set; }

    public string _2024SECLITH { get; set; }

    public string _2024TEXTURE { get; set; }

    public double? ALPHA { get; set; }

    public double? B { get; set; }

    public double? CAVITY { get; set; }

    public double? CHIP_DIAM_MM { get; set; }

    public double? CHIP_PCT { get; set; }

    public string COLOUR1 { get; set; }

    public string COLOUR2 { get; set; }

    public double? COREGAIN { get; set; }

    public double? CORELOSS { get; set; }

    public double? CORELOSS_GEOTECH { get; set; }

    public double? CORERECOVERY_M { get; set; }

    public string DATE_COREDENS_MEASRD { get; set; }

    public string DATE_LOGGED { get; set; }

    public string DATE_VALIDATED { get; set; }

    public string DEFECT_ORIGIN { get; set; }

    public string DEFECT_SETS { get; set; }

    public string DEFECT_TYPE { get; set; }

    public double? DRILLLENGTH_M { get; set; }

    public double? DRY_DENSITY_GCC { get; set; }

    public double? DRY_MASS_KG { get; set; }

    public string FILL_MIN1 { get; set; }

    public string FILL_TYPE { get; set; }

    public double? G { get; set; }

    public string GEOLOGICALALTERATION { get; set; }

    public double? GHP_AZIMUTH { get; set; }

    public double? GHP_CALIPER { get; set; }

    public double? GHP_CALIPER_MA { get; set; }

    public double? GHP_DDIFF { get; set; }

    public double? GHP_DENSITY { get; set; }

    public double? GHP_DISTANCE { get; set; }

    public double? GHP_E_DEV { get; set; }

    public double? GHP_GAM_NAT { get; set; }

    public double? GHP_MAG_VECT { get; set; }

    public double? GHP_N_DEV { get; set; }

    public double? GHP_RGAM_NAT { get; set; }

    public double? GHP_SANG { get; set; }

    public double? GHP_SANGB { get; set; }

    public double? GHP_SUSCEP { get; set; }

    public double? GHP_TDEPTH { get; set; }

    public double? GHP_TEMP { get; set; }

    public double? GHP_YFLUX { get; set; }

    public double? GHP_ZFLUX { get; set; }

    public string HAMMEROIL { get; set; }

    public string HARDNESS { get; set; }

    public string HISTORIC_STRAND { get; set; }

    public string HISTORIC_STRAT { get; set; }

    public double? HM_CHIPS { get; set; }

    public string HUE { get; set; }

    public string I_STRAND { get; set; }

    public string INFILL_MIN1 { get; set; }

    public string INFILL_STRENGTH { get; set; }

    public string INFILL_TEXTURE { get; set; }

    public string INTERIM_BY { get; set; }

    public string INTERIM_DATE { get; set; }

    public double? INTERVAL_LEN_GEOTECH { get; set; }

    public double? INTERVAL_LENGTH { get; set; }

    public string LITH_HARDNESS { get; set; }

    public string LITH01 { get; set; }

    public double? LITH01_PCT { get; set; }

    public string LITH02 { get; set; }

    public double? LITH02_PCT { get; set; }

    public string LITH03 { get; set; }

    public double? LITH03_PCT { get; set; }

    public string LITH04 { get; set; }

    public double? LITH04_PCT { get; set; }

    public string LITH05 { get; set; }

    public double? LITH05_PCT { get; set; }

    public string LITH06 { get; set; }

    public double? LITH06_PCT { get; set; }

    public string LITH07 { get; set; }

    public double? LITH07_PCT { get; set; }

    public string LITH08 { get; set; }

    public double? LITH08_PCT { get; set; }

    public string LITH09 { get; set; }

    public double? LITH09_PCT { get; set; }

    public string LITH10 { get; set; }

    public double? LITH10_PCT { get; set; }

    public string LITH11 { get; set; }

    public double? LITH11_PCT { get; set; }

    public string LITH12 { get; set; }

    public double? LITH12_PCT { get; set; }

    public string LITH13 { get; set; }

    public double? LITH13_PCT { get; set; }

    public string LITH14 { get; set; }

    public double? LITH14_PCT { get; set; }

    public string LITH15 { get; set; }

    public double? LITH15_PCT { get; set; }

    public string LOGGED_BY { get; set; }

    public string LOGGED_STRAND { get; set; }

    public string LOGGED_STRAT { get; set; }

    public string MAJOR1 { get; set; }

    public string MAJOR2 { get; set; }

    public string MAJOR3 { get; set; }

    public string MANGANSES_FOUND { get; set; }

    public string MATERIAL_TYPE { get; set; }

    public double? MET_ASB_PCT { get; set; }

    public double? MET_BSH_PCT { get; set; }

    public double? MET_CAR_PCT { get; set; }

    public double? MET_CC2_PCT { get; set; }

    public double? MET_CH_PCT { get; set; }

    public double? MET_CH1_PCT { get; set; }

    public double? MET_CH4_PCT { get; set; }

    public double? MET_CHT_PCT { get; set; }

    public double? MET_CLA_PCT { get; set; }

    public double? MET_DO1_PCT { get; set; }

    public double? MET_DO3_PCT { get; set; }

    public double? MET_DOL_PCT { get; set; }

    public double? MET_DOM_PCT { get; set; }

    public double? MET_DUR_PCT { get; set; }

    public double? MET_FIB_PCT { get; set; }

    public double? MET_FRIABLE_PCT { get; set; }

    public double? MET_GB_PCT { get; set; }

    public double? MET_GH1_PCT { get; set; }

    public double? MET_GH2_PCT { get; set; }

    public double? MET_GH3_PCT { get; set; }

    public double? MET_GO1_PCT { get; set; }

    public double? MET_GO2_PCT { get; set; }

    public double? MET_GO3_PCT { get; set; }

    public double? MET_GOV_PCT { get; set; }

    public double? MET_GS2_PCT { get; set; }

    public double? MET_GS3_PCT { get; set; }

    public double? MET_HARD_PCT { get; set; }

    public double? MET_HG1_PCT { get; set; }

    public double? MET_HG2_PCT { get; set; }

    public double? MET_HG3_PCT { get; set; }

    public double? MET_HG4_PCT { get; set; }

    public double? MET_HO1_PCT { get; set; }

    public double? MET_HO2_PCT { get; set; }

    public double? MET_HO3_PCT { get; set; }

    public double? MET_HO4_PCT { get; set; }

    public double? MET_HP1_PCT { get; set; }

    public double? MET_HP2_PCT { get; set; }

    public double? MET_HP3_PCT { get; set; }

    public double? MET_HP4_PCT { get; set; }

    public double? MET_HPX1_PCT { get; set; }

    public double? MET_HPX2_PCT { get; set; }

    public double? MET_HPX3_PCT { get; set; }

    public double? MET_HS2_PCT { get; set; }

    public double? MET_HS3_PCT { get; set; }

    public double? MET_HX_PCT { get; set; }

    public double? MET_HX1_PCT { get; set; }

    public double? MET_HX2_PCT { get; set; }

    public double? MET_HX3_PCT { get; set; }

    public double? MET_HY1_PCT { get; set; }

    public double? MET_HY2_PCT { get; set; }

    public double? MET_KL3_PCT { get; set; }

    public double? MET_LUMP_PCT { get; set; }

    public double? MET_MAG_PCT { get; set; }

    public double? MET_MEDIUM_PCT { get; set; }

    public double? MET_MH_PCT { get; set; }

    public double? MET_MN_PCT { get; set; }

    public double? MET_MN1_PCT { get; set; }

    public double? MET_MN3_PCT { get; set; }

    public double? MET_MNO_PCT { get; set; }

    public double? MET_NSR_PCT { get; set; }

    public double? MET_OG3_PCT { get; set; }

    public double? MET_OH_PCT { get; set; }

    public double? MET_PI_PCT { get; set; }

    public double? MET_PIG_PCT { get; set; }

    public double? MET_PIS_PCT { get; set; }

    public double? MET_PY_PCT { get; set; }

    public double? MET_PYR_PCT { get; set; }

    public double? MET_QZ_PCT { get; set; }

    public double? MET_QZ1_PCT { get; set; }

    public double? MET_QZ4_PCT { get; set; }

    public double? MET_RO3_PCT { get; set; }

    public double? MET_SC2_PCT { get; set; }

    public double? MET_SH2_PCT { get; set; }

    public double? MET_SH3_PCT { get; set; }

    public double? MET_SHC_PCT { get; set; }

    public double? MET_SHF_PCT { get; set; }

    public double? MET_SIL_PCT { get; set; }

    public double? MET_SL_PCT { get; set; }

    public double? MET_UNK_PCT { get; set; }

    public double? MET_VG2_PCT { get; set; }

    public double? METRES_DRILLED { get; set; }

    public double? MIDPOINT_M { get; set; }

    public string MINOR1 { get; set; }

    public string MINOR2 { get; set; }

    public string MINOR3 { get; set; }

    public string MOD_MATERIAL_INTERP { get; set; }

    public string MODELRELEASE { get; set; }

    public double? MOISTURE_CONTENT { get; set; }

    public double? MWD_BIT_WEIGHT { get; set; }

    public double? MWD_HAMMER_IMPACT { get; set; }

    public double? MWD_HEAD_SPEED { get; set; }

    public double? MWD_HEAD_TORQUE { get; set; }

    public double? MWD_HOLDBACK { get; set; }

    public double? MWD_PEN_RATE { get; set; }

    public double? MWD_PULLDOWN { get; set; }

    public double? MWD_UNIXTIME { get; set; }

    public double? NUM_DEFECTS { get; set; }

    public string ORECODE_GANGUE { get; set; }

    public string ORECODE_HARDNESS { get; set; }

    public string ORECODE_MINERALOGY { get; set; }

    public string ORECODE_STRAT { get; set; }

    public string ORETYPE { get; set; }

    public double? P_PRIORITY { get; set; }

    public double? PCT_RECOVERY { get; set; }

    public string PIOC_ALTERATION { get; set; }

    public string PIOC_HARDNESS { get; set; }

    public string PIOC_MINERALOGY { get; set; }

    public string PIOC_ORE { get; set; }

    public string PLASTIC_FOUND { get; set; }

    public double? POINT_LOAD_KN { get; set; }

    public string PYRITE_FOUND { get; set; }

    public double? R { get; set; }

    public double? RECOVERY_DDH { get; set; }

    public double? RECOVERY_M_GEOTECH { get; set; }

    public double? RECOVERY_PCT_GEOTECH { get; set; }

    public string RECOVERY_RC { get; set; }

    public string REVIEWED_BY { get; set; }

    public string REVIEWED_DATE { get; set; }

    public string ROCK_TYPE { get; set; }

    public double? RQD_M { get; set; }

    public double? RQD_PCT { get; set; }

    public double? SAMPLEASSAYPROCESS { get; set; }

    public string SHAPE1 { get; set; }

    public string SHAPE2 { get; set; }

    public string STRENGTH { get; set; }

    public string STRUCTURE { get; set; }

    public double? STRUCTURE_COUNT { get; set; }

    public string STRUCTURE_ORIGIN { get; set; }

    public string STRUCTURE_ROUGHNESS { get; set; }

    public string STRUCTURE_TYPE { get; set; }

    public string TEXTURE { get; set; }

    public double? TOTAL_PCT { get; set; }

    public string TRACE1 { get; set; }

    public string TRACE2 { get; set; }

    public string TRACE3 { get; set; }

    public double? UNIX_TIME { get; set; }

    public string VALIDATED_BY { get; set; }

    public string VALIDATED_STRAND { get; set; }

    public double? VOLUME_CC { get; set; }

    public string WATER_TABLE { get; set; }

    public string WEATHERING { get; set; }

    public double? WET_DENSITY_GCC { get; set; }

    public string WET_DRY { get; set; }

    public double? WET_MASS_KG { get; set; }

    public double? WIDTH_MM { get; set; }

    public string X_STRAND { get; set; }

    public string ZONE { get; set; }

    public string ZONE_STRUCTURE { get; set; }
}