// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class DD_Geophysics
{
    public string HoleId { get; set; }

    public string EndDate { get; set; }

    public string Plod_inRodDate { get; set; }

    public string Plod_OpenHoleDate { get; set; }

    public string Plod_InRod { get; set; }

    public string Plod_OpenHole { get; set; }

    public string LASMissed { get; set; }

    public string LASCompany { get; set; }

    public string LASRecordDate { get; set; }

    public string LASReceiveDate { get; set; }
}