// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class DD_SampleSamples
{
    public string SampleID { get; set; }

    public string DuplicateNo { get; set; }

    public string HoleID { get; set; }

    public double? SampleStartDepth { get; set; }

    public double? SampleEndDepth { get; set; }

    public string SampleType { get; set; }

    public string STANDARDID { get; set; }

    public string PSAMPLEID { get; set; }

    public string CHECKSTAGE { get; set; }

    public string B_Sample_Requested { get; set; }

    public string Barcode { get; set; }

    public string BVBarcode { get; set; }

    public string CheckHole_ID { get; set; }

    public string Date_Sample_Pickup { get; set; }

    public string Date_Sampled { get; set; }

    public string Geostats_Ref { get; set; }

    public double? PU_Unixtime { get; set; }

    public string QAQC_By { get; set; }

    public string QAQC_Date { get; set; }

    public string RoyHill_Ref { get; set; }

    public string Sample_Assay_NoValue { get; set; }

    public string Sample_Category { get; set; }

    public string Sample_Condition { get; set; }

    public string Sample_Holeid { get; set; }

    public string Sample_Method { get; set; }

    public string Sampled_By { get; set; }

    public string SeleniumAssay_Ignore { get; set; }

    public string SGSBarcode { get; set; }

    public string Unixtime { get; set; }

    public string VialBarcode { get; set; }

    public string VialPosition { get; set; }

    public string VialTray { get; set; }
}