// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class DD_Sampling
{
    public string HoleId { get; set; }

    public double? SampleStartDepth { get; set; }

    public double? SampleEndDepth { get; set; }

    public double? SampleMetres { get; set; }

    public string DateSampled { get; set; }

    public string XRFDespatch { get; set; }

    public string XRFLab { get; set; }

    public string XRFSendDate { get; set; }

    public string XRFReceiveDate { get; set; }

    public string XRFReturnDate { get; set; }

    public string XRFAnalysisMethod { get; set; }

    public string SEDespatch { get; set; }

    public string SELab { get; set; }

    public string SESendDate { get; set; }

    public string SEReceiveDate { get; set; }

    public string SEReturnDate { get; set; }

    public string SEAnalysisMethod { get; set; }
}