// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Defines, for a given styling field group and styling mode, which styling elements are shown by default in the user interface.
/// </summary>
public partial class DefaultStyling
{
    /// <summary>
    /// A link to the styling field group.
    /// </summary>
    public int StylingFieldGroupId { get; set; }

    /// <summary>
    /// A link to the styling category.
    /// </summary>
    public int StylingCategoryId { get; set; }

    /// <summary>
    /// The styling mode (e.g. Grid, StripLog) which the given styling will be shown in by default.
    /// </summary>
    public string StylingMode { get; set; }

    /// <summary>
    /// The styling within the given styling category to show by default.
    /// </summary>
    public int StylingId { get; set; }

    public virtual StylingCategory StylingCategory { get; set; }

    public virtual StylingFieldGroupStyling StylingFieldGroupStyling { get; set; }
}