// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details table associated with DESPATCHRETURN.
/// </summary>
public partial class DESPATCHRETDETAILS
{
    public string LABJOBNO { get; set; }

    public string DESPATCHNO { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual DESPATCHRETCODE NAMENavigation { get; set; }
}