// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// DespatchSend stores particulars about a group of assays forwarded to a laboratory. Assays are usually despatched or submitted to a laboratory with a company generated number or code. This number/code means that the group of samples can be tracked by: This is the main table for Despatch compound forms. 
/// </summary>
public partial class DESPATCHSEND
{
    public string DESPATCHNO { get; set; }

    public string LABCODE { get; set; }

    public string SENDDATE { get; set; }

    public string CONTRACTCODE { get; set; }

    public string COSTCODE { get; set; }

    public string ANALYSISSUITE { get; set; }

    public string COMMENTS { get; set; }

    public string ORIGINALDESPATCHNO { get; set; }

    public virtual ICollection<AC_DESPATCHSENDACTIVITYREPORTITEM> AC_DESPATCHSENDACTIVITYREPORTITEM { get; set; } = new List<AC_DESPATCHSENDACTIVITYREPORTITEM>();

    public virtual ANALYSISSUITE ANALYSISSUITENavigation { get; set; }

    public virtual CONTRACT CONTRACTCODENavigation { get; set; }

    public virtual COST COSTCODENavigation { get; set; }

    public virtual ASSAYLABORATORY LABCODENavigation { get; set; }
}