// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// DespatchRetComCode stores the names of the comment virtual fields for the DespatchReturns compound definition. 
/// </summary>
public partial class DESPATCHRETCOMCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<DESPATCHRETCOMMENT> DESPATCHRETCOMMENT { get; set; } = new List<DESPATCHRETCOMMENT>();
}