// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// This is the defining table for the virtual fields for Despatch compound forms. Virtual fields are created with the Virtual Field Wizard. 
/// </summary>
public partial class DESPATCHCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public string UNITS { get; set; }

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<DESPATCHDETAILS> DESPATCHDETAILS { get; set; } = new List<DESPATCHDETAILS>();
}