// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// The particulars associated with the virtual fields for Despatch compound forms are stored in this table. 
/// </summary>
public partial class DESPATCHDETAILS
{
    public string DESPATCHNO { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual DESPATCHCODE NAMENavigation { get; set; }
}