// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// The degree to which a sample is digested into a solution for analysis.
/// </summary>
public partial class DIGESTDEGREE
{
    public string DIGESTDEGREE1 { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<ASSAYTYPE> ASSAYTYPE { get; set; } = new List<ASSAYTYPE>();
}