// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// DrillholeDiamCode stores the names of the virtual fields for the DrillholeDiameters compound definition. 
/// </summary>
public partial class DRILLHOLEDIAMCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public string UNITS { get; set; }

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<DRILLHOLEDIAMDETAILS> DRILLHOLEDIAMDETAILS { get; set; } = new List<DRILLHOLEDIAMDETAILS>();
}