// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// DrillholeDiamDetails stores data for the DrillholeDiameters virtual fields. It is associated with the DrillholeDiameter table to make up the DrillholeDiameters compound definition. 
/// </summary>
public partial class DRILLHOLEDIAMDETAILS
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double STARTDEPTH { get; set; }

    public string DIAMETERTYPE { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual DRILLHOLEDIAMCODE NAMENavigation { get; set; }
}