// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// DrillholeDiameter stores details of the type or diameter of drilling used at particular depths downhole. This becomes important to differentiate drillholes in a program by drilling type or to record drillholes that have been precollared by a different method or drillholes that have different drill diameters used downhole. Different diameters or methods usually means different associated costs and keeping this record is important. 
/// </summary>
public partial class DRILLHOLEDIAMETER
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double STARTDEPTH { get; set; }

    public string DIAMETERTYPE { get; set; }

    public double? ENDDEPTH { get; set; }

    public string DRILLTYPE { get; set; }

    public virtual DIAMETERTYPE DIAMETERTYPENavigation { get; set; }

    public virtual DRILLTYPE DRILLTYPENavigation { get; set; }
}