// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class ELEMENT
{
    public string ELEMENT1 { get; set; }

    public string DESCRIPTION { get; set; }

    public string UNITSPREF { get; set; }

    public int? DECIMALPREF { get; set; }

    public string ELEMENTTYPE { get; set; }

    public virtual ICollection<ASSAYTYPE> ASSAYTYPE { get; set; } = new List<ASSAYTYPE>();

    public virtual ELEMENTTYPE ELEMENTTYPENavigation { get; set; }

    public virtual UNITS UNITSPREFNavigation { get; set; }
}