// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// BigComment table associated with the EQUIPMENTMODEL table virtual field system. 
/// </summary>
public partial class EQUIPMENTBIGCOMMENT
{
    public string EQUIPMENTCODE { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual EQUIPMENT EQUIPMENTCODENavigation { get; set; }

    public virtual EQUIPMENTBIGCOMMENTCODE NAMENavigation { get; set; }
}