// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// CommentCode table associated with the EQUIPMENTCONFIG table virtual field system. 
/// </summary>
public partial class EQUIPMENTCONFIGCOMMENTCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<EQUIPMENTCONFIGCOMMENT> EQUIPMENTCONFIGCOMMENT { get; set; } = new List<EQUIPMENTCONFIGCOMMENT>();
}