// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Comment table associated with the EQUIPMENTCONFIG table virtual field system. 
/// </summary>
public partial class EQUIPMENTCONFIGCOMMENT
{
    public string EQUIPMENTCODE { get; set; }

    public DateTime EQUIPMENTDATE { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual EQUIPMENTCONFIG EQUIPMENTCONFIG { get; set; }

    public virtual EQUIPMENTCONFIGCOMMENTCODE NAMENavigation { get; set; }
}