// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// BigCommentCode table associated with the EQUIPMENTMODEL table virtual field system. 
/// </summary>
public partial class EQUIPMENTMODELBIGCOMMENTCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<EQUIPMENTMODELBIGCOMMENT> EQUIPMENTMODELBIGCOMMENT { get; set; } = new List<EQUIPMENTMODELBIGCOMMENT>();
}