// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Code table associated with the EQUIPMENTMODEL table virtual field system. Load order: 3 
/// </summary>
public partial class EQUIPMENTMODELCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public string UNITS { get; set; }

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<EQUIPMENTMODELDETAILS> EQUIPMENTMODELDETAILS { get; set; } = new List<EQUIPMENTMODELDETAILS>();
}