// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
///  Stores time-based measurements of equipment configurations and calibrations.
/// </summary>
public partial class EQUIPMENTCONFIG
{
    /// <summary>
    /// The unique identifier for the equipment to be configured or calibrated.
    /// </summary>
    public string EQUIPMENTCODE { get; set; }

    /// <summary>
    /// Time stamp of configuration or calibration.
    /// </summary>
    public DateTime EQUIPMENTDATE { get; set; }

    public virtual EQUIPMENT EQUIPMENTCODENavigation { get; set; }

    public virtual ICollection<EQUIPMENTCONFIGBIGCOMMENT> EQUIPMENTCONFIGBIGCOMMENT { get; set; } = new List<EQUIPMENTCONFIGBIGCOMMENT>();

    public virtual ICollection<EQUIPMENTCONFIGCOMMENT> EQUIPMENTCONFIGCOMMENT { get; set; } = new List<EQUIPMENTCONFIGCOMMENT>();

    public virtual ICollection<EQUIPMENTCONFIGDETAILS> EQUIPMENTCONFIGDETAILS { get; set; } = new List<EQUIPMENTCONFIGDETAILS>();
}