// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Stores details of the specific make and model of equipment available.
/// </summary>
public partial class EQUIPMENTMODEL
{
    /// <summary>
    /// The unique identifier for the specific make and model of the stored equipment.
    /// </summary>
    public string EQUIPMENTMODELCODE { get; set; }

    /// <summary>
    /// The unique identifier for the type of make and model of equipment.
    /// </summary>
    public string EQUIPMENTTYPECODE { get; set; }

    /// <summary>
    /// A description of the make and model of equipment.
    /// </summary>
    public string DESCRIPTION { get; set; }

    public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; } = new List<EQUIPMENT>();

    public virtual ICollection<EQUIPMENTMODELBIGCOMMENT> EQUIPMENTMODELBIGCOMMENT { get; set; } = new List<EQUIPMENTMODELBIGCOMMENT>();

    public virtual ICollection<EQUIPMENTMODELCOMMENT> EQUIPMENTMODELCOMMENT { get; set; } = new List<EQUIPMENTMODELCOMMENT>();

    public virtual ICollection<EQUIPMENTMODELDETAILS> EQUIPMENTMODELDETAILS { get; set; } = new List<EQUIPMENTMODELDETAILS>();

    public virtual EQUIPMENTTYPE EQUIPMENTTYPECODENavigation { get; set; }
}