// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class ErrorMessage
{
    public int ErrorMessageId { get; set; }

    public string MessageFormat { get; set; }

    public int? Severity { get; set; }

    public virtual AdmErrorMessage AdmErrorMessage { get; set; }

    public virtual ICollection<AdmProcessingWarningCache> AdmProcessingWarningCache { get; set; } = new List<AdmProcessingWarningCache>();
}