// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the types of fields supported by the system.
/// </summary>
public partial class FieldType
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int FieldTypeId { get; set; }

    /// <summary>
    /// The Name of the Field Type.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The Datatype that matches this field type.
    /// </summary>
    public string Datatype { get; set; }

    /// <summary>
    /// The data source which the details of this record were primarily obtained from.
    /// </summary>
    public short DataSourceId { get; set; }

    /// <summary>
    /// Flag to indicate if the type is tied to a single field.
    /// </summary>
    public bool IsSingleField { get; set; }

    /// <summary>
    /// Maximum size for text fields.
    /// </summary>
    public int? MaxSize { get; set; }

    /// <summary>
    /// The flag for determining the base fields.
    /// </summary>
    public bool IsBaseFieldType { get; set; }

    public virtual ICollection<AdmDateRangeFieldType> AdmDateRangeFieldTypeBaseFieldType { get; set; } = new List<AdmDateRangeFieldType>();

    public virtual AdmDateRangeFieldType AdmDateRangeFieldTypeFieldType { get; set; }

    public virtual ICollection<AdmValueRangeFieldType> AdmValueRangeFieldTypeBaseFieldType { get; set; } = new List<AdmValueRangeFieldType>();

    public virtual AdmValueRangeFieldType AdmValueRangeFieldTypeFieldType { get; set; }

    public virtual ICollection<CompoundField> CompoundField { get; set; } = new List<CompoundField>();

    public virtual DataSource DataSource { get; set; }

    public virtual ICollection<FieldTypeAcceptableValueText> FieldTypeAcceptableValueText { get; set; } = new List<FieldTypeAcceptableValueText>();

    public virtual ICollection<FieldAttribute> FieldAttribute { get; set; } = new List<FieldAttribute>();
}