// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Contains files that should be available to any acQuire application that uses this database.
/// </summary>
public partial class File
{
    /// <summary>
    /// The auto incrementing GUID primary key.
    /// </summary>
    public Guid FileGlobalId { get; set; }

    /// <summary>
    /// The name of the file.
    /// </summary>
    public string Filename { get; set; }

    /// <summary>
    /// The binary file data.
    /// </summary>
    public byte[] FileBinaryValue { get; set; }

    /// <summary>
    /// The MIME type of the file.
    /// </summary>
    public string FileBinaryType { get; set; }
}