// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// This reference table has a DLO of 0 and cannot be edited. 
/// </summary>
public partial class GDUNITS
{
    public string UNITS { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<GDPROJECTION> GDPROJECTION { get; set; } = new List<GDPROJECTION>();

    public virtual ICollection<GRID> GRID { get; set; } = new List<GRID>();
}