// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// GeoComment allows the user to record information or comments for an interval. The comment (Value) is given a Priority number. Thus for a particular interval there can be many comments, each with a different priority. Priority can be used to subset the data for reports (eg. Priority = 1 reported and not others), it can be used as a key to different comment topics. For example: Priority 1 = Geology comments. Priority 2 = Texture comments and so on. 
/// </summary>
public partial class GEOCOMMENT
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double GEOLFROM { get; set; }

    public double GEOLTO { get; set; }

    public double PRIORITY { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual GEOCOMMENTCODE NAMENavigation { get; set; }
}