// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// The names and values for the virtual fields of the Geology compound forms are stored in this table. 
/// </summary>
public partial class GEODETAILS
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double GEOLFROM { get; set; }

    public double GEOLTO { get; set; }

    public double PRIORITY { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual GEOLOGYCODESECONDARY NAMENavigation { get; set; }
}