// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// This table links an ID for the GEOINTERVAL table to a PRIMARYCODE.
/// </summary>
public partial class GEOINTERVALPRIMARYCODE
{
    public int LOCALID { get; set; }

    public Guid GEOINTERVAL_ID { get; set; }

    public string PRIMARYCODE { get; set; }

    public virtual GEOLOGYCODEPRIMARY PRIMARYCODENavigation { get; set; }
}