// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// GeologyCodePrimary provides the user with the tools to collect geological information about an interval in space (usually referenced as a distance from a starting point, such as with a drillhole collar) in a structured fashion. 
/// </summary>
public partial class GEOLOGYCODEPRIMARY
{
    public string PRIMARYCODE { get; set; }

    public string DESCRIPTION { get; set; }

    public string CONTINUITY { get; set; }

    public virtual GEOCONTINUITY CONTINUITYNavigation { get; set; }

    public virtual ICollection<GEOBIGCOMMENTCODE> GEOBIGCOMMENTCODE { get; set; } = new List<GEOBIGCOMMENTCODE>();

    public virtual ICollection<GEOCOMMENTCODE> GEOCOMMENTCODE { get; set; } = new List<GEOCOMMENTCODE>();

    public virtual ICollection<GEOINTERVALPRIMARYCODE> GEOINTERVALPRIMARYCODE { get; set; } = new List<GEOINTERVALPRIMARYCODE>();

    public virtual ICollection<GEOLOGYCODESECONDARY> GEOLOGYCODESECONDARY { get; set; } = new List<GEOLOGYCODESECONDARY>();
}