// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class GEOPHYSPROPERTY
{
    public short PROPERTYID { get; set; }

    public string PROPERTYTAG { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<GEOPHYSDETAILS> GEOPHYSDETAILS { get; set; } = new List<GEOPHYSDETAILS>();
}