// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class GEOPHYSHEADERBIGCOMMENTCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<GEOPHYSHEADERBIGCOMMENT> GEOPHYSHEADERBIGCOMMENT { get; set; } = new List<GEOPHYSHEADERBIGCOMMENT>();
}