// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class GEOPHYSDETAILS
{
    public int GEOPHYSGID { get; set; }

    public short PROPERTYID { get; set; }

    public decimal DEPTH { get; set; }

    public string NAME { get; set; }

    public double VALUE { get; set; }

    public virtual GEOPHYSHEADER GEOPHYSG { get; set; }

    public virtual GEOPHYSCODE NAMENavigation { get; set; }

    public virtual GEOPHYSPROPERTY PROPERTY { get; set; }
}