// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class GEOPHYSCODECATEGORY
{
    public string CATEGORY { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<GEOPHYSCODE> GEOPHYSCODE { get; set; } = new List<GEOPHYSCODE>();
}