// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class GEOPHYSLOOP
{
    public string LOOP { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<GEOPHYSHEADER> GEOPHYSHEADER { get; set; } = new List<GEOPHYSHEADER>();

    public virtual ICollection<GEOPHYSLOOPCOORD> GEOPHYSLOOPCOORD { get; set; } = new List<GEOPHYSLOOPCOORD>();

    public virtual ICollection<GEOPHYSLOOPDETAILS> GEOPHYSLOOPDETAILS { get; set; } = new List<GEOPHYSLOOPDETAILS>();
}