// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class GEOPHYSLOOPCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public string UNITS { get; set; }

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<GEOPHYSLOOPDETAILS> GEOPHYSLOOPDETAILS { get; set; } = new List<GEOPHYSLOOPDETAILS>();
}