// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// GridDetails.Value stores the data associated with the virtual field GridDetails.Name for the Grid compound definition. 
/// </summary>
public partial class GRIDDETAILS
{
    public string GRIDNAME { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual GRIDCODE NAMENavigation { get; set; }
}