// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Code table in the virtual field system associated with the HoleCoord table. 
/// </summary>
public partial class HOLECOORDCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public string UNITS { get; set; }

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<HOLECOORDDETAILS> HOLECOORDDETAILS { get; set; } = new List<HOLECOORDDETAILS>();
}