// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// HoleDetails stores particulars or Values under the field names or headings defined in HoleCode.Name. The primary key fields are HoleID, ProjectCode and Name. In HoleCode the records in Name become virtual fields and appear as field names on some Compound Forms.  This ability of records in HoleCode to become field names in Compound Forms gives the user scope to customise the database to particular needs - it is in fact, the implementation of the third normal form of database management. 
/// </summary>
public partial class HOLEDETAILS
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual HOLECODE NAMENavigation { get; set; }
}