// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// HoleBigCommentCode stores the names of the virtual fields for HoleBigComment (long comments) that are associated with the Collar compound definition. 
/// </summary>
public partial class HOLEBIGCOMMENTCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<HOLEBIGCOMMENT> HOLEBIGCOMMENT { get; set; } = new List<HOLEBIGCOMMENT>();
}