// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// HoleBigComment Table stores long comments (up to 4000 characters) for a HoleID/ProjectCode combination. It is associated with the HoleLocation table and other details tables to make up the Collar compound definition. 
/// </summary>
public partial class HOLEBIGCOMMENT
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual HOLEBIGCOMMENTCODE NAMENavigation { get; set; }
}