// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Defines local profile values that can be set.
/// </summary>
public partial class LocalProfileValueDefinition
{
    /// <summary>
    /// The auto incrementing primary key.
    /// </summary>
    public Guid LocalProfileValueDefinitionGlobalId { get; set; }

    /// <summary>
    /// Role Id if this profile value is specific to a role.
    /// </summary>
    public Guid? RoleGlobalId { get; set; }

    /// <summary>
    /// The argument definition for the profile value.
    /// </summary>
    public string ProfileValueDefinition { get; set; }

    /// <summary>
    /// The optional expression specifying the default for the profile value.
    /// </summary>
    public string DefaultValue { get; set; }
}