// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the events that have been logged by the system.
/// </summary>
public partial class Log
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public long LogId { get; set; }

    /// <summary>
    /// The Type of Event Logged.
    /// </summary>
    public int LogTypeId { get; set; }

    /// <summary>
    /// The Datetime the event was logged.
    /// </summary>
    public DateTime LogDatetime { get; set; }

    /// <summary>
    /// The Message recorded.
    /// </summary>
    public string Message { get; set; }

    /// <summary>
    /// The Description of the log.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// The Log Details in an xml format.
    /// </summary>
    public string LogDetails { get; set; }

    /// <summary>
    /// The context of the message recorded.
    /// </summary>
    public string Context { get; set; }

    public virtual ICollection<AdmProcessingWarningCache> AdmProcessingWarningCache { get; set; } = new List<AdmProcessingWarningCache>();

    public virtual LogType LogType { get; set; }

    public virtual ICollection<AdmJob> AdmJob { get; set; } = new List<AdmJob>();

    public virtual ICollection<CacheGroup> CacheGroup { get; set; } = new List<CacheGroup>();
}