// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class Logger
{
    public DateTime Date_Stamp { get; set; }

    public string Instance { get; set; }

    public string Database_Name { get; set; }

    public string User { get; set; }

    public long? Rows { get; set; }

    public string Comments { get; set; }
}