// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details manually defined values for compound uniqnenesses.
/// </summary>
public partial class ManualCompoundUniquenessField
{
    /// <summary>
    /// The name of the field within the compound to which the uniqueness belongs.
    /// </summary>
    public string CompoundFieldName { get; set; }

    /// <summary>
    /// The order number of the uniqueness field within the given uniqueness.
    /// </summary>
    public int OrderNumber { get; set; }

    /// <summary>
    /// Whether or not this field in the uniqueness is descending in it&apos;s physical order.
    /// </summary>
    public bool IsDescending { get; set; }

    /// <summary>
    /// The name of the compound to which the uniqueness belongs.
    /// </summary>
    public string CompoundName { get; set; }

    /// <summary>
    /// The internal name of the uniqueness. Required for unique keys as there may be more than 1 per compound. Should correspond to the SQL Server key name if it exists.
    /// </summary>
    public string UniquenessName { get; set; }

    public virtual ManualCompoundUniqueness ManualCompoundUniqueness { get; set; }
}