// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details manually defined derived relationships between compounds.
/// </summary>
public partial class ManualDerivedRelationship
{
    /// <summary>
    /// A name which uniquely identifies this relationship.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The name of the source compound.
    /// </summary>
    public string Compound1Name { get; set; }

    /// <summary>
    /// The name of the target compound.
    /// </summary>
    public string Compound2Name { get; set; }

    /// <summary>
    /// The relationship direction.
    /// </summary>
    public string RelationshipDirection { get; set; }

    /// <summary>
    /// Whether the source of this relationship is a parent of the target.
    /// </summary>
    public bool IsParent { get; set; }

    /// <summary>
    /// Details the expression required to perform the join forwards.
    /// </summary>
    public string JoinExpression { get; set; }

    /// <summary>
    /// Details the expression required to perform the join in reverse.
    /// </summary>
    public string ReverseJoinExpression { get; set; }

    public virtual ICollection<ManualDerivedRelationshipIndirectRelationship> ManualDerivedRelationshipIndirectRelationship { get; set; } = new List<ManualDerivedRelationshipIndirectRelationship>();
}