// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class ManualEqualityRelationshipDetail
{
    public Guid ManualEqualityRelationshipGlobalId { get; set; }

    public string Name { get; set; }

    public string ReverseRelationshipName { get; set; }

    public string Compound1Name { get; set; }

    public string Compound2Name { get; set; }

    public string Label { get; set; }

    public int? Compound1Id { get; set; }

    public int? Compound2Id { get; set; }

    public string RelationshipDirection { get; set; }

    public string ReverseRelationshipDirection { get; set; }

    public string JoinCondition { get; set; }

    public string ReverseJoinCondition { get; set; }

    public bool? IsVisible { get; set; }

    public bool? IsParent { get; set; }

    public bool? IsRequired { get; set; }

    public string RuleBehavior { get; set; }

    public int ReverseIsParent { get; set; }

    public short? DataSourceId { get; set; }

    public int IsValid { get; set; }
}