// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the columns to be part of the primary key for tables or views that have been identified in ManualTableInclusion.
/// </summary>
public partial class ManualTableInclusionKey
{
    /// <summary>
    /// The name of the column that is part of the primary key to be used for this object.
    /// </summary>
    public string ColumnName { get; set; }

    /// <summary>
    /// The Schema of the object.
    /// </summary>
    public string Schema { get; set; }

    /// <summary>
    /// The name of the object.
    /// </summary>
    public string Name { get; set; }

    public virtual ManualTableInclusion ManualTableInclusion { get; set; }
}