// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the relationship chain defining the indirect path for the parent ManualDerivedRelationship defined relationship.
/// </summary>
public partial class ManualDerivedRelationshipIndirectRelationship
{
    /// <summary>
    /// The order number of the indirect relationship within the parent ManualDerivedRelationship relationship. Part of the primary key.
    /// </summary>
    public int OrderNumber { get; set; }

    /// <summary>
    /// The name of the indirect relationship.
    /// </summary>
    public string RelationshipName { get; set; }

    /// <summary>
    /// The name of the parent record in ManualDerivedRelationship. Part of the primary key.
    /// </summary>
    public string Name { get; set; }

    public virtual ManualDerivedRelationship NameNavigation { get; set; }
}