// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details manually defined extended relationships between compounds. These relationship simply extend existing equality relationships.
/// </summary>
public partial class ManualExtendedRelationship
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int ManualExtendedRelationshipId { get; set; }

    /// <summary>
    /// A name which uniquely identifies this extended relationship.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The name of the equality relationship which this relationship is extending.
    /// </summary>
    public string OriginalRelationshipName { get; set; }

    /// <summary>
    /// The default filter condition to apply to the relationship, if required.
    /// </summary>
    public string DefaultFilterCondition { get; set; }

    /// <summary>
    /// The default order condition to apply to the relationship, if required.
    /// </summary>
    public string DefaultOrderingCondition { get; set; }

    /// <summary>
    /// The default filter condition to apply to the reverse relationship, if required.
    /// </summary>
    public string ReverseDefaultFilterCondition { get; set; }

    /// <summary>
    /// The default order condition to apply to the reverse relationship, if required.
    /// </summary>
    public string ReverseDefaultOrderingCondition { get; set; }
}