// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Manual Record of an Object Category.
/// </summary>
public partial class ManualObjectCategory
{
    /// <summary>
    /// The unique identifier primary key.
    /// </summary>
    public Guid ObjectCategoryGlobalId { get; set; }

    /// <summary>
    /// The name of the Object Category.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The default label of the Object Category, which is to be overriden by Localization.
    /// </summary>
    public string Label { get; set; }

    /// <summary>
    /// The type of the Object Category.
    /// </summary>
    public string ObjectCategoryType { get; set; }

    /// <summary>
    /// The Parent Object Category, if there is one.
    /// </summary>
    public Guid? ParentObjectCategoryGlobalId { get; set; }

    public virtual ICollection<ManualObjectCategory> InverseParentObjectCategoryGlobal { get; set; } = new List<ManualObjectCategory>();

    public virtual ICollection<ManualCompoundObjectCategory> ManualCompoundObjectCategory { get; set; } = new List<ManualCompoundObjectCategory>();

    public virtual ManualObjectCategory ParentObjectCategoryGlobal { get; set; }
}