// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details tables which are not the primary base table (e.g. virtual) which should be added to a manually defined compound.
/// </summary>
public partial class ManualCompoundTable
{
    /// <summary>
    /// The schema to which the table belongs.
    /// </summary>
    public string Schema { get; set; }

    /// <summary>
    /// The name of the table.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The context which this table is being used within this compound (e.g. Virtual, Base).
    /// </summary>
    public string TableContext { get; set; }

    /// <summary>
    /// If the table context is Virtual, and the table being referenced does not contain a field to link to AcqMetaSystem.VirtualField.VirtualFieldId, this is the serialized expression defining the link to AcqMetaSystem.VirtualField.Name.
    /// </summary>
    public string VirtualFieldNameExpression { get; set; }

    /// <summary>
    /// The name of the manually defined compound.
    /// </summary>
    public string CompoundName { get; set; }

    public virtual ManualCompound CompoundNameNavigation { get; set; }
}