// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details manually defined equality relationships between compounds.
/// </summary>
public partial class ManualEqualityRelationshipJoin
{
    /// <summary>
    /// The order of the fields to be joined.
    /// </summary>
    public int OrderNumber { get; set; }

    /// <summary>
    /// The compound field from the source of the relationship.
    /// </summary>
    public string CompoundField1Name { get; set; }

    /// <summary>
    /// The compound field from the target of the relationship.
    /// </summary>
    public string CompoundField2Name { get; set; }

    /// <summary>
    /// The link to the manual equality relationship.
    /// </summary>
    public Guid ManualEqualityRelationshipGlobalId { get; set; }

    public virtual ManualEqualityRelationship ManualEqualityRelationshipGlobal { get; set; }
}