// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class ManualCompoundOverride
{
    public string Name { get; set; }

    public bool OverrideIsSecured { get; set; }

    public bool? IsSecured { get; set; }
}