// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class ManualDerivedRelationshipDetail
{
    public string Name { get; set; }

    public string ReverseRelationshipName { get; set; }

    public string ManualDerivedRelationshipName { get; set; }

    public int Compound1Id { get; set; }

    public int Compound2Id { get; set; }

    public string RelationshipDirection { get; set; }

    public bool IsParent { get; set; }

    public string ReverseRelationshipDirection { get; set; }

    public int ReverseIsParent { get; set; }

    public string JoinCondition { get; set; }

    public string ReverseJoinCondition { get; set; }

    public string JoinExpression { get; set; }

    public string ReverseJoinExpression { get; set; }
}