// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METATABLE
{
    public string TABLENAME { get; set; }

    public double? SHOWPRIORITY { get; set; }

    public double? EDITABLEPRIORITY { get; set; }

    public double? TABLETYPE { get; set; }

    public string REFTABLENAME { get; set; }

    public string REFTABLENAMEFIELD { get; set; }

    public string ABBREVIATIONS { get; set; }

    public int? LOADORDER { get; set; }

    public int? CASCADEDELETE { get; set; }
}