// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METACONSTRAINTERRORMESSAGE
{
    public int METACONSTRAINTERRORMESSAGEID { get; set; }

    public string FAILINGCONSTRAINTNAME { get; set; }

    public string DMLACTION { get; set; }

    public string USERMESSAGE { get; set; }
}