// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METASQLEXP
{
    public string DFIELDNAME { get; set; }

    public string DBMS { get; set; }

    public string VERSION { get; set; }

    public int SEQNO { get; set; }

    public string SQLEXP { get; set; }

    public virtual METASQLEXPREF DFIELDNAMENavigation { get; set; }
}