// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METAVIEW
{
    public string SZVIEWNAME { get; set; }

    public string SZVIEWCOMMENT { get; set; }

    public string SZUSER { get; set; }

    public decimal? SZISOWNER { get; set; }

    public string SZTIME { get; set; }
}