// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METAACQ2ACQREF
{
    public string PACKAGEID { get; set; }

    public string CATEGORY { get; set; }

    public string FILTERBYCD { get; set; }

    public int? VISIBLE { get; set; }

    public int? RESETCACHE { get; set; }

    public int? RUNORDER { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<METAACQ2ACQ> METAACQ2ACQ { get; set; } = new List<METAACQ2ACQ>();
}