// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METAFORMDEFINITIONDETAILS
{
    public string NAME { get; set; }

    public string CATEGORY { get; set; }

    public string PARNAME { get; set; }

    public int PARSEQ { get; set; }

    public string PARVALUE { get; set; }

    public virtual METAFORMDEFINITION METAFORMDEFINITION { get; set; }
}