// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METAVIEWTYPE
{
    public string SZVIEWTYPE { get; set; }

    public string SZBASETABLE { get; set; }

    public string SZVIRTUALTABLE { get; set; }

    public string SZVIRTUALTYPEFIELD { get; set; }

    public string SZVIRTUALVALUEFIELD { get; set; }

    public string SZVIRTUALNAMEREFTABLE { get; set; }

    public string SZVIRTUALNAMEREFFIELD { get; set; }

    public string HOLETYPE { get; set; }

    public double? HASWSF { get; set; }

    public double? SIMPLEFILTERTYPE { get; set; }

    public string WSFCDNAME { get; set; }

    public string MAINJOINTABLE { get; set; }

    public int? HASVT { get; set; }

    public double? VIEWPROPERTIES { get; set; }

    public string DESCRIPTION { get; set; }

    public string TEMPLATEID { get; set; }

    public string CATEGORY { get; set; }

    public string LONGDESCRIPTION { get; set; }

    public string MODULENAME { get; set; }

    public virtual METASQLREF TEMPLATE { get; set; }
}