// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METAFIELD
{
    public string TABLENAME { get; set; }

    public string FIELDNAME { get; set; }

    public double? FIELDISPRIMARY { get; set; }

    public string FIELDSTDTYPE { get; set; }

    public double? FIELDLENGTH { get; set; }

    public double? FIELDDECIMALS { get; set; }

    public double? FIELDISFOREIGN { get; set; }

    public double? FIELDISVIRTUALNAME { get; set; }

    public double? FIELDISVIRTUALVALUE { get; set; }

    public double? FIELDISNULL { get; set; }

    public string RELATEDTABLENAME { get; set; }

    public string RELATEDTABLEFIELDNAME { get; set; }

    public double? FIELDISLOOKUP { get; set; }

    public int FIELDISUNIQUE { get; set; }

    public int FIELDISIDENTITY { get; set; }

    public bool FIELDISGLOBALID { get; set; }
}