// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class META3600UPGRADEEXCLUSION
{
    public string OBJECTNAME { get; set; }

    public string SCHEMANAME { get; set; }

    public string EXCLUDEOBJECTNAME { get; set; }

    public virtual META3600UPGRADEOBJECT META3600UPGRADEOBJECT { get; set; }
}