// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METAASSAYRULE
{
    public string NAME { get; set; }

    public string FORMULA { get; set; }

    public string DESCRIPTION { get; set; }
}