// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// MetaAssayExport table is one of the meta tables of acQuire. Meta tables should only be accessed by the acQuire manager on site. This table is used to define a relationship between Assay virtual fields, non-numeric analytical results and values that can be substituted for the non-numeric result when the data is exported, or presented in objects based on read-only compound definitions. The list of virtual fields and their substitute values are also referenced by some stored procedures. The substituted values can be inserted into another field, they can be displayed in derived fields or they can be displayed in current virtual field. In the latter two cases, the results are read-only. 
/// </summary>
public partial class METAASSAYEXPORT
{
    public string ATNAME { get; set; }

    public string SCNAME { get; set; }

    public double ATVALUE { get; set; }

    public string SCVALUE { get; set; }

    public string EXPRULE1 { get; set; }

    public string EXPRULE2 { get; set; }

    public virtual SAMPLECODE SCNAMENavigation { get; set; }
}