// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METAFORMDEFINITIONFILTER
{
    public string NAME { get; set; }

    public string CATEGORY { get; set; }

    public string DBMS { get; set; }

    public string VERSION { get; set; }

    public int SEQNO { get; set; }

    public string WHERESQL { get; set; }

    public string ORDERBYSQL { get; set; }

    public virtual METAFORMDEFINITION METAFORMDEFINITION { get; set; }
}