// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METAFUNCTION
{
    public string FUNCTION { get; set; }

    public string CD_TABLE { get; set; }

    public string FIELD { get; set; }

    public string DBFIELD { get; set; }

    public int? TYPE { get; set; }
}