// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METASQLFUNCPARAM
{
    public string FNAME { get; set; }

    public string PNAME { get; set; }

    public int ORDINAL { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual METASQLFUNC FNAMENavigation { get; set; }

    public virtual ICollection<METASQLFUNCPARAMFIELD> METASQLFUNCPARAMFIELD { get; set; } = new List<METASQLFUNCPARAMFIELD>();
}