// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METACLIENTALIASES
{
    public string CLIENT { get; set; }

    public string COMPOUNDDEF { get; set; }

    public string ACQFIELD { get; set; }

    public string ALIASFIELD { get; set; }
}