// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class META3600UPGRADEOBJECT
{
    public string OBJECTNAME { get; set; }

    public string SCHEMANAME { get; set; }

    public byte UPGRADEFROMLEVEL { get; set; }

    public virtual ICollection<META3600UPGRADEEXCLUSION> META3600UPGRADEEXCLUSION { get; set; } = new List<META3600UPGRADEEXCLUSION>();
}