// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METAFORMDEFINITION
{
    public string NAME { get; set; }

    public string CATEGORY { get; set; }

    public string COMPOUNDTYPE { get; set; }

    public string DESCRIPTION { get; set; }

    public string TABLENAME { get; set; }

    public string SZUSER { get; set; }

    public decimal? SZISOWNER { get; set; }

    public string CACHETABLENAME { get; set; }

    public DateTime? LASTCACHESTARTTIME { get; set; }

    public DateTime? LASTCACHESUCCESSTIME { get; set; }

    public Guid? PROPERTYOBJECT { get; set; }

    public bool MIGRATE { get; set; }

    public Guid GLOBALID { get; set; }

    public virtual ICollection<AUTO_CACHEGROUPFORM> AUTO_CACHEGROUPFORM { get; set; } = new List<AUTO_CACHEGROUPFORM>();

    public virtual ICollection<METAFORMDEFINITIONDETAILS> METAFORMDEFINITIONDETAILS { get; set; } = new List<METAFORMDEFINITIONDETAILS>();

    public virtual ICollection<METAFORMDEFINITIONFILTER> METAFORMDEFINITIONFILTER { get; set; } = new List<METAFORMDEFINITIONFILTER>();
}