// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class METASQLFUNC
{
    public string FNAME { get; set; }

    public string CATEGORY { get; set; }

    public string FTYPE { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<METASQLFUNCPARAM> METASQLFUNCPARAM { get; set; } = new List<METASQLFUNCPARAM>();
}