// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Associates a Neo 2.9 form (dashboard) residing in AcqPresentation.Form with a GIM Suite 4+ property object residing in AcqManagement.PropertyObject.
/// </summary>
public partial class MigratedFormPropertyObject
{
    /// <summary>
    /// The ID of the item in AcqPresentation.Form to associate with a property object.
    /// </summary>
    public int FormId { get; set; }

    /// <summary>
    /// The GUID of the item in AcqManagement.PropertyObject to associate with the old form.
    /// </summary>
    public Guid PropertyObjectGlobalId { get; set; }

    public virtual Form Form { get; set; }
}