// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class MM_DefineSample
{
    public string HOLEID { get; set; }

    public double? Hole_Depth { get; set; }

    public double? FEXRF_From { get; set; }

    public double? FEXRF_To { get; set; }

    public double? SE4AD_From { get; set; }

    public double? SE4AD_To { get; set; }

    public string Region { get; set; }

    public string RegionPit { get; set; }

    public string SubRegionPit { get; set; }
}