// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the different types of modules in the system.
/// </summary>
public partial class ModuleType
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int ModuleTypeId { get; set; }

    /// <summary>
    /// The name of the module type.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// A description of the module type.
    /// </summary>
    public string Description { get; set; }

    public virtual ICollection<Module> Module { get; set; } = new List<Module>();
}