// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Cached record of an object category.
/// </summary>
public partial class ObjectCategory
{
    /// <summary>
    /// The unique identifier primary key.
    /// </summary>
    public Guid ObjectCategoryGlobalId { get; set; }

    /// <summary>
    /// The name of the object category.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The default label of the object category, which is to be overriden by localization.
    /// </summary>
    public string Label { get; set; }

    /// <summary>
    /// The type of the object category.
    /// </summary>
    public string ObjectCategoryType { get; set; }

    /// <summary>
    /// The parent object category, if there is one.
    /// </summary>
    public Guid? ParentObjectCategoryGlobalId { get; set; }

    /// <summary>
    /// The data source which the details of this record were primarily obtained from.
    /// </summary>
    public short DataSourceId { get; set; }

    public virtual AdmCategoryObjectCategory AdmCategoryObjectCategory { get; set; }

    public virtual ICollection<ObjectCategory> InverseParentObjectCategoryGlobal { get; set; } = new List<ObjectCategory>();

    public virtual ObjectCategory ParentObjectCategoryGlobal { get; set; }

    public virtual ICollection<Compound> Compound { get; set; } = new List<Compound>();
}