// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// PointGeoBigComment Table stores long geology comments (up to 4000 characters) for a point sample. It is associated with the Sample table and other details tables to make up the PointSample and SampleGeoAssay compound definitions. 
/// </summary>
public partial class POINTGEOBIGCOMMENT
{
    public string SAMPLEID { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual GEOBIGCOMMENTCODE NAMENavigation { get; set; }
}