// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// The reference table for AssayDetection. The Preparation type is defined in this table. 
/// </summary>
public partial class PREPARATION
{
    public string PREPARATION1 { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<ASSAYDETECTION> ASSAYDETECTION { get; set; } = new List<ASSAYDETECTION>();

    public virtual ICollection<CORPLABPROPERTIES> CORPLABPROPERTIESPREPARATION1Navigation { get; set; } = new List<CORPLABPROPERTIES>();

    public virtual ICollection<CORPLABPROPERTIES> CORPLABPROPERTIESPREPARATION2Navigation { get; set; } = new List<CORPLABPROPERTIES>();
}