// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the Roles a profile is related to.
/// </summary>
public partial class ProfileRole
{
    /// <summary>
    /// The Profile.
    /// </summary>
    public int ProfileId { get; set; }

    /// <summary>
    /// The Role the profile has access to.
    /// </summary>
    public int RoleId { get; set; }

    /// <summary>
    /// Is the Profile Role Combination Active.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Is the Profile Role Combination available to be made active.
    /// </summary>
    public bool IsAvailable { get; set; }

    public virtual Profile Profile { get; set; }

    public virtual Role Role { get; set; }
}