// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the security profiles.
/// </summary>
public partial class Profile
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int ProfileId { get; set; }

    /// <summary>
    /// The Name of the Profile.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The Description of the Profile.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Is the Profile Shared.
    /// </summary>
    public bool Shared { get; set; }

    /// <summary>
    /// The Profile Owner.
    /// </summary>
    public int? OwnerId { get; set; }

    public virtual User Owner { get; set; }

    public virtual ICollection<ProfileRole> ProfileRole { get; set; } = new List<ProfileRole>();

    public virtual ICollection<User> User { get; set; } = new List<User>();
}