// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Project stores company generated ProjectCode(s) that are used to identify particular activities - it could represent a geological or tenement boundary, for example. A project often consists of a number of different prospects. 
/// </summary>
public partial class PROJECT
{
    /// <summary>
    /// The unique identifying code of the project.
    /// </summary>
    public string PROJECTCODE { get; set; }

    /// <summary>
    /// The name of the project.
    /// </summary>
    public string PROJECTNAME { get; set; }

    /// <summary>
    /// A description of the project.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// The unique identifying code of the location of the project.
    /// </summary>
    public string AREACODE { get; set; }

    /// <summary>
    /// Whether or not the project is active.
    /// </summary>
    public byte? ACTIVE { get; set; }

    public virtual AREA AREACODENavigation { get; set; }
}