// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details information about property objects in the system.
/// </summary>
public partial class PropertyObject
{
    /// <summary>
    /// The label for the property object.
    /// </summary>
    public string Label { get; set; }

    /// <summary>
    /// A description of the property object.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Serialized data detailing information about the property object.
    /// </summary>
    public string PropertyObjectData { get; set; }

    /// <summary>
    /// The type of the property object.
    /// </summary>
    public string PropertyObjectType { get; set; }

    /// <summary>
    /// The name of the factory used to create objects.
    /// </summary>
    public string Factory { get; set; }

    /// <summary>
    /// Tags used to categorise the object.
    /// </summary>
    public string Tags { get; set; }

    /// <summary>
    /// The unique identifier primary key.
    /// </summary>
    public Guid PropertyObjectGlobalId { get; set; }

    /// <summary>
    /// Id of the user that last modified this object.
    /// </summary>
    public Guid? UpdateUserGlobalId { get; set; }

    /// <summary>
    /// If this is a type of property object which can have multiple versions, the link to the first version of this property object.
    /// </summary>
    public Guid? OriginalPropertyObjectGlobalId { get; set; }

    /// <summary>
    /// Date and time of the last modification.
    /// </summary>
    public DateTime? UpdateDateTime { get; set; }

    /// <summary>
    /// If this is a type of property object which can have multiple versions, the version number of the property object.
    /// </summary>
    public byte? VersionNumber { get; set; }

    public virtual AdmProjectValidation AdmProjectValidation { get; set; }

    public virtual ICollection<PropertyObjectEntity> PropertyObjectEntity { get; set; } = new List<PropertyObjectEntity>();

    public virtual ICollection<Compound> Compound { get; set; } = new List<Compound>();

    public virtual ICollection<PropertyObject> DependentPropertyObjectGlobal { get; set; } = new List<PropertyObject>();

    public virtual ICollection<PropertyObject> PropertyObjectGlobal { get; set; } = new List<PropertyObject>();

    public virtual ICollection<Schedule> Schedule { get; set; } = new List<Schedule>();
}