// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Table listing prospects that belong to a project.
/// </summary>
public partial class PROSPECT
{
    /// <summary>
    /// The unique identifying code of the prospect.
    /// </summary>
    public string PROSPECT1 { get; set; }

    /// <summary>
    /// The unique identifying code of the project to which the prospect belongs.
    /// </summary>
    public string PROJECTCODE { get; set; }

    /// <summary>
    /// The name of the prospect.
    /// </summary>
    public string PROSPECTNAME { get; set; }

    /// <summary>
    /// A description of the prospect.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// Whether or not the prospect is active.
    /// </summary>
    public byte? ACTIVE { get; set; }
}