// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class Q_GHeader
{
    public int GEOPHYSGID { get; set; }

    public string HOLEID { get; set; }

    public decimal DEPTHSTEP { get; set; }

    public int PRIORITY { get; set; }

    public string LAS_H_Bit_Size { get; set; }

    public string LAS_H_Chargeable { get; set; }

    public DateOnly? LAS_H_Date { get; set; }

    public string LAS_H_Delta_T_Matrix { get; set; }

    public string LAS_H_Density_Matrix { get; set; }

    public string LAS_H_Driller_Depth { get; set; }

    public string LAS_H_Elev_GL { get; set; }

    public string LAS_H_File_Type_Iden { get; set; }

    public string LAS_H_Logging_Unit { get; set; }

    public string LAS_H_M_Chrg { get; set; }

    public string LAS_H_Mag_Dec { get; set; }

    public int? LAS_H_Missed { get; set; }

    public string LAS_H_Neutron_Matrix { get; set; }

    public DateOnly? LAS_H_Receiv_Date { get; set; }

    public string LAS_H_Recorded_By { get; set; }

    public string LAS_H_Serial_Num { get; set; }

    public string LAS_H_Start_Depth { get; set; }

    public string LAS_H_Stop_Depth { get; set; }

    public string LAS_H_Survey_Company { get; set; }

    public DateOnly? LAS_H_Survey_Date { get; set; }

    public string LAS_H_Sys_Version { get; set; }

    public TimeOnly? LAS_H_Time { get; set; }

    public string LAS_H_Tool_SN { get; set; }

    public string LAS_H_Truck_Cal_Num { get; set; }
}