// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class Q_VUL_COLLARS_PLANNED
{
    public string HOLEID { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public double? DEPTH { get; set; }

    public string STATUS { get; set; }

    public string TYPE { get; set; }

    public string LEASE { get; set; }

    public string GDP { get; set; }

    public string REGION { get; set; }

    public string SUBREGION { get; set; }

    public int? DRILLPRIORITY { get; set; }

    public string PATTERN { get; set; }

    public string BUFFER { get; set; }

    public string SUBDRILL { get; set; }

    public double? PITDEPTH { get; set; }

    public double? OREDEPTH { get; set; }

    public double? WATERDEPTH { get; set; }

    public double? STANDARD { get; set; }

    public double? STANDARDDEPTH { get; set; }

    public double? DUPLICATE { get; set; }

    public double? DUPLICATE_DEPTH { get; set; }

    public string DATE_CLEARED { get; set; }

    public string DATE_PEGGED { get; set; }

    public string MACHINE { get; set; }

    public DateTime? MineDate_201508_LOMP { get; set; }

    public DateTime? CALENDAR_DRILL_DATE { get; set; }

    public int? CALENDAR_DRILL_YEAR { get; set; }

    public int? CALENDAR_DRILL_QUARTER { get; set; }

    public int? CALENDAR_DRILL_MONTH { get; set; }

    public string CALENDAR_DRILL_YYYYMM { get; set; }

    public string CALENDAR_DRILL_YYYYQQ { get; set; }

    public int? FINANCIAL_DRILL_YEAR { get; set; }

    public int? FINANCIAL_DRILL_QUARTER { get; set; }

    public int? FINANCIAL_DRILL_MONTH { get; set; }

    public string FINANCIAL_DRILL_YYYYMM { get; set; }

    public string FINANCIAL_DRILL_YYYYQQ { get; set; }
}