// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class Q_VUL_COLLARS
{
    public string HOLEID { get; set; }

    public string SHORTID { get; set; }

    public string TWIN_IDS { get; set; }

    public string TYPE { get; set; }

    public string MSTAT { get; set; }

    public string DSTAT { get; set; }

    public string LEASE { get; set; }

    public string GDP { get; set; }

    public string REGION { get; set; }

    public string SUB_REGION { get; set; }

    public int? BUFFER { get; set; }

    public int? SUBDRILL { get; set; }

    public string PLANNED_AREA { get; set; }

    public string PROGRAM_ID { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public double? PLAN_EAST { get; set; }

    public double? PLAN_NORTH { get; set; }

    public double? PLAN_RL { get; set; }

    public DateTime? MD_2013_LOM { get; set; }

    public DateTime? MD_2015_ACCEL { get; set; }

    public DateTime? MD_30MONTH { get; set; }

    public DateTime? MD_TAILS_2015 { get; set; }

    public DateTime? MD_201508_LOMP { get; set; }

    public DateTime? PD_201508_LOMP { get; set; }

    public string CAL_YEAR { get; set; }

    public string CAL_MONTH { get; set; }

    public string ADJ_YEAR { get; set; }

    public string QTR { get; set; }

    public string QTR_PERIOD { get; set; }

    public string MTH_PERIOD { get; set; }

    public double? PLANNED_DEPTH { get; set; }

    public int? DRILLPRIORITY { get; set; }

    public string MINE_PLAN { get; set; }

    public string PATTERN { get; set; }

    public double? PIT_DEPTH { get; set; }

    public double? ORE_DEPTH { get; set; }

    public double? WATER_DEPTH { get; set; }

    public double? STANDARD_DEPTH { get; set; }

    public double? DUPLICATE_DEPTH { get; set; }

    public double? DEPTH { get; set; }

    public DateTime? STARTDATE { get; set; }

    public DateTime? ENDDATE { get; set; }

    public double? SURV_EAST { get; set; }

    public double? SURV_NORTH { get; set; }

    public double? SURV_RL { get; set; }

    public double? MWD_EAST { get; set; }

    public double? MWD_NORTH { get; set; }

    public double? MWD_RL { get; set; }

    public DateOnly? DD_ACTUAL { get; set; }

    public string COMMENTS_TECH { get; set; }

    public string HOLE_STATUS { get; set; }

    public string SUMP { get; set; }

    public DateTime? VALIDATED_DATE { get; set; }

    public DateTime? DATE_PEGGED { get; set; }

    public DateTime? DATE_CLEARED { get; set; }

    public string DND { get; set; }

    public string PHOTOS { get; set; }

    public string MACHINE { get; set; }

    public string DRILLED_YN { get; set; }

    public string GEOPHYS_YN { get; set; }

    public string LOGGED_YN { get; set; }

    public string LOGGEO_YN { get; set; }

    public string PHOTO_YN { get; set; }

    public string RIGID_YN { get; set; }

    public string SURVEY_YN { get; set; }

    public string GPH_SURVEY_YN { get; set; }

    public string MWD_SURVEY_YN { get; set; }

    public string RTK_SURVEY_YN { get; set; }

    public string VALID_BY { get; set; }

    public string INTERP_BY { get; set; }

    public string PHOTO_PATH { get; set; }

    public string CMNTS_COLLAR { get; set; }

    public int? LASTMODIFIEDUT { get; set; }
}