// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Internal table maintained by acQuire containing full path for CHECKSAMPLE child rows back to their respective parent row. This is not a user updateable table.
/// </summary>
public partial class QT_CHECKSAMPLE_ROOT_PARENT
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string CHECKID_ROOT_PARENT { get; set; }

    public string DUPLICATENO_ROOT_PARENT { get; set; }

    public byte? LEVEL_Q { get; set; }

    public string SAMPLEID { get; set; }
}