// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QT_FME_COORDSYS
{
    public string FMECOORDSYS { get; set; }

    public string PROJECTION { get; set; }

    public string DATUM { get; set; }

    public string FMEDATUM { get; set; }

    public virtual GDDATUM DATUMNavigation { get; set; }

    public virtual GDPROJECTION PROJECTIONNavigation { get; set; }
}