// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_INVOICEMATCHEDPREDICTEDCOST_RO
{
    public string INVOICENUMBER { get; set; }

    public string COMPANYCODE { get; set; }

    public string COSTCODE { get; set; }

    public DateTime? INVOICEISSUEDATE { get; set; }

    public DateTime? INVOICERECEIVEDATE { get; set; }

    public DateTime INVOICEPERIODSTARTDATE { get; set; }

    public DateTime INVOICEPERIODENDDATE { get; set; }

    public decimal INVOICEAMOUNT { get; set; }

    public decimal? INVOICEPAIDAMOUNT { get; set; }

    public DateTime? INVOICEPAIDDATE { get; set; }

    public double? PREDICTEDCOST { get; set; }
}