// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_ACTIVITYREPORTITEM5LEVELS
{
    public string ACTIVITYREPORTCODE { get; set; }

    public string COMPANYCODE { get; set; }

    public int ITEMNUMBER { get; set; }

    public string CONTRACTITEMTYPECODE { get; set; }

    public string COSTCODE { get; set; }

    public DateTime? STARTDATETIME { get; set; }

    public DateTime? ENDDATETIME { get; set; }

    public decimal? ACTIVITYHOURS { get; set; }

    public double? SINGLEACTIVITYREPORTVALUE { get; set; }

    public double? STARTACTIVITYREPORTVALUE { get; set; }

    public double? ENDACTIVITYREPORTVALUE { get; set; }

    public double? SINGLEPARAMLEVEL2 { get; set; }

    public string TEXTPARAMLEVEL2 { get; set; }

    public double? STARTPARAMLEVEL2 { get; set; }

    public double? ENDPARAMLEVEL2 { get; set; }

    public double? SINGLEPARAMLEVEL3 { get; set; }

    public string TEXTPARAMLEVEL3 { get; set; }

    public double? STARTPARAMLEVEL3 { get; set; }

    public double? ENDPARAMLEVEL3 { get; set; }

    public double? SINGLEPARAMLEVEL4 { get; set; }

    public string TEXTPARAMLEVEL4 { get; set; }

    public double? STARTPARAMLEVEL4 { get; set; }

    public double? ENDPARAMLEVEL4 { get; set; }

    public string COMMENT { get; set; }
}