// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_DESPATCHSENDBYACTIVITYREPORTITEM_RO
{
    public string DESPATCHNO { get; set; }

    /// <summary>
    /// The name of the receiving laboratory.
    /// </summary>
    public string LABCODE { get; set; }

    /// <summary>
    /// The date the despatch is sent to the laboratory.
    /// </summary>
    public string SENDDATE { get; set; }

    /// <summary>
    /// The identifier code of the contract.
    /// </summary>
    public string CONTRACTCODE { get; set; }

    /// <summary>
    /// The suite of analytical tests to be conducted.
    /// </summary>
    public string ANALYSISSUITE { get; set; }

    /// <summary>
    /// A comment describing the despatch.
    /// </summary>
    public string COMMENTS { get; set; }

    /// <summary>
    /// A cost code for the item reported.
    /// </summary>
    public string COSTCODE { get; set; }

    /// <summary>
    /// The original despatch number of a child despatch.
    /// </summary>
    public string ORIGINALDESPATCHNO { get; set; }

    /// <summary>
    /// The identifier, within the contractor company, to identify the activity report.
    /// </summary>
    public string ACTIVITYREPORTCODE { get; set; }
}