// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_ACTIVITYREPORTCOST_RO
{
    /// <summary>
    /// The unique identifier of the company that is the contractor associated with this contract. With ACTIVITYREPORTCODE, uniquely identifies the activity report to which the item belongs.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// The unique identifier for this instance of the contract. With REPORTCODE, uniquely identifies the activity report to which the item belongs.
    /// </summary>
    public string CONTRACTCODE { get; set; }

    /// <summary>
    /// The unique identifier, within the contractor company, to identify the activity report. With COMPANYCODE, uniquely identifies the activity report to which the item belongs.
    /// </summary>
    public string ACTIVITYREPORTCODE { get; set; }

    /// <summary>
    /// Uniquely identifies the specific item within the activity report identified by COMPANYCODE and REPORTCODE.
    /// </summary>
    public int ITEMNUMBER { get; set; }

    /// <summary>
    /// The total cost of the report item across all relevant contract items.
    /// </summary>
    public double? TOTALCOSTOFITEM { get; set; }

    /// <summary>
    /// The amount of the quantity from the report item that is covered by the agreed contract. This should agree with TOTALREPORTEDQUANTITY
    /// </summary>
    public double? TOTALCONTRACTEDQUANTITY { get; set; }

    /// <summary>
    /// The total amount of the quantity from the report item. This should agree with TOTALCONTRACTEDQUANTITY.
    /// </summary>
    public double? TOTALREPORTEDQUANTITY { get; set; }

    /// <summary>
    /// The shortfall of report item quantity against the agreed contract. A value other than 0 here indicates that the activity report reported uncontracted work.
    /// </summary>
    public double? UNCONTRACTEDQUANTITY { get; set; }
}