// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_CONTRACT
{
    /// <summary>
    /// A unique code identifying this instance of the Contract.
    /// </summary>
    public string CONTRACTCODE { get; set; }

    /// <summary>
    /// The primary key of the COMPANY table of the Company that is the Contractor associated with this Contract.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// The Contract Category into which the Report&apos;s Contract must fall. This ties all this Report&apos;s Items to this Category of Contract.
    /// </summary>
    public string CONTRACTCATEGORYCODE { get; set; }

    /// <summary>
    /// The date from which this instance of the Contract is effective.
    /// </summary>
    public DateTime CONTRACTSTARTDATE { get; set; }

    /// <summary>
    /// The date up to which this instance of the Contract is effective.
    /// </summary>
    public DateTime? CONTRACTENDDATE { get; set; }

    /// <summary>
    /// The date up to which this instance of the Contract is active.
    /// </summary>
    public DateTime? INACTIVEFROMDATE { get; set; }

    /// <summary>
    /// A description of this Contract.
    /// </summary>
    public string DESCRIPTION { get; set; }
}