// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_CONTRACTCODESBYTOPLEVELCODE_RO
{
    /// <summary>
    /// The unique identifier for the top level of a contract item type that effectively identifies the whole contract item type hierarchy.
    /// </summary>
    public string TOPLEVELCODE { get; set; }

    /// <summary>
    /// The unique identifier for an instance of a contract.
    /// </summary>
    public string CONTRACTCODE { get; set; }
}