// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_CONTRACTDATES_RO
{
    /// <summary>
    /// The unique identifier for this instance of the contract.
    /// </summary>
    public string CONTRACTCODE { get; set; }

    /// <summary>
    /// The unique identifier of the company that is the contractor associated with this contract.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// The contract category into which the report&apos;s contract must fall. This ties all this report&apos;s items to this category of contract.
    /// </summary>
    public string CONTRACTCATEGORYCODE { get; set; }

    /// <summary>
    /// The date from which this instance of the contract is effective.
    /// </summary>
    public DateTime CONTRACTSTARTDATE { get; set; }

    /// <summary>
    /// A calculated end date taking account of the contract end date, the inactive date and the start date of any following contract instance. If there is no contract end date or inactive date, it is the day before the start of the next contiguous Contract, by COMPANYCODE and CONTRACTPURPOSECODE.
    /// </summary>
    public DateTime? EFFECTIVEENDDATE { get; set; }
}