// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_ACTIVITYREPORTCONTRACTMATCHES_RO
{
    /// <summary>
    /// The unique identifier, within the contractor company, to identify the activity report. With COMPANYCODE, uniquely identifies the activity report to which the item belongs.
    /// </summary>
    public string ACTIVITYREPORTCODE { get; set; }

    /// <summary>
    /// The date of the activity report.
    /// </summary>
    public DateTime ACTIVITYREPORTDATE { get; set; }

    /// <summary>
    /// The unique identifier of the company that is the contractor associated with this contract. With ACTIVITYREPORTCODE, uniquely identifies the activity report to which the item belongs.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// The unique identifier for the job to which the contract has been assigned.
    /// </summary>
    public string JOBCODE { get; set; }

    /// <summary>
    /// The unique identifier for the contract category into which the report&apos;s contract must fall. This ties all this report&apos;s items to this category of contract.
    /// </summary>
    public string CONTRACTCATEGORYCODE { get; set; }

    /// <summary>
    /// The unique identifier for this instance of the contract.
    /// </summary>
    public string CONTRACTCODE { get; set; }

    /// <summary>
    /// The date from which this instance of the contract is effective.
    /// </summary>
    public DateTime? CONTRACTSTARTDATE { get; set; }

    /// <summary>
    /// A calculated end date taking account of the contract end date, the inactive date and the start date of any following contract instance. If there is no contract end date or inactive date, it is the day before the start of the next contiguous Contract, by COMPANYCODE and CONTRACTPURPOSECODE.
    /// </summary>
    public DateTime? EFFECTIVEENDDATE { get; set; }
}