// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_ACTIVITYREPORTITEM
{
    /// <summary>
    /// The unique identifier, within the contractor company, to identify the activity report. With COMPANYCODE, uniquely identifies the activity report to which the item belongs.
    /// </summary>
    public string ACTIVITYREPORTCODE { get; set; }

    /// <summary>
    /// The unique identifier of the company that is the contractor associated with this contract. With ACTIVITYREPORTCODE, uniquely identifies the activity report to which the item belongs.
    /// </summary>
    public string COMPANYCODE { get; set; }

    /// <summary>
    /// The unique identifier of the specific item within the activity report that is identified by COMPANYCODE and ACTIVITYREPORTCODE.
    /// </summary>
    public int ITEMNUMBER { get; set; }

    /// <summary>
    /// The unique identifier for the contract item type.
    /// </summary>
    public string CONTRACTITEMTYPECODE { get; set; }

    /// <summary>
    /// A cost code associated with the activity report item.
    /// </summary>
    public string COSTCODE { get; set; }

    /// <summary>
    /// The date and time that an activity started or a cost was incurred. Mutually exclusive with ACTIVITYHOURS.
    /// </summary>
    public DateTime? STARTDATETIME { get; set; }

    /// <summary>
    /// The date and time that an activity ended. Mutually exclusive with ACTIVITYHOURS.
    /// </summary>
    public DateTime? ENDDATETIME { get; set; }

    /// <summary>
    /// The duration of an activity. Mutually exclusive with STARTDATETIME and ENDDATETIME.
    /// </summary>
    public decimal? ACTIVITYHOURS { get; set; }

    /// <summary>
    /// The value associated with the report item when the contract item type is defined for point data rather than range data.
    /// </summary>
    public double? SINGLEACTIVITYREPORTVALUE { get; set; }

    /// <summary>
    /// The start of a range value associated with the report item when the contract item type is defined for range data.
    /// </summary>
    public double? STARTACTIVITYREPORTVALUE { get; set; }

    /// <summary>
    /// The end of a range value associated with the report item when the contract item type is defined for range data.
    /// </summary>
    public double? ENDACTIVITYREPORTVALUE { get; set; }

    /// <summary>
    /// Any comments related to the activity report item.
    /// </summary>
    public string COMMENT { get; set; }
}