// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AUDIT_ACQ_DB_OBJ_VALID_AND_ENABLED
{
    public string OBJECT_NAME { get; set; }

    public string OBJECT_TYPE { get; set; }

    public int VIEW_ORDER { get; set; }
}