// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_AC_CONTRACTITEMTYPE_LEVEL_RO
{
    /// <summary>
    /// The unique identifier for the actual contract item type.
    /// </summary>
    public string CONTRACTITEMTYPECODE { get; set; }

    /// <summary>
    /// Bit flag to identify contract item types that can be charged pro rata.
    /// </summary>
    public byte CANPRORATA { get; set; }

    /// <summary>
    /// The unique identifier for the contract item type that is the parent of this contract item type.
    /// </summary>
    public string PARENTCONTRACTITEMTYPECODE { get; set; }

    /// <summary>
    /// Whether or not the report values applied against a contract item of this type should be a range. The alternative is a just a single point.
    /// </summary>
    public byte ISRANGEDATA { get; set; }

    /// <summary>
    /// The value used for contract item types that are defined for point data rather than range data.
    /// </summary>
    public double? SINGLEVALUE { get; set; }

    /// <summary>
    /// The value used for contract item types that expect text data.
    /// </summary>
    public string TEXTVALUE { get; set; }

    /// <summary>
    /// The start of a range used for contract item types that are defined for range data.
    /// </summary>
    public double? STARTVALUE { get; set; }

    /// <summary>
    /// The end of a range used for contract item types that are defined for range data.
    /// </summary>
    public double? ENDVALUE { get; set; }

    /// <summary>
    /// A description of the contract item type.
    /// </summary>
    public string DESCRIPTION { get; set; }

    /// <summary>
    /// The units associated with the contract item type.
    /// </summary>
    public string UNITS { get; set; }

    /// <summary>
    /// The unique identifying name for the group in which the contract item type is grouped.
    /// </summary>
    public string GROUPNAME { get; set; }

    /// <summary>
    /// The level of the contract item type within its hierarchy.
    /// </summary>
    public int? LEVEL { get; set; }
}