// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_CORP_AT_PR
{
    public string NAMEP { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }
}