// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_CF_MULTIHOLECOMPOSITE
{
    public string COMPOSITEID { get; set; }

    public int? HOLECOUNT { get; set; }
}