// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_CF_FRACTIONASSAYTYPE_LJN_RO
{
    public string NAMELJN { get; set; }

    public string DATATYPE { get; set; }
}