// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_CF_COMPOSITE
{
    public string COMPOSITEID { get; set; }

    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public string COMPOSITETYPE { get; set; }

    public string COMPOSITEMETHOD { get; set; }

    public string PSAMPLEID { get; set; }

    public string PDUPLICATENO { get; set; }

    public string SAMPLETYPE { get; set; }
}