// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_CHECKSAMPLE_ROOT_PARENT_KEYS
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string CHECKID_ROOT_PARENT { get; set; }

    public string DUPLICATENO_ROOT_PARENT { get; set; }

    public int? LEVEL_Q { get; set; }
}