// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_CORP_SAMPLECHECKASSAYCOMBINEDDETAILS_RO
{
    /// <summary>
    /// The unique identifier of the sample or check sample.
    /// </summary>
    public string SAMPLEID { get; set; }

    /// <summary>
    /// For check samples, an incremental number unqiely identifying each duplicate of a check or PRIMARY for non check samples.
    /// </summary>
    public string DUPLICATENO { get; set; }

    /// <summary>
    /// Unique identifier created by the laboratory to identify the batch.
    /// </summary>
    public string LABJOBNO { get; set; }

    /// <summary>
    /// The name of the virtual details field.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The value stored in the virtual details field.
    /// </summary>
    public string VALUE { get; set; }
}