// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_CHECKSAMPLE_LEVEL_Q
{
    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public string SAMPLEID { get; set; }

    public string STANDARDID { get; set; }

    public string PCHECKID { get; set; }

    public string PDUPLICATENO { get; set; }

    public string CHECKSTAGE { get; set; }

    public string FRACTIONID { get; set; }

    public Guid GLOBALID { get; set; }

    public int? LEVEL_Q { get; set; }
}