// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_CORP_SA_PR
{
    public string SAMPLEID { get; set; }

    public string NAMEP { get; set; }

    public int ASSAYPRIORITY { get; set; }
}