// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_DESPATCHSEND_ORIGDESP
{
    public string DESPATCHNO { get; set; }

    public string LABCODE { get; set; }

    public string SENDDATE { get; set; }

    public string CONTRACTCODE { get; set; }

    public string COSTCODE { get; set; }

    public string ANALYSISSUITE { get; set; }

    public string COMMENTS { get; set; }

    public string ORIGINALDESPATCHNO { get; set; }
}