// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_DE_GEOCOMMENT
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double GEOLFROM { get; set; }

    public double GEOLTO { get; set; }

    public double PRIORITY { get; set; }

    public string PRIMARYCODE { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }
}