// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_GEOPHYS_BEST_BASE
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double? DEPTHFROM { get; set; }

    public double? DEPTHTO { get; set; }

    public string NAME { get; set; }

    public double? VALUE { get; set; }
}