// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_GDLOCALDATUMTRANSFORM
{
    public string LOCALDATUMCODE { get; set; }

    public string LOCALDATUMAREA { get; set; }

    public string LOCALDATUMTRANSFORM { get; set; }

    public string DATUM { get; set; }

    public string DX { get; set; }

    public string DY { get; set; }

    public string DZ { get; set; }

    public string RX { get; set; }

    public string RY { get; set; }

    public string RZ { get; set; }

    public string SCALE { get; set; }

    public string DEFINITIONSTRING { get; set; }

    public string DATUMDEFINITIONSTRING { get; set; }
}