// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_METAVIEWTYPE_INFORMATION
{
    public string COMPOUND_DEFINITION_NAME { get; set; }

    public string BASETABLE { get; set; }

    public string HOLETYPE { get; set; }

    public bool? HAS_WORKSPACE_FILTER { get; set; }

    public string WORKSPACE_FILTER { get; set; }

    public string MAINJOINTABLE { get; set; }

    public bool? HAS_VALIDATION { get; set; }

    public string DESCRIPTION { get; set; }

    public string TEMPLATEID { get; set; }

    public string CATEGORY { get; set; }

    public bool? IS_MULTI_TABLE_CD { get; set; }

    public bool? IS_SINGLE_TABLE_CD { get; set; }

    public bool? IS_READONLY { get; set; }

    public bool? DISABLE_COND_PIVOT { get; set; }

    public bool? HIDE_FROM_GUI { get; set; }

    public bool? LITE_ONLY { get; set; }

    public bool? HIDE_NULLS { get; set; }

    public bool? NO_ORPHANS { get; set; }
}