// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_METAVIEWTYPE_VIRTUALNAMETABLE_INFORMATION
{
    public string COMPOUND_DEFINITION_NAME { get; set; }

    public int? LEVEL { get; set; }

    public string VIRTUAL_TABLE { get; set; }

    public string VIRTUAL_TABLE_FIELD { get; set; }

    public string VIRTUAL_REFERENCE_TABLE { get; set; }

    public string VIRTUAL_REFERENCE_TABLE_FIELD { get; set; }
}