// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_METASQLEXP_INFORMATION
{
    public string DERIVED_FIELD_NAME { get; set; }

    public int SEQ_NO { get; set; }

    public string SQL_EXPRESSION { get; set; }
}