// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_METAVIEWTYPE_VIRTUALVALUETABLE_INFORMATION
{
    public string COMPOUND_DEFINITION_NAME { get; set; }

    public int? LEVEL { get; set; }

    public string VIRTUAL_VALUE_TABLE { get; set; }

    public string VIRTUAL_VALUE_FIELD { get; set; }
}