// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_QC_SAMPLECOORD_OR
{
    public string ID_CK { get; set; }

    public string DUPLICATENO_CK { get; set; }

    public string COORDINATESET { get; set; }

    public double? X { get; set; }

    public double? Y { get; set; }

    public double? Z { get; set; }
}