// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_QLOH_HOLETRANSACTION
{
    public long CHANGENUMBER { get; set; }

    public string TABLENAME_QLR { get; set; }

    public string ACTION_QLR { get; set; }

    public string USERID_QLR { get; set; }

    public string OSUSERID_QLR { get; set; }

    public string TERMINAL_QLR { get; set; }

    public string PROGRAM_QLR { get; set; }

    public DateTime? ACTIONDATE_QLR { get; set; }

    public short? SESSID_QLR { get; set; }

    public string ACCESS_QLR { get; set; }

    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }
}