// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_QC_CORP_DESPATCH_BASE_GN_2_OR_CK
{
    public string GENERICNAME { get; set; }

    public string ASSAYNAME_OR { get; set; }

    public string ASSAYNAME_CK { get; set; }

    public double? ASSAYVALUE_OR { get; set; }

    public double? ASSAYVALUE_CK { get; set; }

    public string ID_OR { get; set; }

    public string DUPLICATENO_OR { get; set; }

    public string ID_CK { get; set; }

    public string DUPLICATENO_CK { get; set; }

    public int? ANALYSISORDER_OR { get; set; }

    public int? ANALYSISORDER_CK { get; set; }

    public int ASSAYPRIORITY_OR { get; set; }

    public int ASSAYPRIORITY_CK { get; set; }

    public DateTime ASSAYLOADDATE_OR { get; set; }

    public DateTime ASSAYLOADDATE_CK { get; set; }

    public string CHECKSTAGE_OR { get; set; }

    public string CHECKSTAGE_CK { get; set; }

    public string STANDARDID_PRIMARY { get; set; }

    public string FRACTIONID_PRIMARY { get; set; }

    public string DESPATCHNO_OR { get; set; }

    public string DESPATCHNO_CK { get; set; }

    public string LABCODE_OR { get; set; }

    public string LABCODE_CK { get; set; }

    public string SENDDATE_OR { get; set; }

    public string SENDDATE_CK { get; set; }

    public string CONTRACTCODE_OR { get; set; }

    public string CONTRACTCODE_CK { get; set; }

    public string COSTCODE_OR { get; set; }

    public string COSTCODE_CK { get; set; }

    public string ANALYSISSUITE_OR { get; set; }

    public string ANALYSISSUITE_CK { get; set; }

    public string DESPATCHSENDCOMMENTS_OR { get; set; }

    public string DESPATCHSENDCOMMENTS_CK { get; set; }

    public string ORIGINALDESPATCHNO_OR { get; set; }

    public string ORIGINALDESPATCHNO_CK { get; set; }

    public string LABJOBNO_OR { get; set; }

    public string LABJOBNO_CK { get; set; }

    public double? LOWERDETECTION_OR { get; set; }

    public double? LOWERDETECTION_CK { get; set; }

    public double? UPPERDETECTION_OR { get; set; }

    public double? UPPERDETECTION_CK { get; set; }

    public string RETURNDATE_OR { get; set; }

    public string RETURNDATE_CK { get; set; }

    public string DESPATCHRETCOMMENTS_OR { get; set; }

    public string DESPATCHRETCOMMENTS_CK { get; set; }

    public string ELEMENT { get; set; }

    public string UNITS { get; set; }

    public string GENERICCODE { get; set; }

    public double? ASSAYRANK_OR { get; set; }

    public double? ASSAYRANK_CK { get; set; }

    public string ANALYSISMETHOD_OR { get; set; }

    public string ANALYSISMETHOD_CK { get; set; }

    public string DIGESTTYPE_OR { get; set; }

    public string DIGESTTYPE_CK { get; set; }

    public string DIGESTDEGREE_OR { get; set; }

    public string DIGESTDEGREE_CK { get; set; }

    public double? ANALYTICALWEIGHT_OR { get; set; }

    public double? ANALYTICALWEIGHT_CK { get; set; }

    public string ASSAYTYPECOMMENTS_OR { get; set; }

    public string ASSAYTYPECOMMENTS_CK { get; set; }
}