// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_QC_AS_BS_OR
{
    public string ID_CK { get; set; }

    public string DUPLICATENO_CK { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }
}