// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_QC_ALL_BASE_OR_CK
{
    public string ASSAYNAME { get; set; }

    public double? ASSAYVALUE_OR { get; set; }

    public double? ASSAYVALUE_CK { get; set; }

    public string ID_OR { get; set; }

    public string DUPLICATENO_OR { get; set; }

    public string ID_CK { get; set; }

    public string DUPLICATENO_CK { get; set; }

    public string CHECKSTAGE_OR { get; set; }

    public string CHECKSTAGE_CK { get; set; }

    public string STANDARDID_PRIMARY { get; set; }

    public string FRACTIONID_PRIMARY { get; set; }

    public string DESPATCHNO_OR { get; set; }

    public string DESPATCHNO_CK { get; set; }

    public string LABCODE_OR { get; set; }

    public string LABCODE_CK { get; set; }

    public string SENDDATE_OR { get; set; }

    public string SENDDATE_CK { get; set; }

    public string CONTRACTCODE_OR { get; set; }

    public string CONTRACTCODE_CK { get; set; }

    public string COSTCODE_OR { get; set; }

    public string COSTCODE_CK { get; set; }

    public string ANALYSISSUITE_OR { get; set; }

    public string ANALYSISSUITE_CK { get; set; }

    public string DESPATCHSENDCOMMENTS_OR { get; set; }

    public string DESPATCHSENDCOMMENTS_CK { get; set; }

    public string ORIGINALDESPATCHNO_OR { get; set; }

    public string ORIGINALDESPATCHNO_CK { get; set; }

    public string LABJOBNO_OR { get; set; }

    public string LABJOBNO_CK { get; set; }

    public string RETURNDATE_OR { get; set; }

    public string RETURNDATE_CK { get; set; }

    public string DESPATCHRETCOMMENTS_OR { get; set; }

    public string DESPATCHRETCOMMENTS_CK { get; set; }

    public double? LOWERDETECTION_OR { get; set; }

    public double? LOWERDETECTION_CK { get; set; }

    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public string HOLETYPE { get; set; }

    public string PROSPECT { get; set; }

    public string TENEMENTID { get; set; }

    public string GRIDNAME { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public double? DEPTH { get; set; }

    public string STARTDATE { get; set; }

    public string ENDDATE { get; set; }

    public string SAMPLEID_PRIMARY { get; set; }

    public string SAMPLETYPE { get; set; }

    public double? SAMPFROM { get; set; }

    public double? SAMPTO { get; set; }

    public string POINTPROSPECT { get; set; }

    public string POINTTENEMENTID { get; set; }

    public string POINTGRIDNAME { get; set; }

    public double? POINTEAST { get; set; }

    public double? POINTNORTH { get; set; }

    public double? POINTRL { get; set; }

    public double? SAMPLE_PRIORITY { get; set; }
}