// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_QC_CORP_ALL_BASE_GN_2_STD
{
    public string STANDARDID { get; set; }

    public string GENERICNAME { get; set; }

    public string ASSAYNAME { get; set; }

    public double? ASSAYVALUE { get; set; }

    public double? STANDARDVALUE { get; set; }

    public double? STANDARDDEVIATION { get; set; }

    public double? ACCEPTABLEMIN { get; set; }

    public double? ACCEPTABLEMAX { get; set; }

    public string STANDARDTYPE { get; set; }

    public string CHECKID { get; set; }

    public string DUPLICATENO { get; set; }

    public int? ANALYSISORDER { get; set; }

    public int ASSAYPRIORITY { get; set; }

    public DateTime ASSAYLOADDATE { get; set; }

    public string DESPATCHNO { get; set; }

    public string LABCODE { get; set; }

    public string SENDDATE { get; set; }

    public string CONTRACTCODE { get; set; }

    public string COSTCODE { get; set; }

    public string ANALYSISSUITE { get; set; }

    public string DESPATCHSENDCOMMENTS { get; set; }

    public string ORIGINALDESPATCHNO { get; set; }

    public string LABJOBNO { get; set; }

    public double? LOWERDETECTION { get; set; }

    public double? UPPERDETECTION { get; set; }

    public string RETURNDATE { get; set; }

    public string DESPATCHRETCOMMENTS { get; set; }

    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public string HOLETYPE { get; set; }

    public string PROSPECT { get; set; }

    public string TENEMENTID { get; set; }

    public string GRIDNAME { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public double? DEPTH { get; set; }

    public string STARTDATE { get; set; }

    public string ENDDATE { get; set; }

    public string SAMPLEID { get; set; }

    public string SAMPLETYPE { get; set; }

    public double? SAMPFROM { get; set; }

    public double? SAMPTO { get; set; }

    public string POINTPROSPECT { get; set; }

    public string POINTTENEMENTID { get; set; }

    public string POINTGRIDNAME { get; set; }

    public double? POINTEAST { get; set; }

    public double? POINTNORTH { get; set; }

    public double? POINTRL { get; set; }

    public double? SAMPLE_PRIORITY { get; set; }
}