// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_SAMPLE_CHECK
{
    public string SAMPLEID { get; set; }

    public string DUPLICATENO { get; set; }

    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public string POINTPROSPECT { get; set; }

    public string POINTGRIDNAME { get; set; }

    public string POINTTENEMENTID { get; set; }

    public double? SAMPFROM { get; set; }

    public double? SAMPTO { get; set; }

    public string SAMPLETYPE { get; set; }

    public double? POINTEAST { get; set; }

    public double? POINTNORTH { get; set; }

    public double? POINTRL { get; set; }

    public double? PRIORITY { get; set; }

    public string STANDARDID { get; set; }

    public string PSAMPLEID { get; set; }

    public string PDUPLICATENO { get; set; }

    public string CHECKSTAGE { get; set; }

    public string FRACTIONID { get; set; }

    public Guid GLOBALID { get; set; }
}