// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_SAMPLE_CHECK_ASSAY_TEXT
{
    public string SAMPLEID { get; set; }

    public string DUPLICATENO { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }
}