// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_VS_FIELD_RW
{
    public string FIELDTABLE { get; set; }

    public string FIELDNAME { get; set; }

    public byte FIELDTYPE { get; set; }

    public string FIELDTYPEDESC { get; set; }

    public string PFIELDTABLE { get; set; }

    public string PFIELDNAME { get; set; }

    public string VTREF { get; set; }
}