// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class QV_VS_DSRANGE_RW
{
    public string FIELDTABLE { get; set; }

    public string FIELDNAME { get; set; }

    public string DMIN { get; set; }

    public string DMAX { get; set; }

    public string PATTERN { get; set; }

    public string FONT { get; set; }

    public int? TEXTCOLOR { get; set; }

    public int? BACKCOLOR { get; set; }
}