// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class r201_20191122
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double GEOLFROM { get; set; }

    public double GEOLTO { get; set; }

    public int PRIORITY { get; set; }

    public DateTime? Date_Interpreted { get; set; }

    public string Interpreted_By { get; set; }

    public string Strand { get; set; }

    public string GEOZONE { get; set; }

    public string MODELRELEASE { get; set; }
}