// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Lists the elements (either relationship or field) for which from/to depths in the given range are distinct and non overlapping.
/// </summary>
public partial class RangeGroupingElement
{
    /// <summary>
    /// The primary key of the range which this grouping element belongs to.
    /// </summary>
    public int RangeId { get; set; }

    /// <summary>
    /// The order number of the element within the range.
    /// </summary>
    public int OrderNumber { get; set; }

    /// <summary>
    /// If the element is a field, this is the compound field representing the element.
    /// </summary>
    public int? CompoundFieldId { get; set; }

    /// <summary>
    /// If the element is a relationship, this is the relationship representing the element.
    /// </summary>
    public int? RelationshipId { get; set; }

    public virtual CompoundField CompoundField { get; set; }

    public virtual Range Range { get; set; }

    public virtual Relationship Relationship { get; set; }
}