// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details from/to ranges (e.g. from/to depths) in the system.
/// </summary>
public partial class Range
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int RangeId { get; set; }

    /// <summary>
    /// The distinct name for this range.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The compound field representing the from field for this range.
    /// </summary>
    public int FromFieldId { get; set; }

    /// <summary>
    /// The compound field representing the to field for this range.
    /// </summary>
    public int ToFieldId { get; set; }

    /// <summary>
    /// The main compound which this range attribute is based on.
    /// </summary>
    public int CompoundId { get; set; }

    /// <summary>
    /// Whether this range allows repeated values for the from and to fields for the given range grouping elements.
    /// </summary>
    public bool HasDuplicatedIntervals { get; set; }

    /// <summary>
    /// The data source which the details of this record were primarily obtained from.
    /// </summary>
    public short DataSourceId { get; set; }

    public virtual Compound Compound { get; set; }

    public virtual DataSource DataSource { get; set; }

    public virtual CompoundField FromField { get; set; }

    public virtual ICollection<RangeGroupingElement> RangeGroupingElement { get; set; } = new List<RangeGroupingElement>();

    public virtual CompoundField ToField { get; set; }
}