// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the fields in each compound to be used when joining the two compounds.
/// </summary>
public partial class RelationshipJoin
{
    /// <summary>
    /// The Relationship.
    /// </summary>
    public int RelationshipId { get; set; }

    /// <summary>
    /// The order of the field pairs within a given relationship.
    /// </summary>
    public int OrderNumber { get; set; }

    /// <summary>
    /// The Compound Field from the first compound.
    /// </summary>
    public int CompoundField1Id { get; set; }

    /// <summary>
    /// The Compound Field from the second compound.
    /// </summary>
    public int CompoundField2Id { get; set; }

    public virtual CompoundField CompoundField1 { get; set; }

    public virtual CompoundField CompoundField2 { get; set; }

    public virtual Relationship Relationship { get; set; }
}