// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class RH_PlannedHoles
{
    public string HOLEID { get; set; }

    public double? DEPTH { get; set; }

    public string TENEMENTID { get; set; }

    public string ENDDATE { get; set; }

    public string P_REGION { get; set; }

    public string P_SUBREGION { get; set; }

    public string P_DEPTH { get; set; }

    public string P_DRY { get; set; }

    public string P_DUPDEPTH { get; set; }

    public string P_STDDPTH { get; set; }

    public string P_WET { get; set; }

    public string REGION { get; set; }

    public string REGIONPIT { get; set; }

    public string SUBREGIONPIT { get; set; }

    public double? HOLE_DEPTH { get; set; }

    public double? DUPLICATE_DEPTH { get; set; }

    public double? STANDARD_DEPTH { get; set; }

    public double? WET_METRES { get; set; }

    public string LEASE { get; set; }
}