// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// List of the roles in the system.
/// </summary>
public partial class Role
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int RoleId { get; set; }

    /// <summary>
    /// The Name of the Role.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The Description of the Role.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// The Windows Group associated with this role.
    /// </summary>
    public string WindowsGroup { get; set; }

    /// <summary>
    /// The Ancestor Role, is this role based on another role.
    /// </summary>
    public int? Ancestor { get; set; }

    public virtual ICollection<AccessRights> AccessRights { get; set; } = new List<AccessRights>();

    public virtual Role AncestorNavigation { get; set; }

    public virtual ICollection<Role> InverseAncestorNavigation { get; set; } = new List<Role>();

    public virtual ICollection<ProfileRole> ProfileRole { get; set; } = new List<ProfileRole>();

    public virtual ICollection<User> User { get; set; } = new List<User>();
}