// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// SampleDespatchCode is a reference table defining the virtual fields in the SampleDespatchDetails table. 
/// </summary>
public partial class SAMPLEDESPATCHCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public string UNITS { get; set; }

    public virtual ICollection<CHECKDESPATCHDETAILS> CHECKDESPATCHDETAILS { get; set; } = new List<CHECKDESPATCHDETAILS>();

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<SAMPLEDESPATCHDETAILS> SAMPLEDESPATCHDETAILS { get; set; } = new List<SAMPLEDESPATCHDETAILS>();
}