// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// You can create virtual fields for Assay, CheckAssay, PointSample, Chemistry and CheckChemistry that do not have to be numeric. (Those defined in AssayType MUST be numeric). The Name and associated Value for the particular SampleIDs are stored in this table. 
/// </summary>
public partial class SAMPLEDETAILS
{
    public string SAMPLEID { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual SAMPLECODE NAMENavigation { get; set; }
}