// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// SampleDespatchComCode is a reference table defining the virtual fields in the SampleDespatchComment table. 
/// </summary>
public partial class SAMPLEDESPATCHCOMCODE
{
    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string DATATYPE { get; set; }

    public virtual ICollection<CHECKDESPATCHCOMMENT> CHECKDESPATCHCOMMENT { get; set; } = new List<CHECKDESPATCHCOMMENT>();

    public virtual DATATYPE DATATYPENavigation { get; set; }

    public virtual ICollection<SAMPLEDESPATCHCOMMENT> SAMPLEDESPATCHCOMMENT { get; set; } = new List<SAMPLEDESPATCHCOMMENT>();
}