// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the Securable Entities in the system.
/// </summary>
public partial class SecureEntity
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int SecureEntityId { get; set; }

    /// <summary>
    /// The Table which details the given securable item.
    /// </summary>
    public string SecurableTable { get; set; }

    /// <summary>
    /// The Key for access to the securable table. Including fields and expected values.
    /// </summary>
    public string SecurableKey { get; set; }

    public virtual ICollection<AccessRights> AccessRights { get; set; } = new List<AccessRights>();
}