// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details general system wide settings.
/// </summary>
public partial class Setting
{
    /// <summary>
    /// The context within which the setting is applicable.
    /// </summary>
    public string Context { get; set; }

    /// <summary>
    /// The name of the setting within the given context.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The SQL Server data type of the setting. If ComplexValue is set, this field must have the value of &quot;xml&quot;.
    /// </summary>
    public string Datatype { get; set; }

    /// <summary>
    /// If the setting is a single value, this is the current setting value. This field or ComplexValue must be provided, but not both.
    /// </summary>
    public object SingleValue { get; set; }

    /// <summary>
    /// If the setting is a complex value, this is the current setting value as an XML document. This field or SingleValue must be provided, but not both.
    /// </summary>
    public string ComplexValue { get; set; }

    public virtual SettingProcessingEventType SettingProcessingEventType { get; set; }
}