// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class SiteLabBackLogStatus
{
    public string DESPATCHNO { get; set; }

    public string SAMPLEID { get; set; }

    public double? SAMPFROM { get; set; }

    public double? SAMPTO { get; set; }

    public string HOLEID { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public string ENDDATE { get; set; }

    public string REGION { get; set; }
}