// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Big comment table associated with table STANDARDSDEFINITION.
/// </summary>
public partial class STANDARDSDEFBIGCOMMENT
{
    /// <summary>
    /// The identifying name of a standard.
    /// </summary>
    public string STANDARDID { get; set; }

    /// <summary>
    /// The name of a virtual big comment field.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The long comment of a virtual big comment field.
    /// </summary>
    public string VALUE { get; set; }

    public virtual STANDARDSDEFBIGCOMMENTCODE NAMENavigation { get; set; }

    public virtual STANDARDSDEFINITION STANDARD { get; set; }
}