// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// This table is a reference table for the foreign key field StandardType in the StandardsDefinition table. 
/// </summary>
public partial class STANDARDSTYPE
{
    public string STANDARDTYPE { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<STANDARDSDEFINITION> STANDARDSDEFINITION { get; set; } = new List<STANDARDSDEFINITION>();
}