// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Code table associated with table STANDARDSDEFBIGCOMMENT.
/// </summary>
public partial class STANDARDSDEFBIGCOMMENTCODE
{
    /// <summary>
    /// The name of a virtual big comment field of a construction.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The description of a virtual big comment field of a construction.
    /// </summary>
    public string DESCRIPTION { get; set; }

    public virtual ICollection<STANDARDSDEFBIGCOMMENT> STANDARDSDEFBIGCOMMENT { get; set; } = new List<STANDARDSDEFBIGCOMMENT>();
}