// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details what styling types (e.g. Fill, Curve, Bar) apply to each styling.
/// </summary>
public partial class StylingStylingType
{
    /// <summary>
    /// A link to the related styling.
    /// </summary>
    public int StylingId { get; set; }

    /// <summary>
    /// The styling type related to the styling (e.g. Fill, Curve).
    /// </summary>
    public string StylingType { get; set; }

    public virtual Styling Styling { get; set; }
}