// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Defines, for a given styling field group, which stylings the data can be displayed in.
/// </summary>
public partial class StylingFieldGroupStyling
{
    /// <summary>
    /// A link to the styling field group.
    /// </summary>
    public int StylingFieldGroupId { get; set; }

    /// <summary>
    /// A link to the styling.
    /// </summary>
    public int StylingId { get; set; }

    public virtual ICollection<DefaultStyling> DefaultStyling { get; set; } = new List<DefaultStyling>();

    public virtual Styling Styling { get; set; }

    public virtual ICollection<StylingCondition> StylingCondition { get; set; } = new List<StylingCondition>();

    public virtual StylingFieldGroup StylingFieldGroup { get; set; }
}