// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Lists the styling categories (e.g. Text, Background, Line) in the system.
/// </summary>
public partial class StylingCategory
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int StylingCategoryId { get; set; }

    /// <summary>
    /// The name of the styling category.
    /// </summary>
    public string Name { get; set; }

    public virtual ICollection<DefaultStyling> DefaultStyling { get; set; } = new List<DefaultStyling>();

    public virtual ICollection<Styling> Styling { get; set; } = new List<Styling>();
}