// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// This table associates an AnalysisSuite name with the elements (AssayType.Name) that make up the suite or group. 
/// </summary>
public partial class SUITEDEFINITION
{
    public string ANALYSISSUITE { get; set; }

    public string NAME { get; set; }

    public byte? ANALYSISREQUIRED { get; set; }

    public virtual ANALYSISSUITE ANALYSISSUITENavigation { get; set; }
}