// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Comments and observations about specific downhole surveys are stored in this table. 
/// </summary>
public partial class SURVEYCOMMENT
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public double DEPTH { get; set; }

    public string SURVTYPE { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual SURVEYCOMMENTCODE NAMENavigation { get; set; }
}