// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the category of the table.
/// </summary>
public partial class TableCategory
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int TableCategoryId { get; set; }

    /// <summary>
    /// The Name of the category, (all tables).
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The Parent category if this category is the child of another category.
    /// </summary>
    public int? ParentTableCategoryId { get; set; }

    public virtual ICollection<DatabaseTable> DatabaseTable { get; set; } = new List<DatabaseTable>();

    public virtual ICollection<TableCategory> InverseParentTableCategory { get; set; } = new List<TableCategory>();

    public virtual TableCategory ParentTableCategory { get; set; }
}