// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class TEMP_DESPATCH_FE
{
    public string HOLEID { get; set; }

    public string SAMPLEID { get; set; }

    public string FE_LABJOBNO { get; set; }

    public string FE_DESPATCHNO { get; set; }

    public string FE_LABCODE { get; set; }

    public string FE_SENDDATE { get; set; }

    public string FE_RETURNDATE { get; set; }

    public string FE_LABANALYSISMETHOD { get; set; }
}