// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class TEMP_GEOPHYS
{
    public string HOLEID { get; set; }

    public decimal DEPTH { get; set; }

    public int? PRIORITY { get; set; }

    public decimal? DEPTHSTEP { get; set; }

    public double? AZIMUTH { get; set; }

    public double? CALIPER { get; set; }

    public double? Caliper_cm { get; set; }

    public double? Caliper_Max { get; set; }

    public double? Caliper_Min { get; set; }

    public double? DDIFF { get; set; }

    public double? DENSITY { get; set; }

    public double? Density_gmcc { get; set; }

    public double? Density_Max { get; set; }

    public double? Density_Min { get; set; }

    public double? Dip_Geophys { get; set; }

    public double? DISTANCE { get; set; }

    public double? E_DEV { get; set; }

    public double? GAM_NAT { get; set; }

    public double? IR_Gamma_cps { get; set; }

    public double? LAS_D_Azimuth { get; set; }

    public double? LAS_D_Caliper { get; set; }

    public double? LAS_D_CALIPER_MA { get; set; }

    public double? LAS_D_D_Diff { get; set; }

    public double? LAS_D_Density { get; set; }

    public double? LAS_D_Density_MA { get; set; }

    public double? LAS_D_Distance { get; set; }

    public double? LAS_D_East_Dev { get; set; }

    public double? LAS_D_IR_Gamma { get; set; }

    public double? LAS_D_Mag_Vector { get; set; }

    public double? LAS_D_North_Dev { get; set; }

    public double? LAS_D_OH_Gamma { get; set; }

    public double? LAS_D_OH_Gamma_MA { get; set; }

    public double? LAS_D_S_Angle { get; set; }

    public double? LAS_D_S_Angle_Beta { get; set; }

    public double? LAS_D_Suscept_MA { get; set; }

    public double? LAS_D_Susceptability { get; set; }

    public double? LAS_D_T_Depth { get; set; }

    public double? LAS_D_Temp { get; set; }

    public double? LAS_D_X_Incl { get; set; }

    public double? LAS_D_Y_Flux { get; set; }

    public double? LAS_D_Z_Flux { get; set; }

    public double? LAS_D_ResF { get; set; }

    public double? MAG_Vect { get; set; }

    public double? N_DEV { get; set; }

    public double? OH_Gamma_cps { get; set; }

    public double? Res_16N { get; set; }

    public double? Res_64N { get; set; }

    public double? Resistivity_ohmm { get; set; }

    public double? RGAM_NAT { get; set; }

    public double? ROD_Gamma { get; set; }

    public double? SANG { get; set; }

    public double? SANGB { get; set; }

    public double? SUSCEP { get; set; }

    public double? SUSCEP_SI_E5 { get; set; }

    public double? TDEPTH { get; set; }

    public double? TEMP { get; set; }

    public double? YFLUX { get; set; }

    public double? ZFLUX { get; set; }

    public double? MWD_ElapsedTime { get; set; }

    public double? MWD_HammerImpact { get; set; }

    public double? MWD_HammerImpact_MA { get; set; }

    public double? MWD_HeadSpeed { get; set; }

    public double? MWD_HeadSpeed_MA { get; set; }

    public double? MWD_HeadTorque { get; set; }

    public double? MWD_HeadTorque_MA { get; set; }

    public double? MWD_HoldBack_MA { get; set; }

    public double? MWD_HoldBackPressure { get; set; }

    public double? MWD_PenRate { get; set; }

    public double? MWD_PenRate_MA { get; set; }

    public double? MWD_Pulldown_MA { get; set; }

    public double? MWD_PulldownPressure { get; set; }

    public double? MWD_Rods { get; set; }

    public double? MWD_StringWeight { get; set; }

    public double? MWD_Time { get; set; }

    public double? MWD_WeightOnBit { get; set; }

    public double? MWDunixtime { get; set; }
}