// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// BigComment table associated with Tenement table in the Tenements compound definition. 
/// </summary>
public partial class TENEMENTBIGCOMMENT
{
    /// <summary>
    /// A unique identifying name and part of the primary key of a tenement.
    /// </summary>
    public string TENEMENTID { get; set; }

    /// <summary>
    /// The name of the virtual big comment field, part of primary key.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The value of the big comment virtual field.
    /// </summary>
    public string VALUE { get; set; }

    public virtual TENEMENTBIGCOMMENTCODE NAMENavigation { get; set; }
}