// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Store a comment associated with a tenement in the Tenements compound definition. 
/// </summary>
public partial class TENEMENTCOMMENT
{
    /// <summary>
    /// A unique identifying name and part of the primary key of a tenement.
    /// </summary>
    public string TENEMENTID { get; set; }

    /// <summary>
    /// The name of a virtual field, also part of primary key.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The mandatory value of a virtual field.
    /// </summary>
    public string VALUE { get; set; }

    public virtual TENEMENTCOMMENTCODE NAMENavigation { get; set; }
}