// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Virtual fields defined for the Tenements compound definitions. 
/// </summary>
public partial class TENEMENTBIGCOMMENTCODE
{
    /// <summary>
    /// The unique name of a virtual field.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The description of a virtual field.
    /// </summary>
    public string DESCRIPTION { get; set; }

    public virtual ICollection<TENEMENTBIGCOMMENT> TENEMENTBIGCOMMENT { get; set; } = new List<TENEMENTBIGCOMMENT>();
}