// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// TenementDetails stores the actual information for the records/items listed in TenementCode. For example: TenementID Name ValueE16/123 ExpDate 21-Apr-1998E16/123 Partners Weston Mining NLE18/ 66 ExpDate 01-Jan-2000E18/66 Partners Boyle Mining NL\r\nThis information is assigned to a tenement via TenementID.
/// </summary>
public partial class TENEMENTDETAILS
{
    /// <summary>
    /// A unique identifying name and part of the primary key of a tenement.
    /// </summary>
    public string TENEMENTID { get; set; }

    /// <summary>
    /// The name of a virtual field, also part of primary key.
    /// </summary>
    public string NAME { get; set; }

    /// <summary>
    /// The mandatory value of a virtual field.
    /// </summary>
    public string VALUE { get; set; }

    public virtual TENEMENTCODE NAMENavigation { get; set; }
}