// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class TEST_MERGE
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public string TENEMENTID { get; set; }

    public string GRIDNAME { get; set; }

    public string HOLETYPE { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public double? DEPTH { get; set; }

    public string PROSPECT { get; set; }

    public DateOnly? STARTDATE { get; set; }

    public DateOnly? ENDDATA { get; set; }

    public DateOnly? ACTUAL_DRILL_DATE { get; set; }

    public string ACTUAL_RIGID { get; set; }

    public double? APPROXDEPTHFROM { get; set; }

    public double? APPROXDEPTHTO { get; set; }

    public string ARCHIVED_SURVEY_BY { get; set; }

    public string ARCHIVED_SURVEY_DATE { get; set; }

    public string ARCHIVE_SURVEY_METHD { get; set; }

    public string ARCHIVE_SURVEY_VALID { get; set; }

    public string ASSAYS_VALID { get; set; }

    public string CLEARED { get; set; }

    public string CLEARING_STATUS { get; set; }

    public string CMNTS_COLLAR { get; set; }

    public string CMNTS_DRILLEQUIPREC { get; set; }

    public string CMNTS_DUPSELECTED { get; set; }

    public string CMNTS_HOLECOLLARED { get; set; }

    public string CMNTS_HOLEPLUGGED { get; set; }

    public string CMNTS_MEASURERECORD { get; set; }

    public string CMNTS_PEGLABELLED { get; set; }

    public string CMNTS_PLANDEPTHREACH { get; set; }

    public string CMNTS_PLANNEDCOLLAR { get; set; }

    public string CMNTS_PLUGLABELLED { get; set; }

    public string CMNTS_REHAB { get; set; }

    public string CMNTS_SAMPSIZEINSPEC { get; set; }

    public string CMNTS_STANDARDINSERT { get; set; }

    public string CMNTS_STANDARDSPIKED { get; set; }

    public string CMNTS_SURVEYPICKUP { get; set; }

    public string CMNTS_TECHNICIAN { get; set; }

    public string CMNTS_WATER { get; set; }

    public string CMNTS_WATER_READING { get; set; }

    public string CMNTS_WATER_TABLE { get; set; }

    public string COLLAR_CUT { get; set; }

    public string COLLAR_VALID { get; set; }

    public string COMPUTER_NAME { get; set; }

    public double? CONTRACTED_YEAR { get; set; }

    public string DATA_SRCE_COLL { get; set; }

    public string DATA_SRCE_DHSURV { get; set; }

    public string DATA_SRCE_METADATA { get; set; }

    public string DATA_SRCE_REHAB { get; set; }

    public string DATA_SRCE_WATER { get; set; }

    public string DATA_SRCE_WTR_COND { get; set; }

    public string DATA_SRCE_WTR_READNG { get; set; }

    public DateOnly? DATE_BAG_SLASHED { get; set; }

    public DateOnly? DATE_CLEARED { get; set; }

    public DateOnly? DATE_PARTIAL_REHAB { get; set; }

    public DateOnly? DATE_PART_CLEARED { get; set; }

    public DateOnly? DATE_PEGGED { get; set; }

    public DateOnly? DATE_PHOTOGRAPHED { get; set; }

    public DateOnly? DATE_PLAN_IMPORTED { get; set; }

    public DateOnly? DATE_SAMPLE_STORED { get; set; }

    public string DATE_SCARIFIED { get; set; }

    public string DATE_WATER_MEAS { get; set; }

    public string DESTROYED { get; set; }

    public string DH_GEOPHYS_COMPANY { get; set; }

    public DateOnly? DH_GEOPHYS_DATE { get; set; }

    public string DIPPING_STATUS { get; set; }

    public string DND { get; set; }

    public string DRILLED_PEG_ID { get; set; }

    public string DRILLEQUIPRECOVERED { get; set; }

    public string DRILLHOLETYPE { get; set; }

    public string DRILLPATTERN { get; set; }

    public double? DRILLPRIORITY { get; set; }

    public string DRUM_DESTROYED { get; set; }

    public string DRUM_ID { get; set; }

    public string DUPLICATESELECTED { get; set; }

    public string EXEMPTREHAB { get; set; }

    public string GDA { get; set; }

    public string GDP { get; set; }

    public string GEOL_INTERP_VALID { get; set; }

    public string GPSCUT_BY { get; set; }

    public DateOnly? GPSCUT_DATE { get; set; }

    public string GPS_HOLEID { get; set; }

    public double? GPS_ZONE { get; set; }

    public string HISTORIC_HOLE_ID { get; set; }

    public string HOLECOLLARED { get; set; }

    public string HOLEPLUGGED { get; set; }

    public string HOLE_CLEARED_BY { get; set; }

    public string HOLE_EXPORTED { get; set; }

    public string HOLE_PEGGED_BY { get; set; }

    public string HOLE_PURPOSE { get; set; }

    public string HOLE_STATUS { get; set; }

    public string HOLE_VALIDATED_BY { get; set; }

    public string LANDFILL_ANALYSIS { get; set; }

    public DateOnly? LAST_MODIFIED { get; set; }

    public string LITH_VALID { get; set; }

    public string LOGGING_COMPLETE { get; set; }

    public string LOGGING_GEO { get; set; }

    public DateOnly? LOGGING_GEO_DATE { get; set; }

    public string MACHINE { get; set; }

    public string MEASUREDRILLRECORDED { get; set; }

    public string METALS_ANALYSIS { get; set; }

    public DateOnly? MINEDATE_2013_LOM { get; set; }

    public DateOnly? MINEDATE_201508_LOMP { get; set; }

    public DateOnly? MINEDATE_2015_ACCEL { get; set; }

    public DateOnly? MINEDATE_30MONTH { get; set; }

    public DateOnly? MINEDATE_TAILS_2015 { get; set; }

    public double? MINE_MONTH { get; set; }

    public string MINE_PLAN { get; set; }

    public double? MINE_YEAR { get; set; }

    public string MODEL_STATUS { get; set; }

    public string MOISTURETEST { get; set; }

    public string OIL_SPILLS { get; set; }

    public string ORIGINAL_TENEMENTID { get; set; }

    public string PAD_REHAB { get; set; }

    public string PARENT_HOLE_ID { get; set; }

    public string PEGGED { get; set; }

    public string PEGLABELLED { get; set; }

    public string PEG_ID { get; set; }

    public string PEG_MARKED { get; set; }

    public string PHOTOGRAPHED { get; set; }

    public string PLANDEPTHREACHED { get; set; }

    public string PLANNED_AREA { get; set; }

    public DateOnly? PLANNED_DATE { get; set; }

    public double? PLANNED_DEPTH { get; set; }

    public DateOnly? PLANNED_DRILLEDBYDAT { get; set; }

    public double? PLANNED_DRYMETRES { get; set; }

    public double? PLANNED_DUPDEPTH { get; set; }

    public double? PLANNED_DUPLICATE { get; set; }

    public double? PLANNED_LEADTIME { get; set; }

    public DateOnly? PLANNED_MINEDATE { get; set; }

    public double? PLANNED_NNCOUNTC { get; set; }

    public double? PLANNED_NNCOUNTU { get; set; }

    public double? PLANNED_NNSTDEVC { get; set; }

    public double? PLANNED_NNSTDEVU { get; set; }

    public double? PLANNED_OREDEPTH { get; set; }

    public double? PLANNED_PITDEPTH { get; set; }

    public double? PLANNED_PRIORITY { get; set; }

    public double? PLANNED_ROCKDEPTH { get; set; }

    public double? PLANNED_STANDARD { get; set; }

    public double? PLANNED_STANDARDDPTH { get; set; }

    public double? PLANNED_WATERDEPTH { get; set; }

    public double? PLANNED_WETMETRES { get; set; }

    public double? PLAN_DRILL_PRIORITY { get; set; }

    public DateOnly? PLN_DDTE_201508_LOMP { get; set; }

    public string PLN_YEAR_201508_LOMP { get; set; }

    public string PLN_YRMN_201508_LOMP { get; set; }

    public string PLN_YRQT_201508_LOMP { get; set; }

    public string PLUGLABELLED { get; set; }

    public string POW { get; set; }

    public string PRECOLLARTYPE { get; set; }

    public double? PRECOLLAR_DEPTH { get; set; }

    public string PROGRAM_ID { get; set; }

    public string PROPOSED_BY { get; set; }

    public string REGION { get; set; }

    public string REHABBED_BY { get; set; }

    public string REJ_DEF_REASON { get; set; }

    public string RELIABILITY { get; set; }

    public string RESPONSIBLE_PERSON { get; set; }

    public string RISK_NOTES { get; set; }

    public string RUBBISH { get; set; }

    public string SAMPLE_STORED_BY { get; set; }

    public string SAMPSIZEINSPECTED { get; set; }

    public double? SECTION { get; set; }

    public string SELENIUM { get; set; }

    public string STANDARDINSERTED { get; set; }

    public string STANDARDSPIKED { get; set; }

    public string SUBREGION { get; set; }

    public string SUMP { get; set; }

    public string SURVEYVALIDATED_DATE { get; set; }

    public string SURVEY_BY { get; set; }

    public string SURVEY_DATE { get; set; }

    public string SURVEY_METHOD { get; set; }

    public string SURVEY_VALIDBY { get; set; }

    public string TAILTYPE { get; set; }

    public string TESTING_REQUIRED { get; set; }

    public string TWIN1_HOLE_ID { get; set; }

    public string TWIN2_HOLE_ID { get; set; }

    public DateOnly? VALIDATED_DATE { get; set; }

    public string WATER_AREA { get; set; }

    public string WATER_LEVELS { get; set; }

    public string WATER_MEASURED_BY { get; set; }

    public double? WATER_TABLE_RAW { get; set; }

    public string WATER_TABLE_RELIABLE { get; set; }

    public string WATER_TABLE_VALID { get; set; }

    public string WATER_VALID_NOTES { get; set; }

    public string WHO_MODIFIED { get; set; }
}