// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Localization resources for entities.
/// </summary>
public partial class TextResource
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int TextResourceId { get; set; }

    /// <summary>
    /// The Type of Entity owning the value.
    /// </summary>
    public string EntityType { get; set; }

    /// <summary>
    /// The surrogate key id of the entity owning the value.
    /// </summary>
    public int EntityId { get; set; }

    /// <summary>
    /// The Field within the entity that the value represents.
    /// </summary>
    public string EntityField { get; set; }

    /// <summary>
    /// ISO 639-1 two letter language code.
    /// </summary>
    public string Language { get; set; }

    /// <summary>
    /// ISO 3166 two letter country code.
    /// </summary>
    public string Country { get; set; }

    /// <summary>
    /// The localized text.
    /// </summary>
    public string Value { get; set; }
}