// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// A transform employed for coordinates.
/// </summary>
public partial class Transform
{
    /// <summary>
    /// The auto incrementing primary key.
    /// </summary>
    public int TransformId { get; set; }

    /// <summary>
    /// The unique name given to the transform.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// A description of the transform.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// The XML definition of the transform.
    /// </summary>
    public string Definition { get; set; }

    /// <summary>
    /// Id of datum this transforms from.
    /// </summary>
    public int FromDatumId { get; set; }

    /// <summary>
    /// Id of datum this transforms to.
    /// </summary>
    public int ToDatumId { get; set; }

    public virtual Datum FromDatum { get; set; }

    public virtual ICollection<GridSystem> GridSystem { get; set; } = new List<GridSystem>();

    public virtual Datum ToDatum { get; set; }
}