// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details the units the meta system is aware of.
/// </summary>
public partial class Unit
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int UnitId { get; set; }

    /// <summary>
    /// Standard abbreviation of the unit.
    /// </summary>
    public string Abbreviation { get; set; }

    /// <summary>
    /// Full name of the unit.
    /// </summary>
    public string FullName { get; set; }

    /// <summary>
    /// Description of the unit&apos;s purpose.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Symbol used for the unit.
    /// </summary>
    public string Symbol { get; set; }

    /// <summary>
    /// The unit type, e.g. Mass, Volume, etc.
    /// </summary>
    public string UnitType { get; set; }

    /// <summary>
    /// Is this unit in the metric system.
    /// </summary>
    public bool? IsMetric { get; set; }

    /// <summary>
    /// Is this a built-in unit that cannot be deleted.
    /// </summary>
    public bool IsInternal { get; set; }

    public virtual ICollection<FieldAttribute> FieldAttribute { get; set; } = new List<FieldAttribute>();

    public virtual ICollection<UnitConversion> UnitConversionSource { get; set; } = new List<UnitConversion>();

    public virtual ICollection<UnitConversion> UnitConversionTarget { get; set; } = new List<UnitConversion>();
}