// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// A reference table. Define the units that may be associated with data in other areas in the database. 
/// </summary>
public partial class UNITS
{
    public string UNITS1 { get; set; }

    public string DESCRIPTION { get; set; }

    public string UNITSTYPE { get; set; }

    public virtual ICollection<AC_CONTRACTITEMTYPE> AC_CONTRACTITEMTYPE { get; set; } = new List<AC_CONTRACTITEMTYPE>();

    public virtual ICollection<ASSAYTYPE> ASSAYTYPE { get; set; } = new List<ASSAYTYPE>();

    public virtual ICollection<CF_FRACTIONUNIT> CF_FRACTIONUNIT { get; set; } = new List<CF_FRACTIONUNIT>();

    public virtual ICollection<COMPANYCODE> COMPANYCODE { get; set; } = new List<COMPANYCODE>();

    public virtual ICollection<CORPLABPROPERTIES> CORPLABPROPERTIES { get; set; } = new List<CORPLABPROPERTIES>();

    public virtual ICollection<DIAMETERTYPE> DIAMETERTYPE { get; set; } = new List<DIAMETERTYPE>();

    public virtual ICollection<ELEMENT> ELEMENT { get; set; } = new List<ELEMENT>();

    public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; } = new List<EQUIPMENT>();

    public virtual ICollection<GEOPHYSCODE> GEOPHYSCODE { get; set; } = new List<GEOPHYSCODE>();

    public virtual ICollection<GEOPHYSHEADERDETAILSCODE> GEOPHYSHEADERDETAILSCODE { get; set; } = new List<GEOPHYSHEADERDETAILSCODE>();

    public virtual ICollection<UNITCONVERSION1> UNITCONVERSION1UNITSFROMNavigation { get; set; } = new List<UNITCONVERSION1>();

    public virtual ICollection<UNITCONVERSION1> UNITCONVERSION1UNITSTONavigation { get; set; } = new List<UNITCONVERSION1>();

    public virtual UNITSTYPE UNITSTYPENavigation { get; set; }
}