// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// The Users of the system.
/// </summary>
public partial class User
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// The Users Login (user id).
    /// </summary>
    public string UserLogin { get; set; }

    /// <summary>
    /// The name of the user.
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// The Description of the user.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Is the user Disabled.
    /// </summary>
    public bool IsDisabled { get; set; }

    /// <summary>
    /// The users default profile.
    /// </summary>
    public int? DefaultProfileId { get; set; }

    /// <summary>
    /// The xml data containing all the settings for the user.
    /// </summary>
    public string Settings { get; set; }

    public virtual ICollection<Canvas> Canvas { get; set; } = new List<Canvas>();

    public virtual Profile DefaultProfile { get; set; }

    public virtual ICollection<Expression> Expression { get; set; } = new List<Expression>();

    public virtual ICollection<Profile> Profile { get; set; } = new List<Profile>();

    public virtual ICollection<UserObjectCategory> UserObjectCategory { get; set; } = new List<UserObjectCategory>();

    public virtual ICollection<View> View { get; set; } = new List<View>();

    public virtual ICollection<Role> Role { get; set; } = new List<Role>();
}