// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

/// <summary>
/// Details information pertaining to the links between a saved view and the compounds that comprise it.
/// </summary>
public partial class ViewCompound
{
    /// <summary>
    /// The auto incrementing integer primary key.
    /// </summary>
    public int ViewCompoundId { get; set; }

    /// <summary>
    /// The related View for the ViewCompound.
    /// </summary>
    public int ViewId { get; set; }

    /// <summary>
    /// The FilterId related to this ViewCompound.
    /// </summary>
    public int? FilterId { get; set; }

    /// <summary>
    /// A Compound used by the View. This is nullable such that, if the compound is temporarily deleted, the details of the view are not accidently deleted.
    /// </summary>
    public int? CompoundId { get; set; }

    /// <summary>
    /// The xml data comprising the ViewCompound.
    /// </summary>
    public string ViewCompoundData { get; set; }

    public virtual CacheGroupViewCompound CacheGroupViewCompound { get; set; }

    public virtual Expression Filter { get; set; }

    public virtual View View { get; set; }
}