// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class VSCOREREFIDENTITY
{
    public int VSPID { get; set; }

    public string DUMMY { get; set; }
}