// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class VSCOREDETAILS
{
    public int CID { get; set; }

    public string NAME { get; set; }

    public string VALUE { get; set; }

    public virtual VSCORE CIDNavigation { get; set; }

    public virtual VSCORECODE NAMENavigation { get; set; }
}