// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class VSCOREFIELD
{
    public string FIELDTABLE { get; set; }

    public string FIELDNAME { get; set; }

    public string EXTERNALTABLE { get; set; }

    public string EXTERNALFIELD { get; set; }

    public byte? CTYPE { get; set; }

    public int? PID { get; set; }

    public virtual VSTYPE CTYPENavigation { get; set; }

    public virtual VSCOREREF PIDNavigation { get; set; }
}