// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFACQ;

public partial class VW_B_Samples_Available
{
    public string HOLEID { get; set; }

    public int? days_since_drilled { get; set; }

    public string SAMPLEID { get; set; }

    public string Drum_ID { get; set; }

    public double? Al2O3 { get; set; }

    public double? Asp { get; set; }

    public double? Ba { get; set; }

    public double? CaO { get; set; }

    public double? Cl { get; set; }

    public double? Co { get; set; }

    public double? Cr { get; set; }

    public double? Cu { get; set; }

    public double? Fe { get; set; }

    public double? K2O { get; set; }

    public double? LOI1000 { get; set; }

    public double? LOI425 { get; set; }

    public double? LOI650 { get; set; }

    public double? MgO { get; set; }

    public double? Mn { get; set; }

    public double? Na2O { get; set; }

    public double? Ni { get; set; }

    public double? P { get; set; }

    public double? Pb { get; set; }

    public double? S { get; set; }

    public double? SiO2 { get; set; }

    public double? Sn { get; set; }

    public double? Sr { get; set; }

    public double? TiO2 { get; set; }

    public double? V { get; set; }

    public double? Zn { get; set; }

    public double? Zr { get; set; }

    public double? WtRec { get; set; }
}