// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class ACQ_COLLARS
{
    public string HOLEID { get; set; }

    public string PROJECTCODE { get; set; }

    public string TENEMENTID { get; set; }

    public string GRIDNAME { get; set; }

    public string HOLETYPE { get; set; }

    public double? EAST { get; set; }

    public double? NORTH { get; set; }

    public double? RL { get; set; }

    public double? DEPTH { get; set; }

    public string PROSPECT { get; set; }

    public string STARTDATE { get; set; }

    public string ENDDATE { get; set; }

    public Guid GLOBALID { get; set; }

    public DateTime? Actual_Drill_Date { get; set; }

    public DateTime? Alternate_DrillDate { get; set; }

    public DateTime? Date_Bag_Slashed { get; set; }

    public DateTime? Date_Cleared { get; set; }

    public DateTime? Date_Part_Cleared { get; set; }

    public DateTime? Date_Partial_Rehab { get; set; }

    public DateTime? Date_Pegged { get; set; }

    public DateTime? Date_Photographed { get; set; }

    public DateTime? Date_plan_Imported { get; set; }

    public DateTime? Date_Sample_Stored { get; set; }

    public DateTime? DH_Geophys_Date { get; set; }

    public DateTime? GDP_DATE { get; set; }

    public DateTime? GPSCUT_Date { get; set; }

    public DateTime? Last_Modified { get; set; }

    public DateTime? Logging_Geo_Date { get; set; }

    public DateTime? MineDate_2013_LOM { get; set; }

    public DateTime? MineDate_2015_Accel { get; set; }

    public DateTime? MineDate_201508_LOMP { get; set; }

    public DateTime? MineDate_30Month { get; set; }

    public DateTime? MineDate_Tails_2015 { get; set; }

    public DateTime? Planned_Date { get; set; }

    public DateTime? Planned_DrilledByDat { get; set; }

    public DateTime? Planned_MineDate { get; set; }

    public DateTime? Pln_DDte_201508_LOMP { get; set; }

    public DateTime? Survey_Date { get; set; }

    public DateTime? Validated_Date { get; set; }

    public string Actual_RigID { get; set; }

    public double? ApproxDepthFrom { get; set; }

    public double? ApproxDepthTo { get; set; }

    public string Archive_Survey_Methd { get; set; }

    public string Archive_Survey_Valid { get; set; }

    public string Archived_Survey_By { get; set; }

    public string Archived_Survey_Date { get; set; }

    public string Assays_Valid { get; set; }

    public string Cleared { get; set; }

    public string Clearing_Status { get; set; }

    public string Collar_Cut { get; set; }

    public string Collar_Valid { get; set; }

    public string Computer_Name { get; set; }

    public double? Contracted_Year { get; set; }

    public string Date_Scarified { get; set; }

    public string Date_water_meas { get; set; }

    public string Destroyed { get; set; }

    public string DH_Geophys { get; set; }

    public string DH_Geophys_Company { get; set; }

    public string DH_Geophys_LogUnit { get; set; }

    public string Diamond_Selected { get; set; }

    public string Dipping_Status { get; set; }

    public string DND { get; set; }

    public string Drilled_Peg_ID { get; set; }

    public string DrillEquipRecovered { get; set; }

    public string DrillholeType { get; set; }

    public string DrillPattern { get; set; }

    public double? DrillPriority { get; set; }

    public string Drum_Destroyed { get; set; }

    public string Drum_ID { get; set; }

    public string DuplicateSelected { get; set; }

    public string ExemptRehab { get; set; }

    public string GDA { get; set; }

    public string GDP { get; set; }

    public string Geol_Interp_Valid { get; set; }

    public double? GPS_Easting { get; set; }

    public string GPS_HOLEID { get; set; }

    public double? GPS_Latitude { get; set; }

    public double? GPS_Longitude { get; set; }

    public double? GPS_Northing { get; set; }

    public double? GPS_Zone { get; set; }

    public string GPSCUT_By { get; set; }

    public string Historic_Hole_ID { get; set; }

    public string Hole_Cleared_By { get; set; }

    public string Hole_Exported { get; set; }

    public string Hole_Pegged_By { get; set; }

    public double? Hole_Priority { get; set; }

    public string Hole_Purpose { get; set; }

    public string Hole_Status { get; set; }

    public string Hole_Validated_By { get; set; }

    public string HoleCollared { get; set; }

    public string HolePlugged { get; set; }

    public string Instrument_Geophys { get; set; }

    public string Landfill_Analysis { get; set; }

    public string Lith_Valid { get; set; }

    public string Logging_Complete { get; set; }

    public string Logging_Geo { get; set; }

    public string Machine { get; set; }

    public string MeasureDrillRecorded { get; set; }

    public string Metals_Analysis { get; set; }

    public double? Mine_Month { get; set; }

    public double? Mine_Period { get; set; }

    public string Mine_Plan { get; set; }

    public double? Mine_Year { get; set; }

    public string MiningProposal { get; set; }

    public string Model_Area { get; set; }

    public string Model_Release { get; set; }

    public string Model_Status { get; set; }

    public string MoistureTest { get; set; }

    public string Oil_Spills { get; set; }

    public string Original_TenementID { get; set; }

    public string Pad_Rehab { get; set; }

    public string Parent_Hole_ID { get; set; }

    public string Peg_ID { get; set; }

    public string Peg_Marked { get; set; }

    public string Pegged { get; set; }

    public string PegLabelled { get; set; }

    public string PermitOfWork { get; set; }

    public string Photographed { get; set; }

    public double? Plan_Drill_Priority { get; set; }

    public string PlanDepthReached { get; set; }

    public string Planned_Area { get; set; }

    public double? Planned_Depth { get; set; }

    public double? Planned_DryMetres { get; set; }

    public double? Planned_DupDepth { get; set; }

    public double? Planned_Duplicate { get; set; }

    public double? Planned_Leadtime { get; set; }

    public double? Planned_nncountc { get; set; }

    public double? Planned_nncountu { get; set; }

    public double? Planned_nnstdevc { get; set; }

    public double? Planned_nnstdevu { get; set; }

    public double? Planned_OreDepth { get; set; }

    public double? Planned_PitDepth { get; set; }

    public double? Planned_Priority { get; set; }

    public double? Planned_RockDepth { get; set; }

    public double? Planned_Standard { get; set; }

    public double? Planned_StandardDpth { get; set; }

    public double? Planned_WaterDepth { get; set; }

    public double? Planned_WetMetres { get; set; }

    public string Pln_Year_201508_LOMP { get; set; }

    public string Pln_YrMn_201508_LOMP { get; set; }

    public string Pln_YrQt_201508_LOMP { get; set; }

    public string PlugLabelled { get; set; }

    public string POW { get; set; }

    public double? Precollar_Depth { get; set; }

    public string PreCollarType { get; set; }

    public string Program_ID { get; set; }

    public string Proposed_By { get; set; }

    public double? Proposed_Depth { get; set; }

    public string Region { get; set; }

    public string Rehabbed_By { get; set; }

    public string Rej_Def_Reason { get; set; }

    public string Reliability { get; set; }

    public string Responsible_Person { get; set; }

    public string Rubbish { get; set; }

    public string Sample_Stored_By { get; set; }

    public string SampSizeInspected { get; set; }

    public double? Section { get; set; }

    public string Selenium { get; set; }

    public string StandardInserted { get; set; }

    public string StandardSpiked { get; set; }

    public string SubRegion { get; set; }

    public string Sump { get; set; }

    public string Survey_By { get; set; }

    public string Survey_Method { get; set; }

    public string Survey_Valid { get; set; }

    public string Survey_ValidBy { get; set; }

    public string SurveyValidated_Date { get; set; }

    public string TailType { get; set; }

    public string Testing_Required { get; set; }

    public string Twin1_Hole_ID { get; set; }

    public string Twin2_Hole_ID { get; set; }

    public string Validated { get; set; }

    public string Water_Area { get; set; }

    public string Water_Measured_By { get; set; }

    public double? Water_Table_Raw { get; set; }

    public string Water_Table_Reliable { get; set; }

    public string Water_Table_Valid { get; set; }

    public double? Wet_Sample_Depth { get; set; }

    public string Who_Modified { get; set; }

    public string Cmnts_DrillEquipRec { get; set; }

    public string Cmnts_DupSelected { get; set; }

    public string Cmnts_HoleCollared { get; set; }

    public string Cmnts_HolePlugged { get; set; }

    public string Cmnts_MeasureRecord { get; set; }

    public string Cmnts_PegLabelled { get; set; }

    public string Cmnts_PlanDepthReach { get; set; }

    public string Cmnts_PlugLabelled { get; set; }

    public string Cmnts_SampSizeInspec { get; set; }

    public string Cmnts_StandardInsert { get; set; }

    public string Cmnts_StandardSpiked { get; set; }

    public string Cmnts_Collar { get; set; }

    public string Cmnts_MetaData { get; set; }

    public string Cmnts_PlannedCollar { get; set; }

    public string Cmnts_Rehab { get; set; }

    public string Cmnts_SurveyPickup { get; set; }

    public string Cmnts_Technician { get; set; }

    public string Cmnts_Water { get; set; }

    public string Cmnts_Water_Reading { get; set; }

    public string Cmnts_Water_Table { get; set; }

    public string Data_Srce_Coll { get; set; }

    public string Data_Srce_DHSurv { get; set; }

    public string Data_Srce_MetaData { get; set; }

    public string Data_Srce_Rehab { get; set; }

    public string Data_Srce_Water { get; set; }

    public string Data_Srce_Wtr_Cond { get; set; }

    public string Data_Srce_Wtr_Readng { get; set; }

    public string Risk_Notes { get; set; }

    public string Water_Levels { get; set; }

    public string Water_Valid_Notes { get; set; }
}