// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class ACQ_DRILLHOLES
{
    public string HOLEID { get; set; }

    public double DEPTH { get; set; }

    public double? EASTING { get; set; }

    public double? NORTHING { get; set; }

    public DateOnly? STARTDATE { get; set; }

    public DateOnly? ENDDATE { get; set; }

    public double STARTDEPTH { get; set; }

    public double ENDDEPTH { get; set; }

    public string RIGID { get; set; }

    public string REGION { get; set; }

    public string SUBREGION { get; set; }

    public string TABLET { get; set; }

    public string GEO { get; set; }

    public string PLAN_REGION { get; set; }

    public string PLAN_REGIONPIT { get; set; }

    public string PLAN_SUBREGIONPIT { get; set; }

    public bool? ExistingPlod { get; set; }

    public DateOnly? DateCompleted { get; set; }

    public string Geologist { get; set; }

    public string GeoFull { get; set; }
}