// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class Company
{
    public string C_ID { get; set; }

    public string C_CompanyName { get; set; }

    public virtual ICollection<DrillRigs> DrillRigs { get; set; } = new List<DrillRigs>();
}