// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class Department
{
    public string RHD_ID { get; set; }

    public string RHD_Name { get; set; }

    public virtual ICollection<DrillPlod> DrillPlod { get; set; } = new List<DrillPlod>();
}