// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DespatchSend
{
    public int DS_DespatchID { get; set; }

    public string DS_Lab { get; set; }

    public string DS_DespatchType { get; set; }

    public DateOnly? DS_SendDate { get; set; }

    public bool? DS_Reconciled { get; set; }
}