// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DMP_Tenements
{
    public string DMP_TenementID { get; set; }

    public string DMP_ProjectID { get; set; }

    public string DMP_FormattedTenementID { get; set; }

    public string DMP_TenementType { get; set; }

    public string DMP_TenementStatus { get; set; }

    public string DMP_Company { get; set; }

    public decimal? DMP_LegalArea { get; set; }

    public string DMP_UOM { get; set; }

    public string DMP_ManagingCompany { get; set; }

    public DateTime? DMP_ApplicationDate { get; set; }

    public DateTime? DMP_GrantedDate { get; set; }

    public DateTime? DMP_ExpiryDate { get; set; }

    public string DMP_TenementName { get; set; }

    public string DMP_Comment { get; set; }
}