// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DownholePlodActivity
{
    public string DPA_ActivityID { get; set; }

    public bool DPA_Active { get; set; }

    public virtual ICollection<DownholePlodData> DownholePlodData { get; set; } = new List<DownholePlodData>();
}