// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DownholePlodHeaderError
{
    public string DHPHE_PlodId { get; set; }

    public string DHPHE_ErrorLevel { get; set; }

    public string DHPHE_ErrorDescription { get; set; }

    public virtual DownHolePlodHeader DHPHE_Plod { get; set; }
}