// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DownholePlodEquipmentOnsite
{
    public string GEO_PlodID { get; set; }

    public string GEO_Service { get; set; }

    public string GEO_Manufacturer { get; set; }

    public string GEO_ToolType { get; set; }

    public string GEO_SerialNumber { get; set; }

    public virtual DownHolePlodHeader GEO_Plod { get; set; }

    public virtual DownholePlodService GEO_ServiceNavigation { get; set; }
}