// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DownholePlodService
{
    public string DPS_ServiceID { get; set; }

    public bool? DPS_Active { get; set; }

    public virtual ICollection<DownholePlodEquipmentOnsite> DownholePlodEquipmentOnsite { get; set; } = new List<DownholePlodEquipmentOnsite>();
}