// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DrillDetails_ACQV
{
    public int DD_Plod { get; set; }

    public int DD_Index { get; set; }

    public int? DD_Task { get; set; }

    public string DD_HoleNumber { get; set; }

    public string DD_Start_H { get; set; }

    public string DD_Start_M { get; set; }

    public string DD_Start_S { get; set; }

    public string DD_Finish_H { get; set; }

    public string DD_Finish_M { get; set; }

    public string DD_Finish_S { get; set; }

    public string DD_Total_H { get; set; }

    public string DD_Total_M { get; set; }

    public string DD_Total_S { get; set; }
}