// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DrillConsumables
{
    public int DC_Plod { get; set; }

    public int DC_Index { get; set; }

    public string DC_Consumable { get; set; }

    public decimal? DC_Quantity { get; set; }

    public string DC_UOM { get; set; }

    public DateTime? DC_SysStart { get; set; }

    public DateTime? DC_SysEnd { get; set; }
}