// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DrillHydrocarbons1
{
    public int DHC_Plod { get; set; }

    public int DHC_Index { get; set; }

    public string DHC_Lubricant { get; set; }

    public int? DHC_Amount { get; set; }

    public DateTime? DHC_SysStart { get; set; }

    public DateTime? DHC_SysEnd { get; set; }
}