// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DrillPlod
{
    public int DP_Plod { get; set; }

    public string DP_Project { get; set; }

    public DateOnly DP_Date { get; set; }

    public string DP_Rig { get; set; }

    public string DP_Location { get; set; }

    public string DP_Shift { get; set; }

    public string DP_Client { get; set; }

    public string DP_Geologist { get; set; }

    public bool? DP_Complete { get; set; }

    public DateTime? DP_SysStart { get; set; }

    public DateTime? DP_SysEnd { get; set; }

    public virtual Department DP_ProjectNavigation { get; set; }

    public virtual DrillRigs DP_RigNavigation { get; set; }
}