// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DrillRigs
{
    public string DR_ID { get; set; }

    public string DR_Histroical_ID { get; set; }

    public string DR_Company { get; set; }

    public string DR_RigType { get; set; }

    public bool? DR_Active { get; set; }

    public DateTime? DR_SysStart { get; set; }

    public DateTime? DR_SysEnd { get; set; }

    public virtual Company DR_CompanyNavigation { get; set; }

    public virtual ICollection<DrillPlod> DrillPlod { get; set; } = new List<DrillPlod>();

    public virtual ICollection<GeoLogDrilling> GeoLogDrilling { get; set; } = new List<GeoLogDrilling>();
}