// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DrillDetails1
{
    public int DD_Plod { get; set; }

    public int DD_Index { get; set; }

    public int? DD_Task { get; set; }

    public string DD_HoleNumber { get; set; }

    public TimeOnly? DD_Start { get; set; }

    public TimeOnly? DD_Finish { get; set; }

    public TimeOnly? DD_Total { get; set; }

    public DateTime? DD_SysStart { get; set; }

    public DateTime? DD_SysEnd { get; set; }
}