// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class DrillTraining_ACQV
{
    public int DT_Plod { get; set; }

    public int DT_Index { get; set; }

    public string DT_Instructor { get; set; }

    public string DT_Trainee { get; set; }

    public string DT_Time_H { get; set; }

    public string DT_Time_M { get; set; }

    public string DT_Time_S { get; set; }

    public TimeOnly? DT_Time { get; set; }
}