// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class GeophysLASHeader
{
    public string GLH_Holeid { get; set; }

    public string GLH_MineSite { get; set; }

    public string GLH_Department { get; set; }

    public string GLH_DrillType { get; set; }

    public string GLH_HolePurpose { get; set; }

    public string GLH_DrillStage { get; set; }

    public decimal? GLH_Easting { get; set; }

    public decimal? GLH_Northing { get; set; }

    public decimal? GLH_StartDepth { get; set; }

    public string GLH_StartDepthUnits { get; set; }

    public decimal? GLH_StopDepth { get; set; }

    public string GLH_StopDepthUnits { get; set; }

    public decimal? GLH_StepInterval { get; set; }

    public string GLH_StepIntervalUnits { get; set; }

    public string GLH_ServiceCompany { get; set; }

    public string GLH_Company { get; set; }

    public string GLH_LicenceNumber { get; set; }

    public decimal? GLH_NULLSubstituteValue { get; set; }

    public string GLH_Province { get; set; }

    public string GLH_WellIdentifier { get; set; }

    public DateOnly? GLH_LASLogDate { get; set; }

    public string GLH_Location { get; set; }

    public string GLH_Country { get; set; }

    public decimal? GLH_Latitude { get; set; }

    public decimal? GLH_Longitude { get; set; }

    public string GLH_SurveyType { get; set; }
}