// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class GeophysMWDHeader
{
    public string GMH_Holeid { get; set; }

    public decimal? GMH_Start { get; set; }

    public decimal? GMH_Stop { get; set; }

    public decimal? GMH_Step { get; set; }

    public decimal? GMH_Null { get; set; }

    public string GMH_Company { get; set; }

    public string GMH_Location { get; set; }

    public string GMH_Country { get; set; }

    public string GMH_ServiceCompany { get; set; }

    public DateOnly? GMH_Date { get; set; }

    public string GMH_Province { get; set; }

    public string GMH_WellIdentifier { get; set; }

    public string GMH_Api { get; set; }

    public string GMH_HammerType { get; set; }

    public string GMH_Rigid { get; set; }
}