// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class GeophysLASDetails
{
    public string GLD_Holeid { get; set; }

    public decimal GLD_Depth { get; set; }

    public decimal? GLD_Caliper { get; set; }

    public decimal? GLD_Density { get; set; }

    public decimal? GLD_DensityH { get; set; }

    public decimal? GLD_NorthDeviation { get; set; }

    public decimal? GLD_EastDeviation { get; set; }

    public decimal? GLD_Distance { get; set; }

    public decimal? GLD_Azimuth { get; set; }

    public decimal? GLD_Sang { get; set; }

    public decimal? GLD_SangBeta { get; set; }

    public decimal? GLD_GamNat { get; set; }

    public decimal? GLD_Susceptability { get; set; }

    public decimal? GLD_GamGam { get; set; }

    public decimal? GLD_NSGNDEV { get; set; }

    public decimal? GLD_NSGEDEV { get; set; }

    public decimal? GLD_NSGDISTANCE { get; set; }

    public decimal? GLD_NSGAZIMUTH { get; set; }

    public decimal? GLD_NSGSANG { get; set; }

    public decimal? GLD_NSGSANGB { get; set; }

    public decimal? GLD_DIP { get; set; }

    public decimal? GLD_NSGDIP { get; set; }

    public decimal? GLD_TL_ShortSpace { get; set; }

    public decimal? GLD_TL_LongSpace { get; set; }

    public decimal? GLD_TL_CompDensity { get; set; }

    public decimal? GLD_WSG_ShortSpace { get; set; }

    public decimal? GLD_WSG_LongSpace { get; set; }

    public decimal? GLD_WSG_CompDensity { get; set; }
}