// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class GeophysLASParameters
{
    public string GLP_Holeid { get; set; }

    public string GLP_FileType { get; set; }

    public string GLP_FileTypeIdentifier { get; set; }

    public string GLP_SystemVersion { get; set; }

    public decimal? GLP_TruckCalibrationNumber { get; set; }

    public decimal? GLP_ToolSerialNumber { get; set; }

    public decimal? GLP_TimeHrHrMinMin { get; set; }

    public decimal? GLP_Latitude { get; set; }

    public decimal? GLP_Longitude { get; set; }

    public string GLP_LogMeasuredFrom { get; set; }

    public string GLP_DrillerMeasuredFrom { get; set; }

    public string GLP_PermanentData { get; set; }

    public string GLP_ElevationGroundLevel { get; set; }

    public decimal? GLP_DrillerDepth { get; set; }

    public decimal? GLP_CasingDiameter { get; set; }

    public string GLP_CasingType { get; set; }

    public string GLP_LoggingUnit { get; set; }

    public string GLP_RecordedBy { get; set; }

    public decimal? GLP_BitSize { get; set; }

    public decimal? GLP_MagneticDeclination { get; set; }

    public decimal? GLP_DensityMatrix { get; set; }

    public string GLP_NeutronMatrix { get; set; }

    public decimal? GLP_DeltaTMatrix { get; set; }

    public string GLP_FluidType { get; set; }

    public decimal? GLP_ElectronCutoff { get; set; }

    public string GLP_CasingThickness { get; set; }

    public string GLP_CasingLogger { get; set; }

    public decimal? GLP_SystsemSerialNumber { get; set; }

    public decimal? GLP_Northing { get; set; }

    public decimal? GLP_Easting { get; set; }

    public string GLP_ElevationPermanentData { get; set; }

    public string GLP_SourceId { get; set; }

    public string GLP_MudSampleSource { get; set; }

    public string GLP_Comment1 { get; set; }

    public string GLP_Comment2 { get; set; }

    public string GLP_Comment3 { get; set; }

    public string GLP_TemperatureGradient { get; set; }

    public string GLP_MudResistivity { get; set; }

    public string GLP_MudTemperature { get; set; }

    public string GLP_ResistivityMudCake { get; set; }

    public string GLP_CasingBottom { get; set; }

    public string GLP_TimeCirculationStopped { get; set; }

    public decimal? GLP_MudWeight { get; set; }

    public decimal? GLP_DensityToolSerialNumber { get; set; }

    public string GLP_DensityToolSourceNumber { get; set; }

    public string GLP_ElevationKellyBushing { get; set; }

    public string GLP_ElevationDF { get; set; }

    public decimal? GLP_MagSuscToolSerialNumber { get; set; }

    public decimal? GLP_GyroToolSerialNumber { get; set; }

    public decimal? GLP_SonicToolSerialNumber { get; set; }

    public string GLP_MeanSurfaceTemperature { get; set; }

    public decimal? GLP_FluidLevel { get; set; }

    public string GLP_DeltaTFluid { get; set; }

    public string GLP_ResistivityMudFiltrate { get; set; }

    public string GLP_TemperatureMudFiltrate { get; set; }

    public string GLP_TemperatureMudCake { get; set; }

    public string GLP_FluidViscosity { get; set; }

    public string GLP_FuildPH { get; set; }

    public string GLP_LoggerTD { get; set; }

    public string GLP_ArrivalTime { get; set; }

    public string GLP_DepartureTime { get; set; }

    public string GLP_RigNumber { get; set; }
}