// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class GeophysDetails
{
    public string GPD_Drillhole { get; set; }

    public string GPD_Program { get; set; }

    public DateOnly GPD_DateLogged { get; set; }

    public decimal GPD_MeasurementDepth { get; set; }

    public decimal? GPD_Caliper { get; set; }

    public decimal? GPD_Density { get; set; }

    public decimal? GPD_DensityH { get; set; }

    public decimal? GPD_NSG_NorthDeviation { get; set; }

    public decimal? GPD_NSG_EastDeviation { get; set; }

    public decimal? GPD_NSG_Distance { get; set; }

    public decimal? GPD_NSG_Azimuth { get; set; }

    public decimal? GPD_NSG_Sang { get; set; }

    public decimal? GPD_NSG_SangB { get; set; }

    public decimal? GPD_NSG_Dip { get; set; }

    public decimal? GPD_EastDeviation { get; set; }

    public decimal? GPD_NorthDeviation { get; set; }

    public decimal? GPD_Distance { get; set; }

    public decimal? GPD_Azimuth { get; set; }

    public decimal? GPD_Sang { get; set; }

    public decimal? GPD_SangB { get; set; }

    public decimal? GPD_Dip { get; set; }

    public decimal? GPD_NaturalGamma { get; set; }

    public decimal? GPD_Susceptability { get; set; }

    public decimal? GPD_GamGam { get; set; }

    public decimal? GPD_Stat { get; set; }

    public decimal? GPD_MagneticVector { get; set; }
}