// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class GeophysLASFileLocation
{
    public string GLFL_HistoricHoleid { get; set; }

    public DateTime GLFL_ProcessDateTime { get; set; }

    public string GLFL_FileLocation { get; set; }

    public string GLFL_Status { get; set; }
}