// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class ImportFieldMapping
{
    public string LDM_LASField { get; set; }

    public string LDM_DatabaseField { get; set; }

    public string LDM_ImportType { get; set; }
}