// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using RHOKSAutomationConsole.EFRHOKS2020;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace RHOKSAutomationConsole.EFRHOKS2020
{
    public partial interface IRHOKS_2020ContextProcedures
    {
        Task<int> AC_SamplePhotos_RHOKS_2020Async(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_0100_ACQDespatchSendPivotResult>> SP_0100_ACQDespatchSendPivotAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_0110_ACQDespatchReturnPivotResult>> SP_0110_ACQDespatchReturnPivotAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_DynamicMerge_Q2Async(string CATALOG_IN, string SCHEMA_IN, string TARGET_IN, string SOURCE_IN, string DynamicTable, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_MergeACQDepthsResult>> SP_MergeACQDepthsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Update_ACQ_DRILLHOLES_TableAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UPDATE_DOWNHOLE_LAS_HEADERResult>> SP_UPDATE_DOWNHOLE_LAS_HEADERAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
