// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class IRImportFieldMapping
{
    public string IRLDM_LASField { get; set; }

    public string IRLDM_DatabaseField { get; set; }

    public string IRLDM_ImportType { get; set; }
}