// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class IRLASCurves
{
    public string IRGPC_Drillhole { get; set; }

    public int IRGPC_ColumnOrder { get; set; }

    public string IRGPC_Field { get; set; }

    public string IRGPC_Units { get; set; }

    public string IRGPC_APICode { get; set; }

    public string IRGPC_Description { get; set; }

    public virtual IRLASHeader IRGPC_DrillholeNavigation { get; set; }
}