// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class IRLASReadings
{
    public string IRGPR_Drillhole { get; set; }

    public decimal IRGPR_ReadingDepth { get; set; }

    public decimal? IRGPR_Caliper { get; set; }

    public decimal? IRGPR_Density { get; set; }

    public decimal? IRGPR_DensityH { get; set; }

    public decimal? IRGPR_NorthDeviation { get; set; }

    public decimal? IRGPR_EastDeviation { get; set; }

    public decimal? IRGPR_Distance { get; set; }

    public decimal? IRGPR_Azimuth { get; set; }

    public decimal? IRGPR_SAngle { get; set; }

    public decimal? IRGPR_SAngleB { get; set; }

    public decimal? IRGPR_NaturalGamma { get; set; }

    public decimal? IRGPR_Susceptibility { get; set; }

    public decimal? IRGPR_OpenHoleGamma { get; set; }

    public decimal? IRGPR_InRodGamma { get; set; }

    public decimal? IRGPR_Dip { get; set; }

    public decimal? IRGPR_FluidResistivity { get; set; }

    public decimal? IRGPR_DensityPorosity { get; set; }

    public decimal? IRGPR_ShortGuardResistivity { get; set; }

    public decimal? IRGPR_SingleNeutron { get; set; }

    public decimal? IRGPR_MagVect { get; set; }

    public decimal? IRGPR_DepthDifference { get; set; }

    public decimal? IRGPR_Temperature { get; set; }

    public decimal? IRGPR_XInclination { get; set; }

    public decimal? IRGPR_ZFlux { get; set; }

    public decimal? IRGPR_YFlux { get; set; }

    public decimal? IRGPR_TrueDepth { get; set; }

    public decimal? IRGPR_Stat { get; set; }

    public decimal? IRGPR_LSD { get; set; }

    public decimal? IRGPR_SSD { get; set; }

    public decimal? IRGPR_LSDCorrected { get; set; }

    public virtual IRLASHeader IRGPR_DrillholeNavigation { get; set; }
}