// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class IRLASHeaderDetails
{
    public string IRGHD_Drillhole { get; set; }

    public string IRGHD_Filetype { get; set; }

    public string IRGHD_FileIdentifier { get; set; }

    public string IRGHD_SystemVersion { get; set; }

    public string IRGHD_SystemSerial { get; set; }

    public string IRGHD_TruckCalibrationNumber { get; set; }

    public string IRGHD_ToolSerialNumber { get; set; }

    public string IRGHD_ReadingTime { get; set; }

    public decimal? IRGHD_Northing { get; set; }

    public decimal? IRGHD_Easting { get; set; }

    public decimal? IRGHD_Latitude { get; set; }

    public decimal? IRGHD_Longitude { get; set; }

    public string IRGHD_LogMeasuredFrom { get; set; }

    public string IRGHD_DrillerMeasuredFrom { get; set; }

    public string IRGHD_PermanentData { get; set; }

    public decimal? IRGHD_ElevationGroundLevel { get; set; }

    public decimal? IRGHD_DrillersDepth { get; set; }

    public decimal? IRGHD_CasingDiameter { get; set; }

    public decimal? IRGHD_CasingBottom { get; set; }

    public string IRGHD_CasingType { get; set; }

    public decimal? IRGHD_CasingThickness { get; set; }

    public string IRGHD_LoggingUnit { get; set; }

    public string IRGHD_LoggingBy { get; set; }

    public string IRGHD_SourceIdentifier { get; set; }

    public decimal? IRGHD_BitSize { get; set; }

    public decimal? IRGHD_MagneticDeclination { get; set; }

    public decimal? IRGHD_DensityMatrix { get; set; }

    public string IRGHD_NeutronMatrix { get; set; }

    public decimal? IRGHD_DeltaTMatrix { get; set; }

    public string IRGHD_FluidType { get; set; }

    public decimal? IRGHD_ElectronCutoff { get; set; }

    public string IRGHD_OtherServicePrimary { get; set; }

    public string IRGHD_OtherServiceSecondary { get; set; }

    public string IRGHD_OtherServiceTertiary { get; set; }

    public string IRGHD_DensityToolSerial { get; set; }

    public string IRGHD_DensityToolSource { get; set; }

    public string IRGHD_MagneticSusceptabilityToolSerial { get; set; }

    public string IRGHD_GyroToolSerial { get; set; }

    public string IRGHD_SonicToolSerial { get; set; }

    public decimal? IRGHD_FluidLevel { get; set; }

    public decimal? IRGHD_DeviationOrientation { get; set; }

    public virtual IRLASHeader IRGHD_DrillholeNavigation { get; set; }
}