// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class LASCurves
{
    public string GPC_Drillhole { get; set; }

    public int GPC_ColumnOrder { get; set; }

    public string GPC_Field { get; set; }

    public string GPC_Units { get; set; }

    public string GPC_APICode { get; set; }

    public string GPC_Description { get; set; }

    public virtual LASHeader GPC_DrillholeNavigation { get; set; }
}