// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class LASHeaderDetails
{
    public string GHD_Drillhole { get; set; }

    public string GHD_Filetype { get; set; }

    public string GHD_FileIdentifier { get; set; }

    public string GHD_SystemVersion { get; set; }

    public string GHD_SystemSerial { get; set; }

    public string GHD_TruckCalibrationNumber { get; set; }

    public string GHD_ToolSerialNumber { get; set; }

    public string GHD_ReadingTime { get; set; }

    public decimal? GHD_Northing { get; set; }

    public decimal? GHD_Easting { get; set; }

    public decimal? GHD_Latitude { get; set; }

    public decimal? GHD_Longitude { get; set; }

    public string GHD_LogMeasuredFrom { get; set; }

    public string GHD_DrillerMeasuredFrom { get; set; }

    public string GHD_PermanentData { get; set; }

    public decimal? GHD_ElevationGroundLevel { get; set; }

    public decimal? GHD_DrillersDepth { get; set; }

    public decimal? GHD_CasingDiameter { get; set; }

    public decimal? GHD_CasingBottom { get; set; }

    public string GHD_CasingType { get; set; }

    public decimal? GHD_CasingThickness { get; set; }

    public string GHD_LoggingUnit { get; set; }

    public string GHD_LoggingBy { get; set; }

    public string GHD_SourceIdentifier { get; set; }

    public decimal? GHD_BitSize { get; set; }

    public decimal? GHD_MagneticDeclination { get; set; }

    public decimal? GHD_DensityMatrix { get; set; }

    public string GHD_NeutronMatrix { get; set; }

    public decimal? GHD_DeltaTMatrix { get; set; }

    public string GHD_FluidType { get; set; }

    public decimal? GHD_ElectronCutoff { get; set; }

    public string GHD_OtherServicePrimary { get; set; }

    public string GHD_OtherServiceSecondary { get; set; }

    public string GHD_OtherServiceTertiary { get; set; }

    public string GHD_DensityToolSerial { get; set; }

    public string GHD_DensityToolSource { get; set; }

    public string GHD_MagneticSusceptabilityToolSerial { get; set; }

    public string GHD_GyroToolSerial { get; set; }

    public string GHD_SonicToolSerial { get; set; }

    public decimal? GHD_FluidLevel { get; set; }

    public decimal? GHD_DeviationOrientation { get; set; }

    public virtual LASHeader GHD_DrillholeNavigation { get; set; }
}