// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class LASLoggingUpdate
{
    public string GLU_Drillhole { get; set; }

    public DateOnly? GLU_UpdateDate { get; set; }

    public string GLU_Operation { get; set; }

    public decimal? GLU_Easting { get; set; }

    public decimal? GLU_Northing { get; set; }

    public decimal? GLU_PlannedDip { get; set; }

    public decimal? GLU_PlannedAzimuth { get; set; }

    public string GLU_PegNumber { get; set; }

    public decimal? GLU_DrilledDepth { get; set; }

    public bool? GLU_RGammaRecorded { get; set; }

    public DateOnly? GLU_RGammaDate { get; set; }

    public decimal? GLU_RGammaDepth { get; set; }

    public bool? GLU_RGammaToolHangup { get; set; }

    public decimal? GLU_RGammaToolHangupDepth { get; set; }

    public bool? GLU_GyroRecorded { get; set; }

    public DateOnly? GLU_GyroDate { get; set; }

    public decimal? GLU_GyroDepth { get; set; }

    public bool? GLU_GyroToolHangup { get; set; }

    public decimal? GLU_GyroToolHangupDepth { get; set; }

    public string GLU_InRodOperator { get; set; }

    public string GLU_InRodServiceCompany { get; set; }

    public string GLU_InRodTruckNumber { get; set; }

    public bool? GLU_MagsusRecorded { get; set; }

    public DateOnly? GLU_MagsusDate { get; set; }

    public decimal? GLU_MagsusDepth { get; set; }

    public bool? GLU_DensityRecorded { get; set; }

    public DateOnly? GLU_DensityDate { get; set; }

    public decimal? GLU_DensityDepth { get; set; }

    public string GLU_OpenHoleOperator { get; set; }

    public string GLU_OpenHoleServiceCompany { get; set; }

    public string GLU_OpenHoleTruckNumber { get; set; }

    public bool? GLU_OTVRecorded { get; set; }

    public DateOnly? GLU_OTVDate { get; set; }

    public decimal? GLU_OTVDepth { get; set; }

    public bool? GLU_ATVRecorded { get; set; }

    public DateOnly? GLU_ATVDate { get; set; }

    public decimal? GLU_ATVDepth { get; set; }

    public string GLU_OpticalBoreholeVisibility { get; set; }

    public string GLU_OpticalWaterVisibility { get; set; }

    public string GLU_OpenHoleTVOperator { get; set; }

    public string GLU_OpenHoleTVServiceCompany { get; set; }

    public string GLU_OpenHoleTVTruckNumber { get; set; }

    public decimal? GLU_ApproxWaterTableDepth { get; set; }

    public bool? GLU_CompletedDrillhole { get; set; }

    public string GLU_PadConditionWhenLeft { get; set; }

    public string GLU_LoggingOperatorsComments { get; set; }

    public decimal? GLU_PercentageOpenHoleLogged { get; set; }

    public string GLU_DensityToolNumber { get; set; }

    public string GLU_DensitySourceNumber { get; set; }
}