// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class LifeOfMinePit
{
    public string LOMP_OBJECT { get; set; }

    public string LOMP_Name { get; set; }

    public string LOMP_SubPit { get; set; }
}