// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class MineralogicalCodes
{
    public string MC_Code { get; set; }

    public string MC_Description { get; set; }

    public bool? MC_Active { get; set; }

    public virtual GeoLoggingMineralogical GeoLoggingMineralogical { get; set; }
}