// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class MinePlanningPit
{
    public DateOnly MPP_LoadDate { get; set; }

    public string MPP_Region { get; set; }
}