// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using RHOKSAutomationConsole.EFRHOKS2020;

namespace RHOKSAutomationConsole.EFRHOKS2020
{
    public partial class RHOKS_2020Context
    {

        [DbFunction("fn_MROUND", "dbo")]
        public static int? fn_MROUND(int? num, int? mult)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("LatLongFromEastNorth", "dbo")]
        public IQueryable<LatLongFromEastNorthResult> LatLongFromEastNorth(double? Easting, double? Northing, int? Zone)
        {
            return FromExpression(() => LatLongFromEastNorth(Easting, Northing, Zone));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LatLongFromEastNorthResult>().HasNoKey();
        }
    }
}
