// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class SURTECH_SHIFT
{
    public string SS_VEHICLE { get; set; }

    public DateOnly SS_DATE { get; set; }

    public string SS_CLIENT { get; set; }

    public string SS_PROJECT { get; set; }

    public string SS_LEASE { get; set; }

    public string SS_LOCATION { get; set; }

    public string SS_OPERATOR { get; set; }

    public int? SS_CHARGE { get; set; }

    public virtual ICollection<SURTECH_ACTIVITY> SURTECH_ACTIVITY { get; set; } = new List<SURTECH_ACTIVITY>();

    public virtual ICollection<SURTECH_DETAILS> SURTECH_DETAILS { get; set; } = new List<SURTECH_DETAILS>();

    public virtual ICollection<SURTECH_EQUIPMENT> SURTECH_EQUIPMENT { get; set; } = new List<SURTECH_EQUIPMENT>();
}