// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class TestCompany
{
    public string C_ID { get; set; }

    public string C_CompanyName { get; set; }

    public decimal C_From { get; set; }

    public decimal C_To { get; set; }

    public string C_TF1 { get; set; }

    public string C_TF2 { get; set; }

    public decimal? C_TF3 { get; set; }
}