// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2020;

public partial class TEST_GEOPHYS_VIEWS_JZ
{
    public string GLH_Holeid { get; set; }

    public string GLH_MineSite { get; set; }

    public string GLH_Department { get; set; }

    public string GLH_DrillType { get; set; }

    public string GLH_HolePurpose { get; set; }

    public string GLH_DrillStage { get; set; }

    public decimal? GLH_Easting { get; set; }

    public decimal? GLH_Northing { get; set; }

    public decimal? GLH_StartDepth { get; set; }

    public string GLH_StartDepthUnits { get; set; }

    public decimal? GLH_StopDepth { get; set; }

    public string GLH_StopDepthUnits { get; set; }

    public decimal? GLH_StepInterval { get; set; }

    public string GLH_StepIntervalUnits { get; set; }

    public string GLH_ServiceCompany { get; set; }

    public string GLH_Company { get; set; }

    public string GLH_LicenceNumber { get; set; }

    public decimal? GLH_NULLSubstituteValue { get; set; }

    public string GLH_Province { get; set; }

    public string GLH_WellIdentifier { get; set; }

    public DateOnly? GLH_LASLogDate { get; set; }

    public string GLH_Location { get; set; }

    public string GLH_Country { get; set; }

    public decimal? GLH_Latitude { get; set; }

    public decimal? GLH_Longitude { get; set; }

    public string GLC_Holeid { get; set; }

    public string GLC_Depth { get; set; }

    public string GLC_DepthUnits { get; set; }

    public string GLC_NorthDeviation { get; set; }

    public string GLC_NorthDeviationUnits { get; set; }

    public string GLC_EastDeviation { get; set; }

    public string GLC_EastDeviationUnits { get; set; }

    public string GLC_Distance { get; set; }

    public string GLC_DistanceUnits { get; set; }

    public string GLC_Azimuth { get; set; }

    public string GLC_AzimuthUnits { get; set; }

    public string GLC_Sangle { get; set; }

    public string GLC_SangleUnits { get; set; }

    public string GLC_SangleBeta { get; set; }

    public string GLC_SangleBetaUnits { get; set; }

    public string GLC_GamNat { get; set; }

    public string GLC_GamNatUnits { get; set; }

    public string GLC_Susceptability { get; set; }

    public string GLC_SusceptabilityUnits { get; set; }

    public string GLC_Caliper { get; set; }

    public string GLC_CaliperUnits { get; set; }

    public string GLC_Density { get; set; }

    public string GLC_DensityUnits { get; set; }

    public string GLC_DensityH { get; set; }

    public string GLC_DensityHUnits { get; set; }

    public string GLC_GamGam { get; set; }

    public string GLC_GamGamUnits { get; set; }

    public string GLC_MagneticVector { get; set; }

    public string GLC_MagneticVectorUnits { get; set; }

    public string GLC_DensityPorosity { get; set; }

    public string GLC_DensityPorosityUnits { get; set; }

    public string GLC_FluidResistivity { get; set; }

    public string GLC_FluidResistivityUnits { get; set; }

    public string GLC_RGamNat { get; set; }

    public string GLC_RGamNatUnits { get; set; }

    public string GLC_YFlux { get; set; }

    public string GLC_YFluxUnits { get; set; }

    public string GLP_Holeid { get; set; }

    public string GLP_FileType { get; set; }

    public string GLP_FileTypeIdentifier { get; set; }

    public string GLP_SystemVersion { get; set; }

    public decimal? GLP_TruckCalibrationNumber { get; set; }

    public decimal? GLP_ToolSerialNumber { get; set; }

    public decimal? GLP_TimeHrHrMinMin { get; set; }

    public decimal? GLP_Latitude { get; set; }

    public decimal? GLP_Longitude { get; set; }

    public string GLP_LogMeasuredFrom { get; set; }

    public string GLP_DrillerMeasuredFrom { get; set; }

    public string GLP_PermanentData { get; set; }

    public string GLP_ElevationGroundLevel { get; set; }

    public decimal? GLP_DrillerDepth { get; set; }

    public decimal? GLP_CasingDiameter { get; set; }

    public string GLP_CasingType { get; set; }

    public string GLP_LoggingUnit { get; set; }

    public string GLP_RecordedBy { get; set; }

    public decimal? GLP_BitSize { get; set; }

    public decimal? GLP_MagneticDeclination { get; set; }

    public decimal? GLP_DensityMatrix { get; set; }

    public string GLP_NeutronMatrix { get; set; }

    public decimal? GLP_DeltaTMatrix { get; set; }

    public string GLP_FluidType { get; set; }

    public decimal? GLP_ElectronCutoff { get; set; }

    public string GLP_CasingThickness { get; set; }

    public string GLP_CasingLogger { get; set; }

    public decimal? GLP_SystsemSerialNumber { get; set; }

    public decimal? GLP_Northing { get; set; }

    public decimal? GLP_Easting { get; set; }

    public string GLP_ElevationPermanentData { get; set; }

    public string GLP_SourceId { get; set; }

    public string GLP_MudSampleSource { get; set; }

    public string GLP_Comment1 { get; set; }

    public string GLP_Comment2 { get; set; }

    public string GLP_Comment3 { get; set; }

    public string GLP_TemperatureGradient { get; set; }

    public string GLP_MudResistivity { get; set; }

    public string GLP_MudTemperature { get; set; }

    public string GLP_ResistivityMudCake { get; set; }

    public string GLP_CasingBottom { get; set; }

    public string GLP_TimeCirculationStopped { get; set; }

    public decimal? GLP_MudWeight { get; set; }
}