// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class CollarPickup
{
    public string Drillhole { get; set; }

    public DateOnly DateCollarPickupFile { get; set; }

    public DateOnly DateCollarPickup { get; set; }

    public decimal? CollarPickupEasting { get; set; }

    public decimal? CollarPickupNorthing { get; set; }

    public decimal? CollarPickupRL { get; set; }

    public string CollarPickupMethod { get; set; }

    public string CollarPickupComment { get; set; }

    public decimal? CollarPlannedEasting { get; set; }

    public decimal? CollarPlannedNorthing { get; set; }

    public decimal? CollarPlannedRL { get; set; }

    public decimal? CollarPeggedEasting { get; set; }

    public decimal? CollarPeggedNorthing { get; set; }

    public decimal? CollarPeggedRL { get; set; }
}