// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class CoordCheck
{
    public string HoleID { get; set; }

    public int WR_Measured_X { get; set; }

    public int WR_Measured_Y { get; set; }

    public int ACQ_Measured_X { get; set; }

    public int ACQ_Measured_Y { get; set; }

    public int Delta_X { get; set; }

    public int Delta_Y { get; set; }
}