// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class LASData
{
    public string WELL { get; set; }

    public decimal? DEPT { get; set; }

    public decimal? SSD { get; set; }

    public decimal? LSD { get; set; }

    public decimal? LSD_CORR { get; set; }

    public decimal? GAM_IRD_ { get; set; }

    public decimal? RES_IRD_ { get; set; }

    public decimal? CAL_IRD_ { get; set; }

    public decimal? DEN_IRD_ { get; set; }

    public decimal? DEN_CPS_IRD_ { get; set; }

    public decimal? DEN_CORR { get; set; }

    public decimal? CALIPER { get; set; }

    public decimal? DENSITY { get; set; }

    public decimal? DENSITYH { get; set; }

    public decimal? NDEV { get; set; }

    public decimal? EDEV { get; set; }

    public decimal? DISTANCE { get; set; }

    public decimal? AZIMUTH { get; set; }

    public decimal? SANG { get; set; }

    public decimal? SANGB { get; set; }

    public decimal? DIP { get; set; }

    public decimal? SUSCEP { get; set; }

    public decimal? GAM_GAM { get; set; }
}