// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class LASHeader
{
    public string WELL { get; set; }

    public decimal? STRT { get; set; }

    public decimal? STOP { get; set; }

    public decimal? STEP { get; set; }

    public decimal? NULL { get; set; }

    public string COMP { get; set; }

    public string FLD { get; set; }

    public string LOC { get; set; }

    public string CNTY { get; set; }

    public string STAT { get; set; }

    public string SRVC { get; set; }

    public string DATE { get; set; }

    public string UWI { get; set; }

    public string LIC { get; set; }

    public string SRVY { get; set; }
}