// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class PlodHeader
{
    public int DP_Plod { get; set; }

    public string DP_MineSite { get; set; }

    public DateOnly DP_Date { get; set; }

    public string DP_Rig { get; set; }

    public string DP_Location { get; set; }

    public string DP_Shift { get; set; }

    public string DP_Geologist { get; set; }

    public bool? DP_Complete { get; set; }

    public virtual MineSites DP_MineSiteNavigation { get; set; }

    public virtual RangerDrillRigs DP_RigNavigation { get; set; }

    public virtual Shifts DP_ShiftNavigation { get; set; }

    public virtual ICollection<PlodActivity> PlodActivity { get; set; } = new List<PlodActivity>();

    public virtual ICollection<PlodAlerts> PlodAlerts { get; set; } = new List<PlodAlerts>();

    public virtual PlodComments PlodComments { get; set; }

    public virtual ICollection<PlodConsumables> PlodConsumables { get; set; } = new List<PlodConsumables>();

    public virtual ICollection<PlodEquipment> PlodEquipment { get; set; } = new List<PlodEquipment>();

    public virtual ICollection<PlodHole> PlodHole { get; set; } = new List<PlodHole>();

    public virtual ICollection<PlodHoleDetails> PlodHoleDetails { get; set; } = new List<PlodHoleDetails>();
}