// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class PlodHeader1
{
    public string DP_Vehicle { get; set; }

    public DateOnly DP_Date { get; set; }

    public string DP_Client { get; set; }

    public string DP_Project { get; set; }

    public string DP_Lease { get; set; }

    public string DP_Location { get; set; }

    public string DP_Operator { get; set; }

    public bool? DP_Charge { get; set; }

    public bool? DP_Complete { get; set; }

    public virtual ICollection<PlodActivity1> PlodActivity1 { get; set; } = new List<PlodActivity1>();

    public virtual PlodDetails PlodDetails { get; set; }

    public virtual ICollection<PlodEquipment1> PlodEquipment1 { get; set; } = new List<PlodEquipment1>();
}