// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class PlodComments
{
    public int PlodID { get; set; }

    public string DrillerComment { get; set; }

    public string GeologistComment { get; set; }

    public virtual PlodHeader Plod { get; set; }
}