// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class PlodActivity1
{
    public string Vehicle { get; set; }

    public DateOnly Date { get; set; }

    public TimeOnly HourFrom { get; set; }

    public TimeOnly HourTo { get; set; }

    public string Activity { get; set; }

    public string HoleID { get; set; }

    public int? Northing { get; set; }

    public int? Easting { get; set; }

    public int? GPSNorthing { get; set; }

    public int? GPSEasting { get; set; }

    public string HoleCondition { get; set; }

    public string Geologist { get; set; }

    public int? DrillTD { get; set; }

    public decimal? Dummy { get; set; }

    public decimal? Magsus { get; set; }

    public decimal? Density { get; set; }

    public string Comment { get; set; }

    public bool? HoleComplete { get; set; }

    public virtual PlodHeader1 PlodHeader1 { get; set; }
}