// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class PlodAlerts1
{
    public string Vehicle { get; set; }

    public int AlertNumber { get; set; }

    public string AlertType { get; set; }

    public string AlertDescription { get; set; }
}