// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class RangerPlodActivity
{
    public int ActivityID { get; set; }

    public string ActivityNumber { get; set; }

    public string ActivityDescription { get; set; }

    public string ActivityReason { get; set; }

    public bool ActivityChargeable { get; set; }
}