// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class RangerPlodConsumables
{
    public int ConsumableID { get; set; }

    public int? ConsumableNumber { get; set; }

    public string ConsumableDescription { get; set; }

    public bool? ConsumableChargeable { get; set; }
}