// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class ReportActivity
{
    public string Vehicle { get; set; }

    public DateOnly Date { get; set; }

    public string HoleID { get; set; }

    public string Activity { get; set; }

    public TimeOnly HourFrom { get; set; }

    public TimeOnly HourTo { get; set; }

    public int DrillTD { get; set; }
}