// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RHOKSAutomationConsole.EFRHOKS2024;

public partial class ReportHeader
{
    public string Vehicle { get; set; }

    public DateOnly Date { get; set; }

    public string HoleID { get; set; }

    public int? X_Plan { get; set; }

    public int? Y_Plan { get; set; }

    public int? X_Meas { get; set; }

    public int? Y_Meas { get; set; }
}